// Code generated by protoc-gen-meshgo. DO NOT EDIT.
// source: api/proto/legal/company/service.proto
package company

import (
	context "context"
)

type Service interface {
	List(ctx context.Context, request *ListRequest) (*ListResponse, error)
}

const ServiceServiceProviderName = "api-legal-company-Service"
