// Code generated by protoc-gen-meshgo. DO NOT EDIT.
// source: api/proto/legal/company/service.proto
package company

import (
	context "context"
	fmt "fmt"
	log "github.com/rs/zerolog/log"
	trace "go.opentelemetry.io/otel/trace"
	grpc "google.golang.org/grpc"
)

// Ensure that GRPCClientService implements the Service interface
var _ Service = &GRPCClientService{}

// GRPCClientService is a gRPC client implementation of the Service interface.
type GRPCClientService struct {
	tracer     trace.Tracer
	grpcClient ServiceClient
}

func NewGRPCClientService(
	tracer trace.Tracer,
	grpcClientConnection *grpc.ClientConn,
) *GRPCClientService {
	return &GRPCClientService{
		tracer:     tracer,
		grpcClient: NewServiceClient(grpcClientConnection),
	}
}

func (g *GRPCClientService) List(ctx context.Context, request *ListRequest) (*ListResponse, error) {
	ctx, span := g.tracer.Start(
		ctx,
		ServiceServiceProviderName+"List",
	)
	defer span.End()

	// call given implementation of the adapted service provider interface
	listResponse, err := g.grpcClient.List(ctx, request)
	if err != nil {
		log.Ctx(ctx).Error().Err(err).Msg("could not List")
		return nil, fmt.Errorf("could not List: %s", err)
	}

	return listResponse, nil
}
