// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: meshtrade/iam/user/v1/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Email address of the user.
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Roles is a list of the standard roles assigned to this user
	// prepended by the name of the group in which they have been assigned that role.
	// e.g. groups/{group_id}/{role}, where role is one of the rolev1.Role enum
	Roles         []string `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_meshtrade_iam_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_meshtrade_iam_user_v1_user_proto protoreflect.FileDescriptor

const file_meshtrade_iam_user_v1_user_proto_rawDesc = "" +
	"\n" +
	" meshtrade/iam/user/v1/user.proto\x12\x15meshtrade.iam.user.v1\"2\n" +
	"\x04User\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05roles\x18\x06 \x03(\tR\x05rolesB0Z.github.com/meshtrade/api/go/iam/user/v1;userv1b\x06proto3"

var (
	file_meshtrade_iam_user_v1_user_proto_rawDescOnce sync.Once
	file_meshtrade_iam_user_v1_user_proto_rawDescData []byte
)

func file_meshtrade_iam_user_v1_user_proto_rawDescGZIP() []byte {
	file_meshtrade_iam_user_v1_user_proto_rawDescOnce.Do(func() {
		file_meshtrade_iam_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshtrade_iam_user_v1_user_proto_rawDesc), len(file_meshtrade_iam_user_v1_user_proto_rawDesc)))
	})
	return file_meshtrade_iam_user_v1_user_proto_rawDescData
}

var file_meshtrade_iam_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meshtrade_iam_user_v1_user_proto_goTypes = []any{
	(*User)(nil), // 0: meshtrade.iam.user.v1.User
}
var file_meshtrade_iam_user_v1_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meshtrade_iam_user_v1_user_proto_init() }
func file_meshtrade_iam_user_v1_user_proto_init() {
	if File_meshtrade_iam_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshtrade_iam_user_v1_user_proto_rawDesc), len(file_meshtrade_iam_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshtrade_iam_user_v1_user_proto_goTypes,
		DependencyIndexes: file_meshtrade_iam_user_v1_user_proto_depIdxs,
		MessageInfos:      file_meshtrade_iam_user_v1_user_proto_msgTypes,
	}.Build()
	File_meshtrade_iam_user_v1_user_proto = out.File
	file_meshtrade_iam_user_v1_user_proto_goTypes = nil
	file_meshtrade_iam_user_v1_user_proto_depIdxs = nil
}
