// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: instrument/fee/dataAmount.proto

package fee

import (
	ledger "github.com/meshtrade/api/go/ledger"
	num "github.com/meshtrade/api/go/num"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AmountData is the additional calculation data for a Fee
// of a fixed amount.
// This is used for flat fees that do not depend on a variable
// base amount and percentage for calculation.
//
// @bson-marshalled
type AmountData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AmountExclVAT is the VAT exclusive amount used to calculate
	// Fee.VatAmount and the resulting Fee.AmountInclVAT.
	AmountExclVAT *ledger.Amount `protobuf:"bytes,1,opt,name=amountExclVAT,proto3" json:"amountExclVAT,omitempty"`
	// VATRate is the rate used to calculate Fee.VatAmount.
	VatRate       *num.Decimal `protobuf:"bytes,2,opt,name=vatRate,proto3" json:"vatRate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AmountData) Reset() {
	*x = AmountData{}
	mi := &file_instrument_fee_dataAmount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmountData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmountData) ProtoMessage() {}

func (x *AmountData) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_fee_dataAmount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmountData.ProtoReflect.Descriptor instead.
func (*AmountData) Descriptor() ([]byte, []int) {
	return file_instrument_fee_dataAmount_proto_rawDescGZIP(), []int{0}
}

func (x *AmountData) GetAmountExclVAT() *ledger.Amount {
	if x != nil {
		return x.AmountExclVAT
	}
	return nil
}

func (x *AmountData) GetVatRate() *num.Decimal {
	if x != nil {
		return x.VatRate
	}
	return nil
}

var File_instrument_fee_dataAmount_proto protoreflect.FileDescriptor

const file_instrument_fee_dataAmount_proto_rawDesc = "" +
	"\n" +
	"\x1finstrument/fee/dataAmount.proto\x12\x12api.instrument.fee\x1a\x13ledger/amount.proto\x1a\x11num/decimal.proto\"r\n" +
	"\n" +
	"AmountData\x128\n" +
	"\ramountExclVAT\x18\x01 \x01(\v2\x12.api.ledger.AmountR\ramountExclVAT\x12*\n" +
	"\avatRate\x18\x02 \x01(\v2\x10.api.num.DecimalR\avatRateB,Z*github.com/meshtrade/api/go/instrument/feeb\x06proto3"

var (
	file_instrument_fee_dataAmount_proto_rawDescOnce sync.Once
	file_instrument_fee_dataAmount_proto_rawDescData []byte
)

func file_instrument_fee_dataAmount_proto_rawDescGZIP() []byte {
	file_instrument_fee_dataAmount_proto_rawDescOnce.Do(func() {
		file_instrument_fee_dataAmount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_instrument_fee_dataAmount_proto_rawDesc), len(file_instrument_fee_dataAmount_proto_rawDesc)))
	})
	return file_instrument_fee_dataAmount_proto_rawDescData
}

var file_instrument_fee_dataAmount_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_instrument_fee_dataAmount_proto_goTypes = []any{
	(*AmountData)(nil),    // 0: api.instrument.fee.AmountData
	(*ledger.Amount)(nil), // 1: api.ledger.Amount
	(*num.Decimal)(nil),   // 2: api.num.Decimal
}
var file_instrument_fee_dataAmount_proto_depIdxs = []int32{
	1, // 0: api.instrument.fee.AmountData.amountExclVAT:type_name -> api.ledger.Amount
	2, // 1: api.instrument.fee.AmountData.vatRate:type_name -> api.num.Decimal
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_instrument_fee_dataAmount_proto_init() }
func file_instrument_fee_dataAmount_proto_init() {
	if File_instrument_fee_dataAmount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_instrument_fee_dataAmount_proto_rawDesc), len(file_instrument_fee_dataAmount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_instrument_fee_dataAmount_proto_goTypes,
		DependencyIndexes: file_instrument_fee_dataAmount_proto_depIdxs,
		MessageInfos:      file_instrument_fee_dataAmount_proto_msgTypes,
	}.Build()
	File_instrument_fee_dataAmount_proto = out.File
	file_instrument_fee_dataAmount_proto_goTypes = nil
	file_instrument_fee_dataAmount_proto_depIdxs = nil
}
