// Code generated by protoc-gen-meshgo. DO NOT EDIT.
// source: instrument/fee/service.proto
package fee

import (
	context "context"
	fmt "fmt"
	log "github.com/rs/zerolog/log"
	trace "go.opentelemetry.io/otel/trace"
	grpc "google.golang.org/grpc"
)

// Ensure that GRPCClientService implements the Service interface
var _ Service = &GRPCClientService{}

// GRPCClientService is a gRPC client implementation of the Service interface.
type GRPCClientService struct {
	tracer     trace.Tracer
	grpcClient ServiceClient
}

func NewGRPCClientService(
	tracer trace.Tracer,
	grpcClientConnection *grpc.ClientConn,
) *GRPCClientService {
	return &GRPCClientService{
		tracer:     tracer,
		grpcClient: NewServiceClient(grpcClientConnection),
	}
}

func (g *GRPCClientService) Get(ctx context.Context, request *GetRequest) (*GetResponse, error) {
	ctx, span := g.tracer.Start(
		ctx,
		ServiceServiceProviderName+"Get",
	)
	defer span.End()

	// call given implementation of the adapted service provider interface
	getResponse, err := g.grpcClient.Get(ctx, request)
	if err != nil {
		log.Ctx(ctx).Error().Err(err).Msg("could not Get")
		return nil, fmt.Errorf("could not Get: %s", err)
	}

	return getResponse, nil
}

func (g *GRPCClientService) List(ctx context.Context, request *ListRequest) (*ListResponse, error) {
	ctx, span := g.tracer.Start(
		ctx,
		ServiceServiceProviderName+"List",
	)
	defer span.End()

	// call given implementation of the adapted service provider interface
	listResponse, err := g.grpcClient.List(ctx, request)
	if err != nil {
		log.Ctx(ctx).Error().Err(err).Msg("could not List")
		return nil, fmt.Errorf("could not List: %s", err)
	}

	return listResponse, nil
}

func (g *GRPCClientService) CalculateMintingFees(ctx context.Context, request *CalculateMintingFeesRequest) (*CalculateMintingFeesResponse, error) {
	ctx, span := g.tracer.Start(
		ctx,
		ServiceServiceProviderName+"CalculateMintingFees",
	)
	defer span.End()

	// call given implementation of the adapted service provider interface
	calculateMintingFeesResponse, err := g.grpcClient.CalculateMintingFees(ctx, request)
	if err != nil {
		log.Ctx(ctx).Error().Err(err).Msg("could not CalculateMintingFees")
		return nil, fmt.Errorf("could not CalculateMintingFees: %s", err)
	}

	return calculateMintingFeesResponse, nil
}

func (g *GRPCClientService) CalculateBurningFees(ctx context.Context, request *CalculateBurningFeesRequest) (*CalculateBurningFeesResponse, error) {
	ctx, span := g.tracer.Start(
		ctx,
		ServiceServiceProviderName+"CalculateBurningFees",
	)
	defer span.End()

	// call given implementation of the adapted service provider interface
	calculateBurningFeesResponse, err := g.grpcClient.CalculateBurningFees(ctx, request)
	if err != nil {
		log.Ctx(ctx).Error().Err(err).Msg("could not CalculateBurningFees")
		return nil, fmt.Errorf("could not CalculateBurningFees: %s", err)
	}

	return calculateBurningFeesResponse, nil
}
