// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file legal/company/service.proto (package api.legal.company, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Criterion } from "../../search/criterion_pb";
import { file_search_criterion } from "../../search/criterion_pb";
import type { Query } from "../../search/query_pb";
import { file_search_query } from "../../search/query_pb";
import type { Company } from "./company_pb";
import { file_legal_company_company } from "./company_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file legal/company/service.proto.
 */
export const file_legal_company_service: GenFile = /*@__PURE__*/
  fileDesc("ChtsZWdhbC9jb21wYW55L3NlcnZpY2UucHJvdG8SEWFwaS5sZWdhbC5jb21wYW55IlgKC0xpc3RSZXF1ZXN0EicKCGNyaXRlcmlhGAEgAygLMhUuYXBpLnNlYXJjaC5Dcml0ZXJpb24SIAoFcXVlcnkYAiABKAsyES5hcGkuc2VhcmNoLlF1ZXJ5IkwKDExpc3RSZXNwb25zZRItCgljb21wYW5pZXMYASADKAsyGi5hcGkubGVnYWwuY29tcGFueS5Db21wYW55Eg0KBXRvdGFsGAIgASgDMlIKB1NlcnZpY2USRwoETGlzdBIeLmFwaS5sZWdhbC5jb21wYW55Lkxpc3RSZXF1ZXN0Gh8uYXBpLmxlZ2FsLmNvbXBhbnkuTGlzdFJlc3BvbnNlQitaKWdpdGh1Yi5jb20vbWVzaHRyYWRlL2FwaS9nby9sZWdhbC9jb21wYW55YgZwcm90bzM", [file_search_criterion, file_search_query, file_legal_company_company]);

/**
 *
 * ListRequest is the List method request on the Fee Service.
 *
 * @generated from message api.legal.company.ListRequest
 */
export type ListRequest = Message<"api.legal.company.ListRequest"> & {
  /**
   *
   * Criteria is the search criteria that specifies which fees to retrieve.
   *
   * @generated from field: repeated api.search.Criterion criteria = 1;
   */
  criteria: Criterion[];

  /**
   *
   * Query controls pagination of the fees.
   *
   * @generated from field: api.search.Query query = 2;
   */
  query?: Query;
};

/**
 * Describes the message api.legal.company.ListRequest.
 * Use `create(ListRequestSchema)` to create a new message.
 */
export const ListRequestSchema: GenMessage<ListRequest> = /*@__PURE__*/
  messageDesc(file_legal_company_service, 0);

/**
 *
 * ListResponse is the List method response on the Fee Service.
 *
 * @generated from message api.legal.company.ListResponse
 */
export type ListResponse = Message<"api.legal.company.ListResponse"> & {
  /**
   *
   * Fees are the list of fees that were retrieved.
   *
   * @generated from field: repeated api.legal.company.Company companies = 1;
   */
  companies: Company[];

  /**
   *
   * Total is the total number of fees that match the given criteria.
   *
   * @generated from field: int64 total = 2;
   */
  total: bigint;
};

/**
 * Describes the message api.legal.company.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema: GenMessage<ListResponse> = /*@__PURE__*/
  messageDesc(file_legal_company_service, 1);

/**
 * @generated from service api.legal.company.Service
 */
export const Service: GenService<{
  /**
   * @generated from rpc api.legal.company.Service.List
   */
  list: {
    methodKind: "unary";
    input: typeof ListRequestSchema;
    output: typeof ListResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_legal_company_service, 0);

