# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/proto/ledger/amount.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'api/proto/ledger/amount.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.python.lib.ledger import token_pb2 as api_dot_proto_dot_ledger_dot_token__pb2
from api.python.lib.num import decimal_pb2 as api_dot_proto_dot_num_dot_decimal__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61pi/proto/ledger/amount.proto\x12\napi.ledger\x1a\x1c\x61pi/proto/ledger/token.proto\x1a\x1b\x61pi/proto/num/decimal.proto\"K\n\x06\x41mount\x12 \n\x05token\x18\x01 \x01(\x0b\x32\x11.api.ledger.Token\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.api.num.DecimalB$Z\"github.com/meshtrade/api/go/ledgerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.python.lib.ledger.amount_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"github.com/meshtrade/api/go/ledger'
  _globals['_AMOUNT']._serialized_start=104
  _globals['_AMOUNT']._serialized_end=179
# @@protoc_insertion_point(module_scope)
