title: Mesh API
description: Home of the Mesh API Documentation.
theme: just-the-docs

url: https://github.com/meshtrade/api

mermaid:
  version: "11.6.0"

logo: "/docs/assets/images/logo.svg"
favicon_ico: "/docs/assets/images/favicon.svg"