// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file legal/companyRepresentative.proto (package api.legal, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Address } from "../location/address_pb";
import { file_location_address } from "../location/address_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file legal/companyRepresentative.proto.
 */
export const file_legal_companyRepresentative: GenFile = /*@__PURE__*/
  fileDesc("CiFsZWdhbC9jb21wYW55UmVwcmVzZW50YXRpdmUucHJvdG8SCWFwaS5sZWdhbCL3AQoVQ29tcGFueVJlcHJlc2VudGF0aXZlEhEKCWZpcnN0TmFtZRgBIAEoCRITCgttaWRkbGVOYW1lcxgCIAEoCRIQCghsYXN0TmFtZRgDIAEoCRIXCg90ZWxlcGhvbmVOdW1iZXIYBCABKAkSFwoPY2VsbHBob25lTnVtYmVyGAUgASgJEhQKDGVtYWlsQWRkcmVzcxgGIAEoCRIuCg9waHlzaWNhbEFkZHJlc3MYByABKAsyFS5hcGkubG9jYXRpb24uQWRkcmVzcxIsCg1wb3N0YWxBZGRyZXNzGAggASgLMhUuYXBpLmxvY2F0aW9uLkFkZHJlc3NCI1ohZ2l0aHViLmNvbS9tZXNodHJhZGUvYXBpL2dvL2xlZ2FsYgZwcm90bzM", [file_location_address]);

/**
 * @generated from message api.legal.CompanyRepresentative
 */
export type CompanyRepresentative = Message<"api.legal.CompanyRepresentative"> & {
  /**
   * First name of the company representative
   *
   * @generated from field: string firstName = 1;
   */
  firstName: string;

  /**
   * Middle names of the company representative (optional)
   *
   * @generated from field: string middleNames = 2;
   */
  middleNames: string;

  /**
   * Last name of the company representative
   *
   * @generated from field: string lastName = 3;
   */
  lastName: string;

  /**
   * Telephone number of the representative
   *
   * @generated from field: string telephoneNumber = 4;
   */
  telephoneNumber: string;

  /**
   * Cellphone number of the representative
   *
   * @generated from field: string cellphoneNumber = 5;
   */
  cellphoneNumber: string;

  /**
   * Email address of the representative
   *
   * @generated from field: string emailAddress = 6;
   */
  emailAddress: string;

  /**
   * Physical address of the representative
   *
   * @generated from field: api.location.Address physicalAddress = 7;
   */
  physicalAddress?: Address;

  /**
   * Postal address of the representative
   *
   * @generated from field: api.location.Address postalAddress = 8;
   */
  postalAddress?: Address;
};

/**
 * Describes the message api.legal.CompanyRepresentative.
 * Use `create(CompanyRepresentativeSchema)` to create a new message.
 */
export const CompanyRepresentativeSchema: GenMessage<CompanyRepresentative> = /*@__PURE__*/
  messageDesc(file_legal_companyRepresentative, 0);

