import * as jspb from 'google-protobuf'



export enum ConnectedIndividualConnectionType { 
  UNDEFINED_CONNECTED_INDIVIDUAL_CONNECTION_TYPE = 0,
  MANAGER_CONNECTED_INDIVIDUAL_CONNECTION_TYPE = 1,
  SHAREHOLDER_CONNECTED_INDIVIDUAL_CONNECTION_TYPE = 2,
  AGENT_CONNECTED_INDIVIDUAL_CONNECTION_TYPE = 3,
  SOLE_PROPRIETOR_CONNECTED_INDIVIDUAL_CONNECTION_TYPE = 4,
  PARTNER_CONNECTED_INDIVIDUAL_CONNECTION_TYPE = 5,
}
