import * as jspb from 'google-protobuf'



export enum LifecycleEventFeeTrigger { 
  UNDEFINED_LIFECYCLE_EVENT_FEE_TRIGGER = 0,
  LISTING_LIFECYCLE_EVENT_FEE_TRIGGER = 1,
  PRIMARY_MARKET_SETTLEMENT_LIFECYCLE_EVENT_FEE_TRIGGER = 2,
}
