// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file instrument/feeprofile/lifecycleEvent.proto (package api.instrument.feeprofile, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { LifecycleEventCategory } from "./lifecycleEventCategory_pb";
import { file_instrument_feeprofile_lifecycleEventCategory } from "./lifecycleEventCategory_pb";
import type { LifecycleEventCalculationConfig } from "./lifecycleEventCalculationConfig_pb";
import { file_instrument_feeprofile_lifecycleEventCalculationConfig } from "./lifecycleEventCalculationConfig_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file instrument/feeprofile/lifecycleEvent.proto.
 */
export const file_instrument_feeprofile_lifecycleEvent: GenFile = /*@__PURE__*/
  fileDesc("CippbnN0cnVtZW50L2ZlZXByb2ZpbGUvbGlmZWN5Y2xlRXZlbnQucHJvdG8SGWFwaS5pbnN0cnVtZW50LmZlZXByb2ZpbGUiwQEKDkxpZmVjeWNsZUV2ZW50EhMKC2Rlc2NyaXB0aW9uGAEgASgJEkMKCGNhdGVnb3J5GAIgASgOMjEuYXBpLmluc3RydW1lbnQuZmVlcHJvZmlsZS5MaWZlY3ljbGVFdmVudENhdGVnb3J5ElUKEWNhbGN1bGF0aW9uQ29uZmlnGAMgASgLMjouYXBpLmluc3RydW1lbnQuZmVlcHJvZmlsZS5MaWZlY3ljbGVFdmVudENhbGN1bGF0aW9uQ29uZmlnQjNaMWdpdGh1Yi5jb20vbWVzaHRyYWRlL2FwaS9nby9pbnN0cnVtZW50L2ZlZXByb2ZpbGViBnByb3RvMw", [file_instrument_feeprofile_lifecycleEventCategory, file_instrument_feeprofile_lifecycleEventCalculationConfig]);

/**
 *
 * LifecycleEvents configures the fees associated with various stages in the
 * Instrument's lifecycle.
 * Lifecycle events are significant milestones or actions that may incur
 * fees, such as:
 * - Listing: Fees for listing the Instrument on Mesh.
 * - Primary Market Settlement: Fees related to the settlement of
 * transactions in the primary market.
 *
 * Multiple lifecycle events can be configured and managed within a single
 * FeeProfile.
 *
 * @generated from message api.instrument.feeprofile.LifecycleEvent
 */
export type LifecycleEvent = Message<"api.instrument.feeprofile.LifecycleEvent"> & {
  /**
   *
   * Description is the description of the Fee charged on this LifecycleEvent.
   * The description must be unique is the sense that the same description
   * cannot be used more than once for a single trigger.
   *
   * @generated from field: string description = 1;
   */
  description: string;

  /**
   *
   * Category is the Instrument lifecycle event type that leads to a Fee being charged.
   *
   * @generated from field: api.instrument.feeprofile.LifecycleEventCategory category = 2;
   */
  category: LifecycleEventCategory;

  /**
   *
   * CalculationConfig defines how the Fee on this lifecycle event is calculated.
   * Implementations include:
   * - Amount: The Fee amount is fixed and pre-determined.
   * - Rate: The Fee amount is variable are calculated as a percentage of a
   * base amount. The base amount used is contextual to the lifecycle event.
   *
   * @generated from field: api.instrument.feeprofile.LifecycleEventCalculationConfig calculationConfig = 3;
   */
  calculationConfig?: LifecycleEventCalculationConfig;
};

/**
 * Describes the message api.instrument.feeprofile.LifecycleEvent.
 * Use `create(LifecycleEventSchema)` to create a new message.
 */
export const LifecycleEventSchema: GenMessage<LifecycleEvent> = /*@__PURE__*/
  messageDesc(file_instrument_feeprofile_lifecycleEvent, 0);

