// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meshtrade/reporting/income_report/v1/entry.proto

// Protobuf Java Version: 3.25.1
package meshtrade.reporting.income_report.v1;

public final class EntryOuterClass {
  private EntryOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:meshtrade.reporting.income_report.v1.Entry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string asset_name = 1 [json_name = "assetName"];</code>
     * @return The assetName.
     */
    java.lang.String getAssetName();
    /**
     * <code>string asset_name = 1 [json_name = "assetName"];</code>
     * @return The bytes for assetName.
     */
    com.google.protobuf.ByteString
        getAssetNameBytes();

    /**
     * <code>.meshtrade.type.v1.Token token = 2 [json_name = "token"];</code>
     * @return Whether the token field is set.
     */
    boolean hasToken();
    /**
     * <code>.meshtrade.type.v1.Token token = 2 [json_name = "token"];</code>
     * @return The token.
     */
    co.meshtrade.api.type.v1.TokenOuterClass.Token getToken();
    /**
     * <code>.meshtrade.type.v1.Token token = 2 [json_name = "token"];</code>
     */
    co.meshtrade.api.type.v1.TokenOuterClass.TokenOrBuilder getTokenOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp date = 3 [json_name = "date"];</code>
     * @return Whether the date field is set.
     */
    boolean hasDate();
    /**
     * <code>.google.protobuf.Timestamp date = 3 [json_name = "date"];</code>
     * @return The date.
     */
    com.google.protobuf.Timestamp getDate();
    /**
     * <code>.google.protobuf.Timestamp date = 3 [json_name = "date"];</code>
     */
    com.google.protobuf.TimestampOrBuilder getDateOrBuilder();

    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>string narrative = 5 [json_name = "narrative"];</code>
     * @return The narrative.
     */
    java.lang.String getNarrative();
    /**
     * <code>string narrative = 5 [json_name = "narrative"];</code>
     * @return The bytes for narrative.
     */
    com.google.protobuf.ByteString
        getNarrativeBytes();

    /**
     * <code>.meshtrade.type.v1.Amount amount = 6 [json_name = "amount"];</code>
     * @return Whether the amount field is set.
     */
    boolean hasAmount();
    /**
     * <code>.meshtrade.type.v1.Amount amount = 6 [json_name = "amount"];</code>
     * @return The amount.
     */
    co.meshtrade.api.type.v1.AmountOuterClass.Amount getAmount();
    /**
     * <code>.meshtrade.type.v1.Amount amount = 6 [json_name = "amount"];</code>
     */
    co.meshtrade.api.type.v1.AmountOuterClass.AmountOrBuilder getAmountOrBuilder();

    /**
     * <code>.meshtrade.type.v1.Amount reported_currency_value = 7 [json_name = "reportedCurrencyValue"];</code>
     * @return Whether the reportedCurrencyValue field is set.
     */
    boolean hasReportedCurrencyValue();
    /**
     * <code>.meshtrade.type.v1.Amount reported_currency_value = 7 [json_name = "reportedCurrencyValue"];</code>
     * @return The reportedCurrencyValue.
     */
    co.meshtrade.api.type.v1.AmountOuterClass.Amount getReportedCurrencyValue();
    /**
     * <code>.meshtrade.type.v1.Amount reported_currency_value = 7 [json_name = "reportedCurrencyValue"];</code>
     */
    co.meshtrade.api.type.v1.AmountOuterClass.AmountOrBuilder getReportedCurrencyValueOrBuilder();
  }
  /**
   * Protobuf type {@code meshtrade.reporting.income_report.v1.Entry}
   */
  public static final class Entry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:meshtrade.reporting.income_report.v1.Entry)
      EntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Entry.newBuilder() to construct.
    private Entry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Entry() {
      assetName_ = "";
      description_ = "";
      narrative_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Entry();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return meshtrade.reporting.income_report.v1.EntryOuterClass.internal_static_meshtrade_reporting_income_report_v1_Entry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return meshtrade.reporting.income_report.v1.EntryOuterClass.internal_static_meshtrade_reporting_income_report_v1_Entry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              meshtrade.reporting.income_report.v1.EntryOuterClass.Entry.class, meshtrade.reporting.income_report.v1.EntryOuterClass.Entry.Builder.class);
    }

    private int bitField0_;
    public static final int ASSET_NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object assetName_ = "";
    /**
     * <code>string asset_name = 1 [json_name = "assetName"];</code>
     * @return The assetName.
     */
    @java.lang.Override
    public java.lang.String getAssetName() {
      java.lang.Object ref = assetName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assetName_ = s;
        return s;
      }
    }
    /**
     * <code>string asset_name = 1 [json_name = "assetName"];</code>
     * @return The bytes for assetName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAssetNameBytes() {
      java.lang.Object ref = assetName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assetName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private co.meshtrade.api.type.v1.TokenOuterClass.Token token_;
    /**
     * <code>.meshtrade.type.v1.Token token = 2 [json_name = "token"];</code>
     * @return Whether the token field is set.
     */
    @java.lang.Override
    public boolean hasToken() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.meshtrade.type.v1.Token token = 2 [json_name = "token"];</code>
     * @return The token.
     */
    @java.lang.Override
    public co.meshtrade.api.type.v1.TokenOuterClass.Token getToken() {
      return token_ == null ? co.meshtrade.api.type.v1.TokenOuterClass.Token.getDefaultInstance() : token_;
    }
    /**
     * <code>.meshtrade.type.v1.Token token = 2 [json_name = "token"];</code>
     */
    @java.lang.Override
    public co.meshtrade.api.type.v1.TokenOuterClass.TokenOrBuilder getTokenOrBuilder() {
      return token_ == null ? co.meshtrade.api.type.v1.TokenOuterClass.Token.getDefaultInstance() : token_;
    }

    public static final int DATE_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp date_;
    /**
     * <code>.google.protobuf.Timestamp date = 3 [json_name = "date"];</code>
     * @return Whether the date field is set.
     */
    @java.lang.Override
    public boolean hasDate() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp date = 3 [json_name = "date"];</code>
     * @return The date.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getDate() {
      return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 3 [json_name = "date"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
      return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NARRATIVE_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object narrative_ = "";
    /**
     * <code>string narrative = 5 [json_name = "narrative"];</code>
     * @return The narrative.
     */
    @java.lang.Override
    public java.lang.String getNarrative() {
      java.lang.Object ref = narrative_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        narrative_ = s;
        return s;
      }
    }
    /**
     * <code>string narrative = 5 [json_name = "narrative"];</code>
     * @return The bytes for narrative.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNarrativeBytes() {
      java.lang.Object ref = narrative_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        narrative_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 6;
    private co.meshtrade.api.type.v1.AmountOuterClass.Amount amount_;
    /**
     * <code>.meshtrade.type.v1.Amount amount = 6 [json_name = "amount"];</code>
     * @return Whether the amount field is set.
     */
    @java.lang.Override
    public boolean hasAmount() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.meshtrade.type.v1.Amount amount = 6 [json_name = "amount"];</code>
     * @return The amount.
     */
    @java.lang.Override
    public co.meshtrade.api.type.v1.AmountOuterClass.Amount getAmount() {
      return amount_ == null ? co.meshtrade.api.type.v1.AmountOuterClass.Amount.getDefaultInstance() : amount_;
    }
    /**
     * <code>.meshtrade.type.v1.Amount amount = 6 [json_name = "amount"];</code>
     */
    @java.lang.Override
    public co.meshtrade.api.type.v1.AmountOuterClass.AmountOrBuilder getAmountOrBuilder() {
      return amount_ == null ? co.meshtrade.api.type.v1.AmountOuterClass.Amount.getDefaultInstance() : amount_;
    }

    public static final int REPORTED_CURRENCY_VALUE_FIELD_NUMBER = 7;
    private co.meshtrade.api.type.v1.AmountOuterClass.Amount reportedCurrencyValue_;
    /**
     * <code>.meshtrade.type.v1.Amount reported_currency_value = 7 [json_name = "reportedCurrencyValue"];</code>
     * @return Whether the reportedCurrencyValue field is set.
     */
    @java.lang.Override
    public boolean hasReportedCurrencyValue() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.meshtrade.type.v1.Amount reported_currency_value = 7 [json_name = "reportedCurrencyValue"];</code>
     * @return The reportedCurrencyValue.
     */
    @java.lang.Override
    public co.meshtrade.api.type.v1.AmountOuterClass.Amount getReportedCurrencyValue() {
      return reportedCurrencyValue_ == null ? co.meshtrade.api.type.v1.AmountOuterClass.Amount.getDefaultInstance() : reportedCurrencyValue_;
    }
    /**
     * <code>.meshtrade.type.v1.Amount reported_currency_value = 7 [json_name = "reportedCurrencyValue"];</code>
     */
    @java.lang.Override
    public co.meshtrade.api.type.v1.AmountOuterClass.AmountOrBuilder getReportedCurrencyValueOrBuilder() {
      return reportedCurrencyValue_ == null ? co.meshtrade.api.type.v1.AmountOuterClass.Amount.getDefaultInstance() : reportedCurrencyValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(assetName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, assetName_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getToken());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(3, getDate());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(narrative_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, narrative_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(6, getAmount());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(7, getReportedCurrencyValue());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(assetName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, assetName_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getToken());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getDate());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(narrative_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, narrative_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getAmount());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getReportedCurrencyValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof meshtrade.reporting.income_report.v1.EntryOuterClass.Entry)) {
        return super.equals(obj);
      }
      meshtrade.reporting.income_report.v1.EntryOuterClass.Entry other = (meshtrade.reporting.income_report.v1.EntryOuterClass.Entry) obj;

      if (!getAssetName()
          .equals(other.getAssetName())) return false;
      if (hasToken() != other.hasToken()) return false;
      if (hasToken()) {
        if (!getToken()
            .equals(other.getToken())) return false;
      }
      if (hasDate() != other.hasDate()) return false;
      if (hasDate()) {
        if (!getDate()
            .equals(other.getDate())) return false;
      }
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getNarrative()
          .equals(other.getNarrative())) return false;
      if (hasAmount() != other.hasAmount()) return false;
      if (hasAmount()) {
        if (!getAmount()
            .equals(other.getAmount())) return false;
      }
      if (hasReportedCurrencyValue() != other.hasReportedCurrencyValue()) return false;
      if (hasReportedCurrencyValue()) {
        if (!getReportedCurrencyValue()
            .equals(other.getReportedCurrencyValue())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ASSET_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getAssetName().hashCode();
      if (hasToken()) {
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken().hashCode();
      }
      if (hasDate()) {
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDate().hashCode();
      }
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + NARRATIVE_FIELD_NUMBER;
      hash = (53 * hash) + getNarrative().hashCode();
      if (hasAmount()) {
        hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getAmount().hashCode();
      }
      if (hasReportedCurrencyValue()) {
        hash = (37 * hash) + REPORTED_CURRENCY_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getReportedCurrencyValue().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static meshtrade.reporting.income_report.v1.EntryOuterClass.Entry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static meshtrade.reporting.income_report.v1.EntryOuterClass.Entry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static meshtrade.reporting.income_report.v1.EntryOuterClass.Entry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static meshtrade.reporting.income_report.v1.EntryOuterClass.Entry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static meshtrade.reporting.income_report.v1.EntryOuterClass.Entry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static meshtrade.reporting.income_report.v1.EntryOuterClass.Entry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static meshtrade.reporting.income_report.v1.EntryOuterClass.Entry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static meshtrade.reporting.income_report.v1.EntryOuterClass.Entry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static meshtrade.reporting.income_report.v1.EntryOuterClass.Entry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static meshtrade.reporting.income_report.v1.EntryOuterClass.Entry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static meshtrade.reporting.income_report.v1.EntryOuterClass.Entry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static meshtrade.reporting.income_report.v1.EntryOuterClass.Entry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(meshtrade.reporting.income_report.v1.EntryOuterClass.Entry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code meshtrade.reporting.income_report.v1.Entry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:meshtrade.reporting.income_report.v1.Entry)
        meshtrade.reporting.income_report.v1.EntryOuterClass.EntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return meshtrade.reporting.income_report.v1.EntryOuterClass.internal_static_meshtrade_reporting_income_report_v1_Entry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return meshtrade.reporting.income_report.v1.EntryOuterClass.internal_static_meshtrade_reporting_income_report_v1_Entry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                meshtrade.reporting.income_report.v1.EntryOuterClass.Entry.class, meshtrade.reporting.income_report.v1.EntryOuterClass.Entry.Builder.class);
      }

      // Construct using meshtrade.reporting.income_report.v1.EntryOuterClass.Entry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTokenFieldBuilder();
          getDateFieldBuilder();
          getAmountFieldBuilder();
          getReportedCurrencyValueFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        assetName_ = "";
        token_ = null;
        if (tokenBuilder_ != null) {
          tokenBuilder_.dispose();
          tokenBuilder_ = null;
        }
        date_ = null;
        if (dateBuilder_ != null) {
          dateBuilder_.dispose();
          dateBuilder_ = null;
        }
        description_ = "";
        narrative_ = "";
        amount_ = null;
        if (amountBuilder_ != null) {
          amountBuilder_.dispose();
          amountBuilder_ = null;
        }
        reportedCurrencyValue_ = null;
        if (reportedCurrencyValueBuilder_ != null) {
          reportedCurrencyValueBuilder_.dispose();
          reportedCurrencyValueBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return meshtrade.reporting.income_report.v1.EntryOuterClass.internal_static_meshtrade_reporting_income_report_v1_Entry_descriptor;
      }

      @java.lang.Override
      public meshtrade.reporting.income_report.v1.EntryOuterClass.Entry getDefaultInstanceForType() {
        return meshtrade.reporting.income_report.v1.EntryOuterClass.Entry.getDefaultInstance();
      }

      @java.lang.Override
      public meshtrade.reporting.income_report.v1.EntryOuterClass.Entry build() {
        meshtrade.reporting.income_report.v1.EntryOuterClass.Entry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public meshtrade.reporting.income_report.v1.EntryOuterClass.Entry buildPartial() {
        meshtrade.reporting.income_report.v1.EntryOuterClass.Entry result = new meshtrade.reporting.income_report.v1.EntryOuterClass.Entry(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(meshtrade.reporting.income_report.v1.EntryOuterClass.Entry result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.assetName_ = assetName_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.token_ = tokenBuilder_ == null
              ? token_
              : tokenBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.date_ = dateBuilder_ == null
              ? date_
              : dateBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.description_ = description_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.narrative_ = narrative_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.amount_ = amountBuilder_ == null
              ? amount_
              : amountBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.reportedCurrencyValue_ = reportedCurrencyValueBuilder_ == null
              ? reportedCurrencyValue_
              : reportedCurrencyValueBuilder_.build();
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof meshtrade.reporting.income_report.v1.EntryOuterClass.Entry) {
          return mergeFrom((meshtrade.reporting.income_report.v1.EntryOuterClass.Entry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(meshtrade.reporting.income_report.v1.EntryOuterClass.Entry other) {
        if (other == meshtrade.reporting.income_report.v1.EntryOuterClass.Entry.getDefaultInstance()) return this;
        if (!other.getAssetName().isEmpty()) {
          assetName_ = other.assetName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasToken()) {
          mergeToken(other.getToken());
        }
        if (other.hasDate()) {
          mergeDate(other.getDate());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getNarrative().isEmpty()) {
          narrative_ = other.narrative_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.hasAmount()) {
          mergeAmount(other.getAmount());
        }
        if (other.hasReportedCurrencyValue()) {
          mergeReportedCurrencyValue(other.getReportedCurrencyValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                assetName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getTokenFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getDateFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                narrative_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getAmountFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                input.readMessage(
                    getReportedCurrencyValueFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object assetName_ = "";
      /**
       * <code>string asset_name = 1 [json_name = "assetName"];</code>
       * @return The assetName.
       */
      public java.lang.String getAssetName() {
        java.lang.Object ref = assetName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          assetName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string asset_name = 1 [json_name = "assetName"];</code>
       * @return The bytes for assetName.
       */
      public com.google.protobuf.ByteString
          getAssetNameBytes() {
        java.lang.Object ref = assetName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          assetName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string asset_name = 1 [json_name = "assetName"];</code>
       * @param value The assetName to set.
       * @return This builder for chaining.
       */
      public Builder setAssetName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        assetName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string asset_name = 1 [json_name = "assetName"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAssetName() {
        assetName_ = getDefaultInstance().getAssetName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string asset_name = 1 [json_name = "assetName"];</code>
       * @param value The bytes for assetName to set.
       * @return This builder for chaining.
       */
      public Builder setAssetNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        assetName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private co.meshtrade.api.type.v1.TokenOuterClass.Token token_;
      private com.google.protobuf.SingleFieldBuilderV3<
          co.meshtrade.api.type.v1.TokenOuterClass.Token, co.meshtrade.api.type.v1.TokenOuterClass.Token.Builder, co.meshtrade.api.type.v1.TokenOuterClass.TokenOrBuilder> tokenBuilder_;
      /**
       * <code>.meshtrade.type.v1.Token token = 2 [json_name = "token"];</code>
       * @return Whether the token field is set.
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.meshtrade.type.v1.Token token = 2 [json_name = "token"];</code>
       * @return The token.
       */
      public co.meshtrade.api.type.v1.TokenOuterClass.Token getToken() {
        if (tokenBuilder_ == null) {
          return token_ == null ? co.meshtrade.api.type.v1.TokenOuterClass.Token.getDefaultInstance() : token_;
        } else {
          return tokenBuilder_.getMessage();
        }
      }
      /**
       * <code>.meshtrade.type.v1.Token token = 2 [json_name = "token"];</code>
       */
      public Builder setToken(co.meshtrade.api.type.v1.TokenOuterClass.Token value) {
        if (tokenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          token_ = value;
        } else {
          tokenBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.meshtrade.type.v1.Token token = 2 [json_name = "token"];</code>
       */
      public Builder setToken(
          co.meshtrade.api.type.v1.TokenOuterClass.Token.Builder builderForValue) {
        if (tokenBuilder_ == null) {
          token_ = builderForValue.build();
        } else {
          tokenBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.meshtrade.type.v1.Token token = 2 [json_name = "token"];</code>
       */
      public Builder mergeToken(co.meshtrade.api.type.v1.TokenOuterClass.Token value) {
        if (tokenBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            token_ != null &&
            token_ != co.meshtrade.api.type.v1.TokenOuterClass.Token.getDefaultInstance()) {
            getTokenBuilder().mergeFrom(value);
          } else {
            token_ = value;
          }
        } else {
          tokenBuilder_.mergeFrom(value);
        }
        if (token_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.meshtrade.type.v1.Token token = 2 [json_name = "token"];</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000002);
        token_ = null;
        if (tokenBuilder_ != null) {
          tokenBuilder_.dispose();
          tokenBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.meshtrade.type.v1.Token token = 2 [json_name = "token"];</code>
       */
      public co.meshtrade.api.type.v1.TokenOuterClass.Token.Builder getTokenBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getTokenFieldBuilder().getBuilder();
      }
      /**
       * <code>.meshtrade.type.v1.Token token = 2 [json_name = "token"];</code>
       */
      public co.meshtrade.api.type.v1.TokenOuterClass.TokenOrBuilder getTokenOrBuilder() {
        if (tokenBuilder_ != null) {
          return tokenBuilder_.getMessageOrBuilder();
        } else {
          return token_ == null ?
              co.meshtrade.api.type.v1.TokenOuterClass.Token.getDefaultInstance() : token_;
        }
      }
      /**
       * <code>.meshtrade.type.v1.Token token = 2 [json_name = "token"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          co.meshtrade.api.type.v1.TokenOuterClass.Token, co.meshtrade.api.type.v1.TokenOuterClass.Token.Builder, co.meshtrade.api.type.v1.TokenOuterClass.TokenOrBuilder> 
          getTokenFieldBuilder() {
        if (tokenBuilder_ == null) {
          tokenBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              co.meshtrade.api.type.v1.TokenOuterClass.Token, co.meshtrade.api.type.v1.TokenOuterClass.Token.Builder, co.meshtrade.api.type.v1.TokenOuterClass.TokenOrBuilder>(
                  getToken(),
                  getParentForChildren(),
                  isClean());
          token_ = null;
        }
        return tokenBuilder_;
      }

      private com.google.protobuf.Timestamp date_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateBuilder_;
      /**
       * <code>.google.protobuf.Timestamp date = 3 [json_name = "date"];</code>
       * @return Whether the date field is set.
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp date = 3 [json_name = "date"];</code>
       * @return The date.
       */
      public com.google.protobuf.Timestamp getDate() {
        if (dateBuilder_ == null) {
          return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
        } else {
          return dateBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp date = 3 [json_name = "date"];</code>
       */
      public Builder setDate(com.google.protobuf.Timestamp value) {
        if (dateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          date_ = value;
        } else {
          dateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 3 [json_name = "date"];</code>
       */
      public Builder setDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (dateBuilder_ == null) {
          date_ = builderForValue.build();
        } else {
          dateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 3 [json_name = "date"];</code>
       */
      public Builder mergeDate(com.google.protobuf.Timestamp value) {
        if (dateBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            date_ != null &&
            date_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getDateBuilder().mergeFrom(value);
          } else {
            date_ = value;
          }
        } else {
          dateBuilder_.mergeFrom(value);
        }
        if (date_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 3 [json_name = "date"];</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        date_ = null;
        if (dateBuilder_ != null) {
          dateBuilder_.dispose();
          dateBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 3 [json_name = "date"];</code>
       */
      public com.google.protobuf.Timestamp.Builder getDateBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getDateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp date = 3 [json_name = "date"];</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
        if (dateBuilder_ != null) {
          return dateBuilder_.getMessageOrBuilder();
        } else {
          return date_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : date_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp date = 3 [json_name = "date"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDateFieldBuilder() {
        if (dateBuilder_ == null) {
          dateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDate(),
                  getParentForChildren(),
                  isClean());
          date_ = null;
        }
        return dateBuilder_;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 4 [json_name = "description"];</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 4 [json_name = "description"];</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 4 [json_name = "description"];</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 4 [json_name = "description"];</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string description = 4 [json_name = "description"];</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object narrative_ = "";
      /**
       * <code>string narrative = 5 [json_name = "narrative"];</code>
       * @return The narrative.
       */
      public java.lang.String getNarrative() {
        java.lang.Object ref = narrative_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          narrative_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string narrative = 5 [json_name = "narrative"];</code>
       * @return The bytes for narrative.
       */
      public com.google.protobuf.ByteString
          getNarrativeBytes() {
        java.lang.Object ref = narrative_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          narrative_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string narrative = 5 [json_name = "narrative"];</code>
       * @param value The narrative to set.
       * @return This builder for chaining.
       */
      public Builder setNarrative(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        narrative_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string narrative = 5 [json_name = "narrative"];</code>
       * @return This builder for chaining.
       */
      public Builder clearNarrative() {
        narrative_ = getDefaultInstance().getNarrative();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string narrative = 5 [json_name = "narrative"];</code>
       * @param value The bytes for narrative to set.
       * @return This builder for chaining.
       */
      public Builder setNarrativeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        narrative_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private co.meshtrade.api.type.v1.AmountOuterClass.Amount amount_;
      private com.google.protobuf.SingleFieldBuilderV3<
          co.meshtrade.api.type.v1.AmountOuterClass.Amount, co.meshtrade.api.type.v1.AmountOuterClass.Amount.Builder, co.meshtrade.api.type.v1.AmountOuterClass.AmountOrBuilder> amountBuilder_;
      /**
       * <code>.meshtrade.type.v1.Amount amount = 6 [json_name = "amount"];</code>
       * @return Whether the amount field is set.
       */
      public boolean hasAmount() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>.meshtrade.type.v1.Amount amount = 6 [json_name = "amount"];</code>
       * @return The amount.
       */
      public co.meshtrade.api.type.v1.AmountOuterClass.Amount getAmount() {
        if (amountBuilder_ == null) {
          return amount_ == null ? co.meshtrade.api.type.v1.AmountOuterClass.Amount.getDefaultInstance() : amount_;
        } else {
          return amountBuilder_.getMessage();
        }
      }
      /**
       * <code>.meshtrade.type.v1.Amount amount = 6 [json_name = "amount"];</code>
       */
      public Builder setAmount(co.meshtrade.api.type.v1.AmountOuterClass.Amount value) {
        if (amountBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          amount_ = value;
        } else {
          amountBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.meshtrade.type.v1.Amount amount = 6 [json_name = "amount"];</code>
       */
      public Builder setAmount(
          co.meshtrade.api.type.v1.AmountOuterClass.Amount.Builder builderForValue) {
        if (amountBuilder_ == null) {
          amount_ = builderForValue.build();
        } else {
          amountBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.meshtrade.type.v1.Amount amount = 6 [json_name = "amount"];</code>
       */
      public Builder mergeAmount(co.meshtrade.api.type.v1.AmountOuterClass.Amount value) {
        if (amountBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0) &&
            amount_ != null &&
            amount_ != co.meshtrade.api.type.v1.AmountOuterClass.Amount.getDefaultInstance()) {
            getAmountBuilder().mergeFrom(value);
          } else {
            amount_ = value;
          }
        } else {
          amountBuilder_.mergeFrom(value);
        }
        if (amount_ != null) {
          bitField0_ |= 0x00000020;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.meshtrade.type.v1.Amount amount = 6 [json_name = "amount"];</code>
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000020);
        amount_ = null;
        if (amountBuilder_ != null) {
          amountBuilder_.dispose();
          amountBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.meshtrade.type.v1.Amount amount = 6 [json_name = "amount"];</code>
       */
      public co.meshtrade.api.type.v1.AmountOuterClass.Amount.Builder getAmountBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getAmountFieldBuilder().getBuilder();
      }
      /**
       * <code>.meshtrade.type.v1.Amount amount = 6 [json_name = "amount"];</code>
       */
      public co.meshtrade.api.type.v1.AmountOuterClass.AmountOrBuilder getAmountOrBuilder() {
        if (amountBuilder_ != null) {
          return amountBuilder_.getMessageOrBuilder();
        } else {
          return amount_ == null ?
              co.meshtrade.api.type.v1.AmountOuterClass.Amount.getDefaultInstance() : amount_;
        }
      }
      /**
       * <code>.meshtrade.type.v1.Amount amount = 6 [json_name = "amount"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          co.meshtrade.api.type.v1.AmountOuterClass.Amount, co.meshtrade.api.type.v1.AmountOuterClass.Amount.Builder, co.meshtrade.api.type.v1.AmountOuterClass.AmountOrBuilder> 
          getAmountFieldBuilder() {
        if (amountBuilder_ == null) {
          amountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              co.meshtrade.api.type.v1.AmountOuterClass.Amount, co.meshtrade.api.type.v1.AmountOuterClass.Amount.Builder, co.meshtrade.api.type.v1.AmountOuterClass.AmountOrBuilder>(
                  getAmount(),
                  getParentForChildren(),
                  isClean());
          amount_ = null;
        }
        return amountBuilder_;
      }

      private co.meshtrade.api.type.v1.AmountOuterClass.Amount reportedCurrencyValue_;
      private com.google.protobuf.SingleFieldBuilderV3<
          co.meshtrade.api.type.v1.AmountOuterClass.Amount, co.meshtrade.api.type.v1.AmountOuterClass.Amount.Builder, co.meshtrade.api.type.v1.AmountOuterClass.AmountOrBuilder> reportedCurrencyValueBuilder_;
      /**
       * <code>.meshtrade.type.v1.Amount reported_currency_value = 7 [json_name = "reportedCurrencyValue"];</code>
       * @return Whether the reportedCurrencyValue field is set.
       */
      public boolean hasReportedCurrencyValue() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>.meshtrade.type.v1.Amount reported_currency_value = 7 [json_name = "reportedCurrencyValue"];</code>
       * @return The reportedCurrencyValue.
       */
      public co.meshtrade.api.type.v1.AmountOuterClass.Amount getReportedCurrencyValue() {
        if (reportedCurrencyValueBuilder_ == null) {
          return reportedCurrencyValue_ == null ? co.meshtrade.api.type.v1.AmountOuterClass.Amount.getDefaultInstance() : reportedCurrencyValue_;
        } else {
          return reportedCurrencyValueBuilder_.getMessage();
        }
      }
      /**
       * <code>.meshtrade.type.v1.Amount reported_currency_value = 7 [json_name = "reportedCurrencyValue"];</code>
       */
      public Builder setReportedCurrencyValue(co.meshtrade.api.type.v1.AmountOuterClass.Amount value) {
        if (reportedCurrencyValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          reportedCurrencyValue_ = value;
        } else {
          reportedCurrencyValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.meshtrade.type.v1.Amount reported_currency_value = 7 [json_name = "reportedCurrencyValue"];</code>
       */
      public Builder setReportedCurrencyValue(
          co.meshtrade.api.type.v1.AmountOuterClass.Amount.Builder builderForValue) {
        if (reportedCurrencyValueBuilder_ == null) {
          reportedCurrencyValue_ = builderForValue.build();
        } else {
          reportedCurrencyValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.meshtrade.type.v1.Amount reported_currency_value = 7 [json_name = "reportedCurrencyValue"];</code>
       */
      public Builder mergeReportedCurrencyValue(co.meshtrade.api.type.v1.AmountOuterClass.Amount value) {
        if (reportedCurrencyValueBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0) &&
            reportedCurrencyValue_ != null &&
            reportedCurrencyValue_ != co.meshtrade.api.type.v1.AmountOuterClass.Amount.getDefaultInstance()) {
            getReportedCurrencyValueBuilder().mergeFrom(value);
          } else {
            reportedCurrencyValue_ = value;
          }
        } else {
          reportedCurrencyValueBuilder_.mergeFrom(value);
        }
        if (reportedCurrencyValue_ != null) {
          bitField0_ |= 0x00000040;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.meshtrade.type.v1.Amount reported_currency_value = 7 [json_name = "reportedCurrencyValue"];</code>
       */
      public Builder clearReportedCurrencyValue() {
        bitField0_ = (bitField0_ & ~0x00000040);
        reportedCurrencyValue_ = null;
        if (reportedCurrencyValueBuilder_ != null) {
          reportedCurrencyValueBuilder_.dispose();
          reportedCurrencyValueBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.meshtrade.type.v1.Amount reported_currency_value = 7 [json_name = "reportedCurrencyValue"];</code>
       */
      public co.meshtrade.api.type.v1.AmountOuterClass.Amount.Builder getReportedCurrencyValueBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getReportedCurrencyValueFieldBuilder().getBuilder();
      }
      /**
       * <code>.meshtrade.type.v1.Amount reported_currency_value = 7 [json_name = "reportedCurrencyValue"];</code>
       */
      public co.meshtrade.api.type.v1.AmountOuterClass.AmountOrBuilder getReportedCurrencyValueOrBuilder() {
        if (reportedCurrencyValueBuilder_ != null) {
          return reportedCurrencyValueBuilder_.getMessageOrBuilder();
        } else {
          return reportedCurrencyValue_ == null ?
              co.meshtrade.api.type.v1.AmountOuterClass.Amount.getDefaultInstance() : reportedCurrencyValue_;
        }
      }
      /**
       * <code>.meshtrade.type.v1.Amount reported_currency_value = 7 [json_name = "reportedCurrencyValue"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          co.meshtrade.api.type.v1.AmountOuterClass.Amount, co.meshtrade.api.type.v1.AmountOuterClass.Amount.Builder, co.meshtrade.api.type.v1.AmountOuterClass.AmountOrBuilder> 
          getReportedCurrencyValueFieldBuilder() {
        if (reportedCurrencyValueBuilder_ == null) {
          reportedCurrencyValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              co.meshtrade.api.type.v1.AmountOuterClass.Amount, co.meshtrade.api.type.v1.AmountOuterClass.Amount.Builder, co.meshtrade.api.type.v1.AmountOuterClass.AmountOrBuilder>(
                  getReportedCurrencyValue(),
                  getParentForChildren(),
                  isClean());
          reportedCurrencyValue_ = null;
        }
        return reportedCurrencyValueBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:meshtrade.reporting.income_report.v1.Entry)
    }

    // @@protoc_insertion_point(class_scope:meshtrade.reporting.income_report.v1.Entry)
    private static final meshtrade.reporting.income_report.v1.EntryOuterClass.Entry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new meshtrade.reporting.income_report.v1.EntryOuterClass.Entry();
    }

    public static meshtrade.reporting.income_report.v1.EntryOuterClass.Entry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Entry>
        PARSER = new com.google.protobuf.AbstractParser<Entry>() {
      @java.lang.Override
      public Entry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Entry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Entry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public meshtrade.reporting.income_report.v1.EntryOuterClass.Entry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meshtrade_reporting_income_report_v1_Entry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meshtrade_reporting_income_report_v1_Entry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0meshtrade/reporting/income_report/v1/e" +
      "ntry.proto\022$meshtrade.reporting.income_r" +
      "eport.v1\032\035meshtrade/type/v1/token.proto\032" +
      "\036meshtrade/type/v1/amount.proto\032\037google/" +
      "protobuf/timestamp.proto\"\314\002\n\005Entry\022\035\n\nas" +
      "set_name\030\001 \001(\tR\tassetName\022.\n\005token\030\002 \001(\013" +
      "2\030.meshtrade.type.v1.TokenR\005token\022.\n\004dat" +
      "e\030\003 \001(\0132\032.google.protobuf.TimestampR\004dat" +
      "e\022 \n\013description\030\004 \001(\tR\013description\022\034\n\tn" +
      "arrative\030\005 \001(\tR\tnarrative\0221\n\006amount\030\006 \001(" +
      "\0132\031.meshtrade.type.v1.AmountR\006amount\022Q\n\027" +
      "reported_currency_value\030\007 \001(\0132\031.meshtrad" +
      "e.type.v1.AmountR\025reportedCurrencyValueB" +
      "HZFgithub.com/meshtrade/api/go/reporting" +
      "/income_report/v1;income_reportv1b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          co.meshtrade.api.type.v1.TokenOuterClass.getDescriptor(),
          co.meshtrade.api.type.v1.AmountOuterClass.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_meshtrade_reporting_income_report_v1_Entry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_meshtrade_reporting_income_report_v1_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meshtrade_reporting_income_report_v1_Entry_descriptor,
        new java.lang.String[] { "AssetName", "Token", "Date", "Description", "Narrative", "Amount", "ReportedCurrencyValue", });
    co.meshtrade.api.type.v1.TokenOuterClass.getDescriptor();
    co.meshtrade.api.type.v1.AmountOuterClass.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
