// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.28.0
// source: api/proto/search/textNINListCriterion.proto

package search

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TextNINListCriterion is a list of strings that a field should not be equal to.
type TextNINListCriterion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Field is the field that the search is performed against.
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// List is the list of string values that field CANNOT be equal to.
	// i.e. looking for entities where the value in Field is not in this List.
	List []string `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *TextNINListCriterion) Reset() {
	*x = TextNINListCriterion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_search_textNINListCriterion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextNINListCriterion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextNINListCriterion) ProtoMessage() {}

func (x *TextNINListCriterion) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_textNINListCriterion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextNINListCriterion.ProtoReflect.Descriptor instead.
func (*TextNINListCriterion) Descriptor() ([]byte, []int) {
	return file_api_proto_search_textNINListCriterion_proto_rawDescGZIP(), []int{0}
}

func (x *TextNINListCriterion) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *TextNINListCriterion) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

var File_api_proto_search_textNINListCriterion_proto protoreflect.FileDescriptor

var file_api_proto_search_textNINListCriterion_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x2f, 0x74, 0x65, 0x78, 0x74, 0x4e, 0x49, 0x4e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x72,
	0x69, 0x74, 0x65, 0x72, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x22, 0x40, 0x0a, 0x14, 0x54, 0x65, 0x78,
	0x74, 0x4e, 0x49, 0x4e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x24, 0x5a, 0x22, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x72,
	0x61, 0x64, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_search_textNINListCriterion_proto_rawDescOnce sync.Once
	file_api_proto_search_textNINListCriterion_proto_rawDescData = file_api_proto_search_textNINListCriterion_proto_rawDesc
)

func file_api_proto_search_textNINListCriterion_proto_rawDescGZIP() []byte {
	file_api_proto_search_textNINListCriterion_proto_rawDescOnce.Do(func() {
		file_api_proto_search_textNINListCriterion_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_search_textNINListCriterion_proto_rawDescData)
	})
	return file_api_proto_search_textNINListCriterion_proto_rawDescData
}

var file_api_proto_search_textNINListCriterion_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_search_textNINListCriterion_proto_goTypes = []interface{}{
	(*TextNINListCriterion)(nil), // 0: api.search.TextNINListCriterion
}
var file_api_proto_search_textNINListCriterion_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_search_textNINListCriterion_proto_init() }
func file_api_proto_search_textNINListCriterion_proto_init() {
	if File_api_proto_search_textNINListCriterion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_search_textNINListCriterion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextNINListCriterion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_search_textNINListCriterion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_search_textNINListCriterion_proto_goTypes,
		DependencyIndexes: file_api_proto_search_textNINListCriterion_proto_depIdxs,
		MessageInfos:      file_api_proto_search_textNINListCriterion_proto_msgTypes,
	}.Build()
	File_api_proto_search_textNINListCriterion_proto = out.File
	file_api_proto_search_textNINListCriterion_proto_rawDesc = nil
	file_api_proto_search_textNINListCriterion_proto_goTypes = nil
	file_api_proto_search_textNINListCriterion_proto_depIdxs = nil
}
