// Code generated by protoc-gen-meshgo. DO NOT EDIT.
// source: meshtrade/ledger/transaction/v1/service.proto
package transaction_v1

import (
	context "context"
)

// TransactionService manages Transaction lifecycle.
type TransactionService interface {
	// Retrieves a single Transaction state by the unique identifier of the transaction
	GetTransactionState(ctx context.Context, request *GetTransactionStateRequest) (*GetTransactionStateResponse, error)
}

const TransactionServiceServiceProviderName = "meshtrade-ledger-transaction-v1-TransactionService"
