# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/proto/instrument/fee/data.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'api/proto/instrument/fee/data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.python.lib.instrument.fee import dataAmount_pb2 as api_dot_proto_dot_instrument_dot_fee_dot_dataAmount__pb2
from api.python.lib.instrument.fee import dataRate_pb2 as api_dot_proto_dot_instrument_dot_fee_dot_dataRate__pb2
from api.python.lib.instrument.fee import dataPerUnit_pb2 as api_dot_proto_dot_instrument_dot_fee_dot_dataPerUnit__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#api/proto/instrument/fee/data.proto\x12\x12\x61pi.instrument.fee\x1a)api/proto/instrument/fee/dataAmount.proto\x1a\'api/proto/instrument/fee/dataRate.proto\x1a*api/proto/instrument/fee/dataPerUnit.proto\"\xae\x01\n\x04\x44\x61ta\x12\x34\n\namountData\x18\x01 \x01(\x0b\x32\x1e.api.instrument.fee.AmountDataH\x00\x12\x30\n\x08rateData\x18\x02 \x01(\x0b\x32\x1c.api.instrument.fee.RateDataH\x00\x12\x36\n\x0bperUnitData\x18\x03 \x01(\x0b\x32\x1f.api.instrument.fee.PerUnitDataH\x00\x42\x06\n\x04\x44\x61taB,Z*github.com/meshtrade/api/go/instrument/feeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.python.lib.instrument.fee.data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/meshtrade/api/go/instrument/fee'
  _globals['_DATA']._serialized_start=188
  _globals['_DATA']._serialized_end=362
# @@protoc_insertion_point(module_scope)
