// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: meshtrade/iam/api_user/v1/api_credentials.proto

package api_userv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents API credentials used for authentication with the Mesh API.
//
// API credentials consist of an API key for authentication and a group
// identifier that specifies the organizational context for API operations.
// The group field must be in the format groups/{group_id} where group_id
// is the unique identifier of the owning group.
type APICredentials struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The API key used for Bearer token authentication.
	// This should be kept secure and never exposed in logs or version control.
	// Required field.
	ApiKey string `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// The group resource name in the format groups/{group_id}.
	// This identifies the organizational context for API operations and
	// is used for authorization and resource scoping.
	// Required field with strict format validation.
	Group         string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APICredentials) Reset() {
	*x = APICredentials{}
	mi := &file_meshtrade_iam_api_user_v1_api_credentials_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APICredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APICredentials) ProtoMessage() {}

func (x *APICredentials) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_api_user_v1_api_credentials_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APICredentials.ProtoReflect.Descriptor instead.
func (*APICredentials) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_api_user_v1_api_credentials_proto_rawDescGZIP(), []int{0}
}

func (x *APICredentials) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *APICredentials) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

var File_meshtrade_iam_api_user_v1_api_credentials_proto protoreflect.FileDescriptor

const file_meshtrade_iam_api_user_v1_api_credentials_proto_rawDesc = "" +
	"\n" +
	"/meshtrade/iam/api_user/v1/api_credentials.proto\x12\x19meshtrade.iam.api_user.v1\x1a\x1bbuf/validate/validate.proto\"\x81\x05\n" +
	"\x0eAPICredentials\x12\xbd\x02\n" +
	"\aapi_key\x18\x01 \x01(\tB\xa3\x02\xbaH\x9f\x02\xba\x01u\n" +
	"\x10api_key.required\x12Oapi_key is required and must be exactly 43 characters (base64 URL-safe encoded)\x1a\x10size(this) == 43\xba\x01\x89\x01\n" +
	"\x0eapi_key.format\x12Rapi_key must be base64 URL-safe encoded (43 characters, alphanumeric plus _ and -)\x1a#this.matches('^[A-Za-z0-9_-]{43}$')r\x182\x13^[A-Za-z0-9_-]{43}$\x98\x01+R\x06apiKey\x12\xae\x02\n" +
	"\x05group\x18\x02 \x01(\tB\x97\x02\xbaH\x93\x02\xba\x01Y\n" +
	"\x0egroup.required\x125group is required and must be in format groups/{ulid}\x1a\x10size(this) == 33\xba\x01\x97\x01\n" +
	"\fgroup.format\x12`group must be in format groups/{ulid} where ulid is a 26-character ULID (uppercase alphanumeric)\x1a%this.matches('^groups/[0-9A-Z]{26}$')r\x1a2\x15^groups/[0-9A-Z]{26}$\x98\x01!R\x05groupB8Z6github.com/meshtrade/api/go/iam/api_user/v1;api_userv1b\x06proto3"

var (
	file_meshtrade_iam_api_user_v1_api_credentials_proto_rawDescOnce sync.Once
	file_meshtrade_iam_api_user_v1_api_credentials_proto_rawDescData []byte
)

func file_meshtrade_iam_api_user_v1_api_credentials_proto_rawDescGZIP() []byte {
	file_meshtrade_iam_api_user_v1_api_credentials_proto_rawDescOnce.Do(func() {
		file_meshtrade_iam_api_user_v1_api_credentials_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshtrade_iam_api_user_v1_api_credentials_proto_rawDesc), len(file_meshtrade_iam_api_user_v1_api_credentials_proto_rawDesc)))
	})
	return file_meshtrade_iam_api_user_v1_api_credentials_proto_rawDescData
}

var file_meshtrade_iam_api_user_v1_api_credentials_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meshtrade_iam_api_user_v1_api_credentials_proto_goTypes = []any{
	(*APICredentials)(nil), // 0: meshtrade.iam.api_user.v1.APICredentials
}
var file_meshtrade_iam_api_user_v1_api_credentials_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meshtrade_iam_api_user_v1_api_credentials_proto_init() }
func file_meshtrade_iam_api_user_v1_api_credentials_proto_init() {
	if File_meshtrade_iam_api_user_v1_api_credentials_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshtrade_iam_api_user_v1_api_credentials_proto_rawDesc), len(file_meshtrade_iam_api_user_v1_api_credentials_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshtrade_iam_api_user_v1_api_credentials_proto_goTypes,
		DependencyIndexes: file_meshtrade_iam_api_user_v1_api_credentials_proto_depIdxs,
		MessageInfos:      file_meshtrade_iam_api_user_v1_api_credentials_proto_msgTypes,
	}.Build()
	File_meshtrade_iam_api_user_v1_api_credentials_proto = out.File
	file_meshtrade_iam_api_user_v1_api_credentials_proto_goTypes = nil
	file_meshtrade_iam_api_user_v1_api_credentials_proto_depIdxs = nil
}
