// Code generated by protoc-gen-meshgo. DO NOT EDIT.
// source: meshtrade/iam/api_user/v1/service.proto
package api_userv1

import (
	context "context"
)

// ApiUserService manages API user lifecycle and authentication credentials.
//
// API users represent automated clients that can authenticate with API keys
// and perform operations within a specific group context. Each API user has:
// - A unique identifier and display name
// - Group ownership for resource isolation
// - Role-based permissions for authorization
// - Active/inactive state for access control
//
// All operations require IAM domain permissions and operate within
// the authenticated group context.
type ApiUserService interface {
	// Retrieves a single API user by its unique identifier.
	//
	// Parameters:
	// - name: The resource name in format api_users/{api_user_id}
	//
	// Returns:
	// - APIUser: Complete API user resource including metadata and roles
	//
	// Authorization: Requires ROLE_IAM_ADMIN or ROLE_IAM_VIEWER
	GetApiUser(ctx context.Context, request *GetApiUserRequest) (*APIUser, error)

	// Creates a new API user with the specified configuration.
	//
	// The API user will be created in the authenticated group context
	// and assigned the provided roles. The system generates a unique
	// identifier and API key for authentication.
	//
	// Parameters:
	// - api_user: APIUser configuration (name field ignored, assigned by system)
	//
	// Returns:
	// - APIUser: Newly created API user with generated name and API key
	//
	// Authorization: Requires ROLE_IAM_ADMIN
	CreateApiUser(ctx context.Context, request *CreateApiUserRequest) (*APIUser, error)

	// Lists all API users in the authenticated group context.
	//
	// Returns all API users that belong to the current group,
	// regardless of their active/inactive state.
	//
	// Returns:
	// - ListApiUsersResponse: Collection of API users in the group
	//
	// Authorization: Requires ROLE_IAM_ADMIN or ROLE_IAM_VIEWER
	ListApiUsers(ctx context.Context, request *ListApiUsersRequest) (*ListApiUsersResponse, error)

	// Searches API users using display name filtering.
	//
	// Performs substring matching on API user display names
	// within the authenticated group context.
	//
	// Parameters:
	// - display_name: Substring to search for in display names
	//
	// Returns:
	// - SearchApiUsersResponse: Collection of matching API users
	//
	// Authorization: Requires ROLE_IAM_ADMIN or ROLE_IAM_VIEWER
	SearchApiUsers(ctx context.Context, request *SearchApiUsersRequest) (*SearchApiUsersResponse, error)

	// Activates an API user, enabling API key authentication.
	//
	// Changes the API user state to active, allowing the associated
	// API key to be used for authentication and authorization.
	//
	// Parameters:
	// - name: The resource name in format api_users/{api_user_id}
	//
	// Returns:
	// - APIUser: Updated API user with active state
	//
	// Authorization: Requires ROLE_IAM_ADMIN
	ActivateApiUser(ctx context.Context, request *ActivateApiUserRequest) (*APIUser, error)

	// Deactivates an API user, disabling API key authentication.
	//
	// Changes the API user state to inactive, preventing the associated
	// API key from being used for authentication.
	//
	// Parameters:
	// - name: The resource name in format api_users/{api_user_id}
	//
	// Returns:
	// - APIUser: Updated API user with inactive state
	//
	// Authorization: Requires ROLE_IAM_ADMIN
	DeactivateApiUser(ctx context.Context, request *DeactivateApiUserRequest) (*APIUser, error)

	// Retrieves an API user using its API key hash.
	//
	// This method is used for authentication flows to lookup
	// an API user based on the hash of their API key.
	//
	// Parameters:
	// - key_hash: Hash of the API key to lookup
	//
	// Returns:
	// - APIUser: Complete API user resource associated with the key
	//
	// Authorization: Requires ROLE_IAM_ADMIN or ROLE_IAM_VIEWER
	GetApiUserByKeyHash(ctx context.Context, request *GetApiUserByKeyHashRequest) (*APIUser, error)
}

const ApiUserServiceServiceProviderName = "meshtrade-iam-api_user-v1-ApiUserService"
