// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: meshtrade/iam/api_user/v1/service.proto

package api_user_v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/meshtrade/api/go/iam/role/v1"
	_ "github.com/meshtrade/api/go/option/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetApiUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the API user to retrieve.
	// Format: api_users/{ULIDv2}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiUserRequest) Reset() {
	*x = GetApiUserRequest{}
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiUserRequest) ProtoMessage() {}

func (x *GetApiUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiUserRequest.ProtoReflect.Descriptor instead.
func (*GetApiUserRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_api_user_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetApiUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetApiUserByKeyHashRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key hash of the API user to get.
	KeyHash       string `protobuf:"bytes,1,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiUserByKeyHashRequest) Reset() {
	*x = GetApiUserByKeyHashRequest{}
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiUserByKeyHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiUserByKeyHashRequest) ProtoMessage() {}

func (x *GetApiUserByKeyHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiUserByKeyHashRequest.ProtoReflect.Descriptor instead.
func (*GetApiUserByKeyHashRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_api_user_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetApiUserByKeyHashRequest) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

type CreateApiUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The API user resource to create.
	// The name field will be ignored and assigned by the server.
	ApiUser       *APIUser `protobuf:"bytes,1,opt,name=api_user,json=apiUser,proto3" json:"api_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApiUserRequest) Reset() {
	*x = CreateApiUserRequest{}
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiUserRequest) ProtoMessage() {}

func (x *CreateApiUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiUserRequest.ProtoReflect.Descriptor instead.
func (*CreateApiUserRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_api_user_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateApiUserRequest) GetApiUser() *APIUser {
	if x != nil {
		return x.ApiUser
	}
	return nil
}

type AssignRolesToAPIUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the API user to assign roles to in the format api_users/{ULIDv2}.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Roles to assign to the API user in the format groups/{ULIDv2}/roles/{role_id}.
	// The role_id corresponds to a value from the meshtrade.iam.role.v1.Role enum.
	Roles         []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRolesToAPIUserRequest) Reset() {
	*x = AssignRolesToAPIUserRequest{}
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRolesToAPIUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRolesToAPIUserRequest) ProtoMessage() {}

func (x *AssignRolesToAPIUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRolesToAPIUserRequest.ProtoReflect.Descriptor instead.
func (*AssignRolesToAPIUserRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_api_user_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *AssignRolesToAPIUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AssignRolesToAPIUserRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type RevokeRolesFromAPIUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the API user to revoke roles from in the format api_users/{ULIDv2}.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Roles to revoke from the API user in the format groups/{ULIDv2}/roles/{role_id}.
	// The role_id corresponds to a value from the meshtrade.iam.role.v1.Role enum.
	Roles         []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRolesFromAPIUserRequest) Reset() {
	*x = RevokeRolesFromAPIUserRequest{}
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRolesFromAPIUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRolesFromAPIUserRequest) ProtoMessage() {}

func (x *RevokeRolesFromAPIUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRolesFromAPIUserRequest.ProtoReflect.Descriptor instead.
func (*RevokeRolesFromAPIUserRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_api_user_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeRolesFromAPIUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RevokeRolesFromAPIUserRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ListApiUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApiUsersRequest) Reset() {
	*x = ListApiUsersRequest{}
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApiUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApiUsersRequest) ProtoMessage() {}

func (x *ListApiUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApiUsersRequest.ProtoReflect.Descriptor instead.
func (*ListApiUsersRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_api_user_v1_service_proto_rawDescGZIP(), []int{5}
}

type ListApiUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiUsers      []*APIUser             `protobuf:"bytes,1,rep,name=api_users,json=apiUsers,proto3" json:"api_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApiUsersResponse) Reset() {
	*x = ListApiUsersResponse{}
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApiUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApiUsersResponse) ProtoMessage() {}

func (x *ListApiUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApiUsersResponse.ProtoReflect.Descriptor instead.
func (*ListApiUsersResponse) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_api_user_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListApiUsersResponse) GetApiUsers() []*APIUser {
	if x != nil {
		return x.ApiUsers
	}
	return nil
}

type SearchApiUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Display name is a substring search for API users.
	DisplayName   string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchApiUsersRequest) Reset() {
	*x = SearchApiUsersRequest{}
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchApiUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchApiUsersRequest) ProtoMessage() {}

func (x *SearchApiUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchApiUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchApiUsersRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_api_user_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *SearchApiUsersRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type SearchApiUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiUsers      []*APIUser             `protobuf:"bytes,1,rep,name=api_users,json=apiUsers,proto3" json:"api_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchApiUsersResponse) Reset() {
	*x = SearchApiUsersResponse{}
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchApiUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchApiUsersResponse) ProtoMessage() {}

func (x *SearchApiUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchApiUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchApiUsersResponse) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_api_user_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *SearchApiUsersResponse) GetApiUsers() []*APIUser {
	if x != nil {
		return x.ApiUsers
	}
	return nil
}

type ActivateApiUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the API user to activate.
	// Format: api_users/{ULIDv2}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateApiUserRequest) Reset() {
	*x = ActivateApiUserRequest{}
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateApiUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateApiUserRequest) ProtoMessage() {}

func (x *ActivateApiUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateApiUserRequest.ProtoReflect.Descriptor instead.
func (*ActivateApiUserRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_api_user_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *ActivateApiUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeactivateApiUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the API user to deactivate.
	// Format: api_users/{ULIDv2}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateApiUserRequest) Reset() {
	*x = DeactivateApiUserRequest{}
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateApiUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateApiUserRequest) ProtoMessage() {}

func (x *DeactivateApiUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_api_user_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateApiUserRequest.ProtoReflect.Descriptor instead.
func (*DeactivateApiUserRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_api_user_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeactivateApiUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_meshtrade_iam_api_user_v1_service_proto protoreflect.FileDescriptor

const file_meshtrade_iam_api_user_v1_service_proto_rawDesc = "" +
	"\n" +
	"'meshtrade/iam/api_user/v1/service.proto\x12\x19meshtrade.iam.api_user.v1\x1a\x1bbuf/validate/validate.proto\x1a(meshtrade/iam/api_user/v1/api_user.proto\x1a meshtrade/iam/role/v1/role.proto\x1a%meshtrade/option/v1/method_type.proto\"h\n" +
	"\x11GetApiUserRequest\x12S\n" +
	"\x04name\x18\x01 \x01(\tB?\xbaH<\xc8\x01\x01r722^api_users/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$\x98\x01$R\x04name\"Z\n" +
	"\x1aGetApiUserByKeyHashRequest\x12<\n" +
	"\bkey_hash\x18\x01 \x01(\tB!\xbaH\x1e\xc8\x01\x01r\x192\x14^[A-Za-z0-9+/]{43}=$\x98\x01,R\akeyHash\"]\n" +
	"\x14CreateApiUserRequest\x12E\n" +
	"\bapi_user\x18\x01 \x01(\v2\".meshtrade.iam.api_user.v1.APIUserB\x06\xbaH\x03\xc8\x01\x01R\aapiUser\"\xe2\x01\n" +
	"\x1bAssignRolesToAPIUserRequest\x12S\n" +
	"\x04name\x18\x01 \x01(\tB?\xbaH<\xc8\x01\x01r722^api_users/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$\x98\x01$R\x04name\x12n\n" +
	"\x05roles\x18\x02 \x03(\tBX\xbaHU\xc8\x01\x01\x92\x01O\"MrK\x10/\x1802E^groups/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}/roles/[1-9][0-9]{6,7}$R\x05roles\"\xe4\x01\n" +
	"\x1dRevokeRolesFromAPIUserRequest\x12S\n" +
	"\x04name\x18\x01 \x01(\tB?\xbaH<\xc8\x01\x01r722^api_users/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$\x98\x01$R\x04name\x12n\n" +
	"\x05roles\x18\x02 \x03(\tBX\xbaHU\xc8\x01\x01\x92\x01O\"MrK\x10/\x1802E^groups/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}/roles/[1-9][0-9]{6,7}$R\x05roles\"\x15\n" +
	"\x13ListApiUsersRequest\"W\n" +
	"\x14ListApiUsersResponse\x12?\n" +
	"\tapi_users\x18\x01 \x03(\v2\".meshtrade.iam.api_user.v1.APIUserR\bapiUsers\":\n" +
	"\x15SearchApiUsersRequest\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\"Y\n" +
	"\x16SearchApiUsersResponse\x12?\n" +
	"\tapi_users\x18\x01 \x03(\v2\".meshtrade.iam.api_user.v1.APIUserR\bapiUsers\"m\n" +
	"\x16ActivateApiUserRequest\x12S\n" +
	"\x04name\x18\x01 \x01(\tB?\xbaH<\xc8\x01\x01r722^api_users/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$\x98\x01$R\x04name\"o\n" +
	"\x18DeactivateApiUserRequest\x12S\n" +
	"\x04name\x18\x01 \x01(\tB?\xbaH<\xc8\x01\x01r722^api_users/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$\x98\x01$R\x04name2\xce\t\n" +
	"\x0eApiUserService\x12z\n" +
	"\n" +
	"GetApiUser\x12,.meshtrade.iam.api_user.v1.GetApiUserRequest\x1a\".meshtrade.iam.api_user.v1.APIUser\"\x1a\xa0\xb5\x18\x01\xaa\xb5\x18\x12\n" +
	"\x10\xc0\x8d\xb7\x01\xc1\x8d\xb7\x01\u008d\xb7\x01Í\xb7\x01\x12x\n" +
	"\rCreateApiUser\x12/.meshtrade.iam.api_user.v1.CreateApiUserRequest\x1a\".meshtrade.iam.api_user.v1.APIUser\"\x12\xa0\xb5\x18\x02\xaa\xb5\x18\n" +
	"\n" +
	"\b\xc0\x8d\xb7\x01\u008d\xb7\x01\x12\x86\x01\n" +
	"\x14AssignRolesToAPIUser\x126.meshtrade.iam.api_user.v1.AssignRolesToAPIUserRequest\x1a\".meshtrade.iam.api_user.v1.APIUser\"\x12\xa0\xb5\x18\x02\xaa\xb5\x18\n" +
	"\n" +
	"\b\xc0\x8d\xb7\x01\u008d\xb7\x01\x12\x8a\x01\n" +
	"\x16RevokeRolesFromAPIUser\x128.meshtrade.iam.api_user.v1.RevokeRolesFromAPIUserRequest\x1a\".meshtrade.iam.api_user.v1.APIUser\"\x12\xa0\xb5\x18\x02\xaa\xb5\x18\n" +
	"\n" +
	"\b\xc0\x8d\xb7\x01\u008d\xb7\x01\x12\x8b\x01\n" +
	"\fListApiUsers\x12..meshtrade.iam.api_user.v1.ListApiUsersRequest\x1a/.meshtrade.iam.api_user.v1.ListApiUsersResponse\"\x1a\xa0\xb5\x18\x01\xaa\xb5\x18\x12\n" +
	"\x10\xc0\x8d\xb7\x01\xc1\x8d\xb7\x01\u008d\xb7\x01Í\xb7\x01\x12\x91\x01\n" +
	"\x0eSearchApiUsers\x120.meshtrade.iam.api_user.v1.SearchApiUsersRequest\x1a1.meshtrade.iam.api_user.v1.SearchApiUsersResponse\"\x1a\xa0\xb5\x18\x01\xaa\xb5\x18\x12\n" +
	"\x10\xc0\x8d\xb7\x01\xc1\x8d\xb7\x01\u008d\xb7\x01Í\xb7\x01\x12|\n" +
	"\x0fActivateApiUser\x121.meshtrade.iam.api_user.v1.ActivateApiUserRequest\x1a\".meshtrade.iam.api_user.v1.APIUser\"\x12\xa0\xb5\x18\x02\xaa\xb5\x18\n" +
	"\n" +
	"\b\xc0\x8d\xb7\x01\u008d\xb7\x01\x12\x80\x01\n" +
	"\x11DeactivateApiUser\x123.meshtrade.iam.api_user.v1.DeactivateApiUserRequest\x1a\".meshtrade.iam.api_user.v1.APIUser\"\x12\xa0\xb5\x18\x02\xaa\xb5\x18\n" +
	"\n" +
	"\b\xc0\x8d\xb7\x01\u008d\xb7\x01\x12\x8c\x01\n" +
	"\x13GetApiUserByKeyHash\x125.meshtrade.iam.api_user.v1.GetApiUserByKeyHashRequest\x1a\".meshtrade.iam.api_user.v1.APIUser\"\x1a\xa0\xb5\x18\x01\xaa\xb5\x18\x12\n" +
	"\x10\xc0\x8d\xb7\x01\xc1\x8d\xb7\x01\u008d\xb7\x01Í\xb7\x01B[\n" +
	" co.meshtrade.api.iam.api_user.v1Z7github.com/meshtrade/api/go/iam/api_user/v1;api_user_v1b\x06proto3"

var (
	file_meshtrade_iam_api_user_v1_service_proto_rawDescOnce sync.Once
	file_meshtrade_iam_api_user_v1_service_proto_rawDescData []byte
)

func file_meshtrade_iam_api_user_v1_service_proto_rawDescGZIP() []byte {
	file_meshtrade_iam_api_user_v1_service_proto_rawDescOnce.Do(func() {
		file_meshtrade_iam_api_user_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshtrade_iam_api_user_v1_service_proto_rawDesc), len(file_meshtrade_iam_api_user_v1_service_proto_rawDesc)))
	})
	return file_meshtrade_iam_api_user_v1_service_proto_rawDescData
}

var file_meshtrade_iam_api_user_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_meshtrade_iam_api_user_v1_service_proto_goTypes = []any{
	(*GetApiUserRequest)(nil),             // 0: meshtrade.iam.api_user.v1.GetApiUserRequest
	(*GetApiUserByKeyHashRequest)(nil),    // 1: meshtrade.iam.api_user.v1.GetApiUserByKeyHashRequest
	(*CreateApiUserRequest)(nil),          // 2: meshtrade.iam.api_user.v1.CreateApiUserRequest
	(*AssignRolesToAPIUserRequest)(nil),   // 3: meshtrade.iam.api_user.v1.AssignRolesToAPIUserRequest
	(*RevokeRolesFromAPIUserRequest)(nil), // 4: meshtrade.iam.api_user.v1.RevokeRolesFromAPIUserRequest
	(*ListApiUsersRequest)(nil),           // 5: meshtrade.iam.api_user.v1.ListApiUsersRequest
	(*ListApiUsersResponse)(nil),          // 6: meshtrade.iam.api_user.v1.ListApiUsersResponse
	(*SearchApiUsersRequest)(nil),         // 7: meshtrade.iam.api_user.v1.SearchApiUsersRequest
	(*SearchApiUsersResponse)(nil),        // 8: meshtrade.iam.api_user.v1.SearchApiUsersResponse
	(*ActivateApiUserRequest)(nil),        // 9: meshtrade.iam.api_user.v1.ActivateApiUserRequest
	(*DeactivateApiUserRequest)(nil),      // 10: meshtrade.iam.api_user.v1.DeactivateApiUserRequest
	(*APIUser)(nil),                       // 11: meshtrade.iam.api_user.v1.APIUser
}
var file_meshtrade_iam_api_user_v1_service_proto_depIdxs = []int32{
	11, // 0: meshtrade.iam.api_user.v1.CreateApiUserRequest.api_user:type_name -> meshtrade.iam.api_user.v1.APIUser
	11, // 1: meshtrade.iam.api_user.v1.ListApiUsersResponse.api_users:type_name -> meshtrade.iam.api_user.v1.APIUser
	11, // 2: meshtrade.iam.api_user.v1.SearchApiUsersResponse.api_users:type_name -> meshtrade.iam.api_user.v1.APIUser
	0,  // 3: meshtrade.iam.api_user.v1.ApiUserService.GetApiUser:input_type -> meshtrade.iam.api_user.v1.GetApiUserRequest
	2,  // 4: meshtrade.iam.api_user.v1.ApiUserService.CreateApiUser:input_type -> meshtrade.iam.api_user.v1.CreateApiUserRequest
	3,  // 5: meshtrade.iam.api_user.v1.ApiUserService.AssignRolesToAPIUser:input_type -> meshtrade.iam.api_user.v1.AssignRolesToAPIUserRequest
	4,  // 6: meshtrade.iam.api_user.v1.ApiUserService.RevokeRolesFromAPIUser:input_type -> meshtrade.iam.api_user.v1.RevokeRolesFromAPIUserRequest
	5,  // 7: meshtrade.iam.api_user.v1.ApiUserService.ListApiUsers:input_type -> meshtrade.iam.api_user.v1.ListApiUsersRequest
	7,  // 8: meshtrade.iam.api_user.v1.ApiUserService.SearchApiUsers:input_type -> meshtrade.iam.api_user.v1.SearchApiUsersRequest
	9,  // 9: meshtrade.iam.api_user.v1.ApiUserService.ActivateApiUser:input_type -> meshtrade.iam.api_user.v1.ActivateApiUserRequest
	10, // 10: meshtrade.iam.api_user.v1.ApiUserService.DeactivateApiUser:input_type -> meshtrade.iam.api_user.v1.DeactivateApiUserRequest
	1,  // 11: meshtrade.iam.api_user.v1.ApiUserService.GetApiUserByKeyHash:input_type -> meshtrade.iam.api_user.v1.GetApiUserByKeyHashRequest
	11, // 12: meshtrade.iam.api_user.v1.ApiUserService.GetApiUser:output_type -> meshtrade.iam.api_user.v1.APIUser
	11, // 13: meshtrade.iam.api_user.v1.ApiUserService.CreateApiUser:output_type -> meshtrade.iam.api_user.v1.APIUser
	11, // 14: meshtrade.iam.api_user.v1.ApiUserService.AssignRolesToAPIUser:output_type -> meshtrade.iam.api_user.v1.APIUser
	11, // 15: meshtrade.iam.api_user.v1.ApiUserService.RevokeRolesFromAPIUser:output_type -> meshtrade.iam.api_user.v1.APIUser
	6,  // 16: meshtrade.iam.api_user.v1.ApiUserService.ListApiUsers:output_type -> meshtrade.iam.api_user.v1.ListApiUsersResponse
	8,  // 17: meshtrade.iam.api_user.v1.ApiUserService.SearchApiUsers:output_type -> meshtrade.iam.api_user.v1.SearchApiUsersResponse
	11, // 18: meshtrade.iam.api_user.v1.ApiUserService.ActivateApiUser:output_type -> meshtrade.iam.api_user.v1.APIUser
	11, // 19: meshtrade.iam.api_user.v1.ApiUserService.DeactivateApiUser:output_type -> meshtrade.iam.api_user.v1.APIUser
	11, // 20: meshtrade.iam.api_user.v1.ApiUserService.GetApiUserByKeyHash:output_type -> meshtrade.iam.api_user.v1.APIUser
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_meshtrade_iam_api_user_v1_service_proto_init() }
func file_meshtrade_iam_api_user_v1_service_proto_init() {
	if File_meshtrade_iam_api_user_v1_service_proto != nil {
		return
	}
	file_meshtrade_iam_api_user_v1_api_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshtrade_iam_api_user_v1_service_proto_rawDesc), len(file_meshtrade_iam_api_user_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meshtrade_iam_api_user_v1_service_proto_goTypes,
		DependencyIndexes: file_meshtrade_iam_api_user_v1_service_proto_depIdxs,
		MessageInfos:      file_meshtrade_iam_api_user_v1_service_proto_msgTypes,
	}.Build()
	File_meshtrade_iam_api_user_v1_service_proto = out.File
	file_meshtrade_iam_api_user_v1_service_proto_goTypes = nil
	file_meshtrade_iam_api_user_v1_service_proto_depIdxs = nil
}
