// @generated by protoc-gen-meshts v1
// @generated from file meshtrade/trading/market_order/v1/service.proto (package meshtrade.trading.market_order.v1, syntax proto3)
/* eslint-disable */

import { createClient, type Client as ConnectClient, Interceptor } from "@connectrpc/connect";
import { createGrpcWebTransport } from "@connectrpc/connect-web";
import { MarketOrderService } from "./service_pb";
import {
  GetMarketOrderRequest
} from "./service_pb";
import { MarketOrder } from "./market_order_pb";
import { ConfigOpts, getConfigFromOpts } from "../../../common/config";
import { validateRequest } from "../../../common/validation";
import { createGroupInterceptor } from "../../../common/connectInterceptors";

/**
 * Web client for interacting with the meshtrade.trading.market_order.v1 market order v1 API resource service.
 * Uses Connect-ES with gRPC-Web transport for browser-compatible gRPC communication.
 */
export class MarketOrderServiceWeb {
  private _client: ConnectClient<typeof MarketOrderService>;
  private readonly _config: ReturnType<typeof getConfigFromOpts>;
  private readonly _interceptors: Interceptor[];

  /**
   * Constructs an instance of MarketOrderServiceWeb.
   * @param {ConfigOpts} [config] - Optional configuration for the client.
   * @param {Interceptor[]} [interceptors] - For internal use by `withGroup`.
   */
  constructor(config?: ConfigOpts, interceptors?: Interceptor[]) {
    this._config = getConfigFromOpts(config);
    this._interceptors = interceptors || [];

    // Create the gRPC-Web transport with interceptors
    const transport = createGrpcWebTransport({
      baseUrl: this._config.apiServerURL,
      interceptors: this._interceptors,
      // Enable credentials (cookies) for cross-origin requests
      fetch: (input, init) => globalThis.fetch(input, { ...init, credentials: 'include' }),
    });

    // Construct the Connect-ES client
    this._client = createClient(MarketOrderService, transport);
  }

  /**
   * Returns a new client instance configured to send the specified group
   * resource name in the request headers for subsequent API calls.
   * 
   * @param {string} group - The operating group context to inject into the request
   *                         in the format `groups/{ulid}` where {ulid} is a 26-character ULID.
   *                         Example: 'groups/01ARZ3NDEKTSV4YWVF8F5BH32'
   * @returns {MarketOrderServiceWeb} A new, configured instance of the client.
   * @throws {Error} If the group format is invalid (validation occurs in createGroupInterceptor)
   */
  withGroup(group: string): MarketOrderServiceWeb {
    // Check if a group interceptor already exists.
    // Group interceptors are identified by having a 'groupContext' property
    const hasGroupInterceptor = this._interceptors.some(
      (interceptor: any) => interceptor.groupContext !== undefined
    );

    if (hasGroupInterceptor) {
      throw new Error(
        "Attempted to set group context twice. A group has already been set for this client instance."
      );
    }

    // Create a new interceptor for the group context
    const groupInterceptor = createGroupInterceptor(group);

    // Return a new client instance with the existing interceptors plus the new one
    return new MarketOrderServiceWeb(
      this._config,
      [
        ...this._interceptors,
        groupInterceptor,
      ],
    );
  }

  /**
   * Retrieves a market order.
   * @param {GetMarketOrderRequest} request - The request object for getmarketorder.
   * @returns {Promise<MarketOrder>} A promise that resolves with the market order.
   */
  getMarketOrder(request: GetMarketOrderRequest): Promise<MarketOrder> {
    // Validate request
    validateRequest(request);

    return this._client.getMarketOrder(request);
  }

}
