// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: meshtrade/wallet/account/v1/account.proto

package accountv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_meshtrade_wallet_account_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_wallet_account_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_meshtrade_wallet_account_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_meshtrade_wallet_account_v1_account_proto protoreflect.FileDescriptor

const file_meshtrade_wallet_account_v1_account_proto_rawDesc = "" +
	"\n" +
	")meshtrade/wallet/account/v1/account.proto\x12\x1bmeshtrade.wallet.account.v1\"\x1d\n" +
	"\aAccount\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04nameB]\n" +
	"\"co.meshtrade.api.wallet.account.v1Z7github.com/meshtrade/api/go/wallet/account/v1;accountv1b\x06proto3"

var (
	file_meshtrade_wallet_account_v1_account_proto_rawDescOnce sync.Once
	file_meshtrade_wallet_account_v1_account_proto_rawDescData []byte
)

func file_meshtrade_wallet_account_v1_account_proto_rawDescGZIP() []byte {
	file_meshtrade_wallet_account_v1_account_proto_rawDescOnce.Do(func() {
		file_meshtrade_wallet_account_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshtrade_wallet_account_v1_account_proto_rawDesc), len(file_meshtrade_wallet_account_v1_account_proto_rawDesc)))
	})
	return file_meshtrade_wallet_account_v1_account_proto_rawDescData
}

var file_meshtrade_wallet_account_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meshtrade_wallet_account_v1_account_proto_goTypes = []any{
	(*Account)(nil), // 0: meshtrade.wallet.account.v1.Account
}
var file_meshtrade_wallet_account_v1_account_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meshtrade_wallet_account_v1_account_proto_init() }
func file_meshtrade_wallet_account_v1_account_proto_init() {
	if File_meshtrade_wallet_account_v1_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshtrade_wallet_account_v1_account_proto_rawDesc), len(file_meshtrade_wallet_account_v1_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshtrade_wallet_account_v1_account_proto_goTypes,
		DependencyIndexes: file_meshtrade_wallet_account_v1_account_proto_depIdxs,
		MessageInfos:      file_meshtrade_wallet_account_v1_account_proto_msgTypes,
	}.Build()
	File_meshtrade_wallet_account_v1_account_proto = out.File
	file_meshtrade_wallet_account_v1_account_proto_goTypes = nil
	file_meshtrade_wallet_account_v1_account_proto_depIdxs = nil
}
