# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/proto/client/clientType.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'api/proto/client/clientType.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!api/proto/client/clientType.proto\x12\napi.client*\x93\x01\n\nClientType\x12!\n\x1dUNDEFINED_COMPANY_CLIENT_TYPE\x10\x00\x12\x1e\n\x1aISSUER_COMPANY_CLIENT_TYPE\x10\x01\x12 \n\x1cINVESTOR_COMPANY_CLIENT_TYPE\x10\x02\x12 \n\x1cMANAGING_COMPANY_CLIENT_TYPE\x10\x03\x42$Z\"github.com/meshtrade/api/go/clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.python.lib.client.clientType_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"github.com/meshtrade/api/go/client'
  _globals['_CLIENTTYPE']._serialized_start=50
  _globals['_CLIENTTYPE']._serialized_end=197
# @@protoc_insertion_point(module_scope)
