// Code generated by protoc-gen-meshgo. DO NOT EDIT.
// source: api/proto/banking/funding/peachPaymentMetaData.proto
package funding

import (
	fmt "fmt"
	bson "go.mongodb.org/mongo-driver/bson"
	bsontype "go.mongodb.org/mongo-driver/bson/bsontype"
)

// peachPaymentMetaDataBSONAtTypeName is the annotation used when marshalling a PeachPaymentMetaData to BSON for mongo db persistence
const peachPaymentMetaDataBSONAtTypeName = "mesh::funding/PeachPaymentMetaData"

// Ensure that PeachPaymentMetaData implements the bson.Marshaler interface
var _ bson.Marshaler = &PeachPaymentMetaData{}

// MarshalBSONValue is called to marshal PeachPaymentMetaData when it is embedded as a field in another struct.
// This behaviour is overridden to get desired nil behaviour.
func (p *PeachPaymentMetaData) MarshalBSONValue() (bsontype.Type, []byte, error) {
	// if this PeachPaymentMetaData is nil then return the bson null type and no data
	if p == nil {
		return bson.TypeNull, nil, nil
	}

	// otherwise call the MarshalBSON method to get data and a possible error
	bsonData, err := p.MarshalBSON()

	// then return the bson embedded document type along with the associated data and error
	return bson.TypeEmbeddedDocument, bsonData, err
}

// MarshalBSON controls the marshalling of a PeachPaymentMetaData to BSON for persistence to mongo db
func (p *PeachPaymentMetaData) MarshalBSON() ([]byte, error) {
	type Alias PeachPaymentMetaData
	return bson.Marshal(struct {
		AtType string `bson:"@type"`
		Alias  `bson:"inline"`
	}{
		AtType: peachPaymentMetaDataBSONAtTypeName,
		Alias:  Alias(*p),
	})
}

// Ensure that PeachPaymentMetaData implements the bson.Unmarshaler interface
var _ bson.Unmarshaler = &PeachPaymentMetaData{}

// MarshalBSON controls the unmarshalling of a PeachPaymentMetaData from BSON
func (p *PeachPaymentMetaData) UnmarshalBSON(data []byte) error {
	// prepare marshalled type to unmarshall into
	type Alias PeachPaymentMetaData
	var marshalled = struct {
		Alias `bson:"inline"`
	}{}

	// perform unmarshal
	if err := bson.Unmarshal(data, &marshalled); err != nil {
		return fmt.Errorf("error unmarshalling PeachPaymentMetaData: %w", err)
	}

	// set alias fields
	*p = PeachPaymentMetaData(marshalled.Alias)

	// set overridden fields

	return nil
}
