// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: meshtrade/reporting/income_report/v1/entry.proto

package income_reportv1

import (
	v1 "github.com/meshtrade/api/go/type/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entry struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AssetName             string                 `protobuf:"bytes,1,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	Token                 *v1.Token              `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Date                  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Description           string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Narrative             string                 `protobuf:"bytes,5,opt,name=narrative,proto3" json:"narrative,omitempty"`
	Amount                *v1.Amount             `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	ReportedCurrencyValue *v1.Amount             `protobuf:"bytes,7,opt,name=reported_currency_value,json=reportedCurrencyValue,proto3" json:"reported_currency_value,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_meshtrade_reporting_income_report_v1_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_reporting_income_report_v1_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_meshtrade_reporting_income_report_v1_entry_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *Entry) GetToken() *v1.Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *Entry) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Entry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Entry) GetNarrative() string {
	if x != nil {
		return x.Narrative
	}
	return ""
}

func (x *Entry) GetAmount() *v1.Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Entry) GetReportedCurrencyValue() *v1.Amount {
	if x != nil {
		return x.ReportedCurrencyValue
	}
	return nil
}

var File_meshtrade_reporting_income_report_v1_entry_proto protoreflect.FileDescriptor

const file_meshtrade_reporting_income_report_v1_entry_proto_rawDesc = "" +
	"\n" +
	"0meshtrade/reporting/income_report/v1/entry.proto\x12$meshtrade.reporting.income_report.v1\x1a\x1dmeshtrade/type/v1/token.proto\x1a\x1emeshtrade/type/v1/amount.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x02\n" +
	"\x05Entry\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x01 \x01(\tR\tassetName\x12.\n" +
	"\x05token\x18\x02 \x01(\v2\x18.meshtrade.type.v1.TokenR\x05token\x12.\n" +
	"\x04date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\tnarrative\x18\x05 \x01(\tR\tnarrative\x121\n" +
	"\x06amount\x18\x06 \x01(\v2\x19.meshtrade.type.v1.AmountR\x06amount\x12Q\n" +
	"\x17reported_currency_value\x18\a \x01(\v2\x19.meshtrade.type.v1.AmountR\x15reportedCurrencyValueBHZFgithub.com/meshtrade/api/go/reporting/income_report/v1;income_reportv1b\x06proto3"

var (
	file_meshtrade_reporting_income_report_v1_entry_proto_rawDescOnce sync.Once
	file_meshtrade_reporting_income_report_v1_entry_proto_rawDescData []byte
)

func file_meshtrade_reporting_income_report_v1_entry_proto_rawDescGZIP() []byte {
	file_meshtrade_reporting_income_report_v1_entry_proto_rawDescOnce.Do(func() {
		file_meshtrade_reporting_income_report_v1_entry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshtrade_reporting_income_report_v1_entry_proto_rawDesc), len(file_meshtrade_reporting_income_report_v1_entry_proto_rawDesc)))
	})
	return file_meshtrade_reporting_income_report_v1_entry_proto_rawDescData
}

var file_meshtrade_reporting_income_report_v1_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meshtrade_reporting_income_report_v1_entry_proto_goTypes = []any{
	(*Entry)(nil),                 // 0: meshtrade.reporting.income_report.v1.Entry
	(*v1.Token)(nil),              // 1: meshtrade.type.v1.Token
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*v1.Amount)(nil),             // 3: meshtrade.type.v1.Amount
}
var file_meshtrade_reporting_income_report_v1_entry_proto_depIdxs = []int32{
	1, // 0: meshtrade.reporting.income_report.v1.Entry.token:type_name -> meshtrade.type.v1.Token
	2, // 1: meshtrade.reporting.income_report.v1.Entry.date:type_name -> google.protobuf.Timestamp
	3, // 2: meshtrade.reporting.income_report.v1.Entry.amount:type_name -> meshtrade.type.v1.Amount
	3, // 3: meshtrade.reporting.income_report.v1.Entry.reported_currency_value:type_name -> meshtrade.type.v1.Amount
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_meshtrade_reporting_income_report_v1_entry_proto_init() }
func file_meshtrade_reporting_income_report_v1_entry_proto_init() {
	if File_meshtrade_reporting_income_report_v1_entry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshtrade_reporting_income_report_v1_entry_proto_rawDesc), len(file_meshtrade_reporting_income_report_v1_entry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshtrade_reporting_income_report_v1_entry_proto_goTypes,
		DependencyIndexes: file_meshtrade_reporting_income_report_v1_entry_proto_depIdxs,
		MessageInfos:      file_meshtrade_reporting_income_report_v1_entry_proto_msgTypes,
	}.Build()
	File_meshtrade_reporting_income_report_v1_entry_proto = out.File
	file_meshtrade_reporting_income_report_v1_entry_proto_goTypes = nil
	file_meshtrade_reporting_income_report_v1_entry_proto_depIdxs = nil
}
