// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: meshtrade/reporting/income_report/v1/income_report.proto

package income_reportv1

import (
	v1 "github.com/meshtrade/api/go/type/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IncomeReport represents a detailed report of income entries over a specific period.
//
// It contains individual transaction entries, an aggregated summary,
// metadata about the reporting period, client information, and any
// relevant disclaimers or copyright notes.
//
// This structure supports both display and export of income reporting data.
type IncomeReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of detailed income entries included in this report.
	Entries []*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// Aggregated summary of the income report, including totals by currency.
	Summary *Summary `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	// Token representing the currency in which the report values are denominated.
	ReportingCurrency *v1.Token `protobuf:"bytes,3,opt,name=reporting_currency,json=reportingCurrency,proto3" json:"reporting_currency,omitempty"`
	// The period covered by this report.
	Period *IncomeReport_Period `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`
	// Timestamp indicating when this report was generated.
	GenerationDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=generation_date,json=generationDate,proto3" json:"generation_date,omitempty"`
	// Account number for which this income report applies.
	AccountNumber string `protobuf:"bytes,6,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	// Optional disclaimers or notices to accompany the report.
	Disclaimers []string `protobuf:"bytes,7,rep,name=disclaimers,proto3" json:"disclaimers,omitempty"`
	// Address details of the client for whom the report is generated.
	ClientAddress *v1.Address `protobuf:"bytes,8,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	// Name of the client associated with this report.
	ClientName string `protobuf:"bytes,9,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	// Copyright or attribution text related to this income report.
	Copyright     string `protobuf:"bytes,10,opt,name=copyright,proto3" json:"copyright,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomeReport) Reset() {
	*x = IncomeReport{}
	mi := &file_meshtrade_reporting_income_report_v1_income_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomeReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomeReport) ProtoMessage() {}

func (x *IncomeReport) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_reporting_income_report_v1_income_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomeReport.ProtoReflect.Descriptor instead.
func (*IncomeReport) Descriptor() ([]byte, []int) {
	return file_meshtrade_reporting_income_report_v1_income_report_proto_rawDescGZIP(), []int{0}
}

func (x *IncomeReport) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *IncomeReport) GetSummary() *Summary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *IncomeReport) GetReportingCurrency() *v1.Token {
	if x != nil {
		return x.ReportingCurrency
	}
	return nil
}

func (x *IncomeReport) GetPeriod() *IncomeReport_Period {
	if x != nil {
		return x.Period
	}
	return nil
}

func (x *IncomeReport) GetGenerationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.GenerationDate
	}
	return nil
}

func (x *IncomeReport) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *IncomeReport) GetDisclaimers() []string {
	if x != nil {
		return x.Disclaimers
	}
	return nil
}

func (x *IncomeReport) GetClientAddress() *v1.Address {
	if x != nil {
		return x.ClientAddress
	}
	return nil
}

func (x *IncomeReport) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *IncomeReport) GetCopyright() string {
	if x != nil {
		return x.Copyright
	}
	return ""
}

// Reporting period for which this income report was generated.
type IncomeReport_Period struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start timestamp (inclusive) of the reporting period.
	From *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// End timestamp (inclusive) of the reporting period.
	To            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomeReport_Period) Reset() {
	*x = IncomeReport_Period{}
	mi := &file_meshtrade_reporting_income_report_v1_income_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomeReport_Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomeReport_Period) ProtoMessage() {}

func (x *IncomeReport_Period) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_reporting_income_report_v1_income_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomeReport_Period.ProtoReflect.Descriptor instead.
func (*IncomeReport_Period) Descriptor() ([]byte, []int) {
	return file_meshtrade_reporting_income_report_v1_income_report_proto_rawDescGZIP(), []int{0, 0}
}

func (x *IncomeReport_Period) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *IncomeReport_Period) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

var File_meshtrade_reporting_income_report_v1_income_report_proto protoreflect.FileDescriptor

const file_meshtrade_reporting_income_report_v1_income_report_proto_rawDesc = "" +
	"\n" +
	"8meshtrade/reporting/income_report/v1/income_report.proto\x12$meshtrade.reporting.income_report.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dmeshtrade/type/v1/token.proto\x1a\x1fmeshtrade/type/v1/address.proto\x1a2meshtrade/reporting/income_report/v1/summary.proto\x1a0meshtrade/reporting/income_report/v1/entry.proto\"\xb0\x05\n" +
	"\fIncomeReport\x12E\n" +
	"\aentries\x18\x01 \x03(\v2+.meshtrade.reporting.income_report.v1.EntryR\aentries\x12G\n" +
	"\asummary\x18\x02 \x01(\v2-.meshtrade.reporting.income_report.v1.SummaryR\asummary\x12G\n" +
	"\x12reporting_currency\x18\x03 \x01(\v2\x18.meshtrade.type.v1.TokenR\x11reportingCurrency\x12Q\n" +
	"\x06period\x18\x04 \x01(\v29.meshtrade.reporting.income_report.v1.IncomeReport.PeriodR\x06period\x12C\n" +
	"\x0fgeneration_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0egenerationDate\x12%\n" +
	"\x0eaccount_number\x18\x06 \x01(\tR\raccountNumber\x12 \n" +
	"\vdisclaimers\x18\a \x03(\tR\vdisclaimers\x12A\n" +
	"\x0eclient_address\x18\b \x01(\v2\x1a.meshtrade.type.v1.AddressR\rclientAddress\x12\x1f\n" +
	"\vclient_name\x18\t \x01(\tR\n" +
	"clientName\x12\x1c\n" +
	"\tcopyright\x18\n" +
	" \x01(\tR\tcopyright\x1ad\n" +
	"\x06Period\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02toBHZFgithub.com/meshtrade/api/go/reporting/income_report/v1;income_reportv1b\x06proto3"

var (
	file_meshtrade_reporting_income_report_v1_income_report_proto_rawDescOnce sync.Once
	file_meshtrade_reporting_income_report_v1_income_report_proto_rawDescData []byte
)

func file_meshtrade_reporting_income_report_v1_income_report_proto_rawDescGZIP() []byte {
	file_meshtrade_reporting_income_report_v1_income_report_proto_rawDescOnce.Do(func() {
		file_meshtrade_reporting_income_report_v1_income_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshtrade_reporting_income_report_v1_income_report_proto_rawDesc), len(file_meshtrade_reporting_income_report_v1_income_report_proto_rawDesc)))
	})
	return file_meshtrade_reporting_income_report_v1_income_report_proto_rawDescData
}

var file_meshtrade_reporting_income_report_v1_income_report_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meshtrade_reporting_income_report_v1_income_report_proto_goTypes = []any{
	(*IncomeReport)(nil),          // 0: meshtrade.reporting.income_report.v1.IncomeReport
	(*IncomeReport_Period)(nil),   // 1: meshtrade.reporting.income_report.v1.IncomeReport.Period
	(*Entry)(nil),                 // 2: meshtrade.reporting.income_report.v1.Entry
	(*Summary)(nil),               // 3: meshtrade.reporting.income_report.v1.Summary
	(*v1.Token)(nil),              // 4: meshtrade.type.v1.Token
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*v1.Address)(nil),            // 6: meshtrade.type.v1.Address
}
var file_meshtrade_reporting_income_report_v1_income_report_proto_depIdxs = []int32{
	2, // 0: meshtrade.reporting.income_report.v1.IncomeReport.entries:type_name -> meshtrade.reporting.income_report.v1.Entry
	3, // 1: meshtrade.reporting.income_report.v1.IncomeReport.summary:type_name -> meshtrade.reporting.income_report.v1.Summary
	4, // 2: meshtrade.reporting.income_report.v1.IncomeReport.reporting_currency:type_name -> meshtrade.type.v1.Token
	1, // 3: meshtrade.reporting.income_report.v1.IncomeReport.period:type_name -> meshtrade.reporting.income_report.v1.IncomeReport.Period
	5, // 4: meshtrade.reporting.income_report.v1.IncomeReport.generation_date:type_name -> google.protobuf.Timestamp
	6, // 5: meshtrade.reporting.income_report.v1.IncomeReport.client_address:type_name -> meshtrade.type.v1.Address
	5, // 6: meshtrade.reporting.income_report.v1.IncomeReport.Period.from:type_name -> google.protobuf.Timestamp
	5, // 7: meshtrade.reporting.income_report.v1.IncomeReport.Period.to:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_meshtrade_reporting_income_report_v1_income_report_proto_init() }
func file_meshtrade_reporting_income_report_v1_income_report_proto_init() {
	if File_meshtrade_reporting_income_report_v1_income_report_proto != nil {
		return
	}
	file_meshtrade_reporting_income_report_v1_summary_proto_init()
	file_meshtrade_reporting_income_report_v1_entry_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshtrade_reporting_income_report_v1_income_report_proto_rawDesc), len(file_meshtrade_reporting_income_report_v1_income_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshtrade_reporting_income_report_v1_income_report_proto_goTypes,
		DependencyIndexes: file_meshtrade_reporting_income_report_v1_income_report_proto_depIdxs,
		MessageInfos:      file_meshtrade_reporting_income_report_v1_income_report_proto_msgTypes,
	}.Build()
	File_meshtrade_reporting_income_report_v1_income_report_proto = out.File
	file_meshtrade_reporting_income_report_v1_income_report_proto_goTypes = nil
	file_meshtrade_reporting_income_report_v1_income_report_proto_depIdxs = nil
}
