// Code generated by protoc-gen-meshgo. DO NOT EDIT.
// source: meshtrade/reporting/account_report/v1/service.proto
package account_reportv1

import (
	context "context"
)

// AccountReportService manages comprehensive account activity report generation and export.
//
// This service allows clients to retrieve structured account reports containing
// income entries, fee transactions, and trading statements, as well as download
// them as Excel files. Reports are generated for a specified account over a
// given time range with all values denominated in the account's reporting currency.
//
// All operations require Reporting domain permissions and operate within
// the authenticated group context.
type AccountReportService interface {
	// Retrieves a structured account report for a specific account and time range.
	//
	// Parameters:
	// - account_number: Unique account identifier
	// - from: Start timestamp for the report period (inclusive)
	// - to: End timestamp for the report period (inclusive)
	// - reporting_asset_token: Token in which all report values will be denominated
	//
	// Returns:
	// - AccountReport: Comprehensive report containing income entries, fees, and trading statements
	GetAccountReport(ctx context.Context, request *GetAccountReportRequest) (*AccountReport, error)

	// Exports an account report to Excel format for download.
	//
	// Parameters:
	// - account_number: Unique account identifier (must be numeric)
	// - from: Start timestamp for the report period (inclusive)
	// - to: End timestamp for the report period (inclusive)
	// - reporting_asset_token: Token in which all report values will be denominated
	//
	// Returns:
	// - GetExcelAccountReportResponse: Base64-encoded Excel file containing the complete report
	GetExcelAccountReport(ctx context.Context, request *GetExcelAccountReportRequest) (*GetExcelAccountReportResponse, error)
}

const AccountReportServiceServiceProviderName = "meshtrade-reporting-account_report-v1-AccountReportService"
