# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meshtrade/fee/instrument_fee_profile/v1/lifecycle_event_calculation_config_amount.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'meshtrade/fee/instrument_fee_profile/v1/lifecycle_event_calculation_config_amount.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from meshtrade.type.v1 import amount_pb2 as meshtrade_dot_type_dot_v1_dot_amount__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nWmeshtrade/fee/instrument_fee_profile/v1/lifecycle_event_calculation_config_amount.proto\x12\'meshtrade.fee.instrument_fee_profile.v1\x1a\x1emeshtrade/type/v1/amount.proto\"Z\n%AmountLifecycleEventCalculationConfig\x12\x31\n\x06\x61mount\x18\x01 \x01(\x0b\x32\x19.meshtrade.type.v1.AmountR\x06\x61mountBTZRgithub.com/meshtrade/api/go/fee/instrument_fee_profile/v1;instrument_fee_profilev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meshtrade.fee.instrument_fee_profile.v1.lifecycle_event_calculation_config_amount_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZRgithub.com/meshtrade/api/go/fee/instrument_fee_profile/v1;instrument_fee_profilev1'
  _globals['_AMOUNTLIFECYCLEEVENTCALCULATIONCONFIG']._serialized_start=164
  _globals['_AMOUNTLIFECYCLEEVENTCALCULATIONCONFIG']._serialized_end=254
# @@protoc_insertion_point(module_scope)
