# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meshtrade/compliance/client/v1/legal_person_form.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'meshtrade/compliance/client/v1/legal_person_form.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6meshtrade/compliance/client/v1/legal_person_form.proto\x12\x1emeshtrade.compliance.client.v1*\xea\x02\n\x0fLegalPersonForm\x12!\n\x1dLEGAL_PERSON_FORM_UNSPECIFIED\x10\x00\x12)\n%LEGAL_PERSON_FORM_SOLE_PROPRIETORSHIP\x10\x01\x12%\n!LEGAL_PERSON_FORM_PRIVATE_COMPANY\x10\x02\x12-\n)LEGAL_PERSON_FORM_PUBLICLY_LISTED_COMPANY\x10\x03\x12!\n\x1dLEGAL_PERSON_FORM_PARTNERSHIP\x10\x04\x12\x1b\n\x17LEGAL_PERSON_FORM_TRUST\x10\x05\x12-\n)LEGAL_PERSON_FORM_NON_PROFIT_ORGANIZATION\x10\x06\x12\'\n#LEGAL_PERSON_FORM_GOVERNMENT_ENTITY\x10\x07\x12\x1b\n\x17LEGAL_PERSON_FORM_OTHER\x10\x08\x42;Z9github.com/meshtrade/api/go/compliance/client/v1;clientv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meshtrade.compliance.client.v1.legal_person_form_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/meshtrade/api/go/compliance/client/v1;clientv1'
  _globals['_LEGALPERSONFORM']._serialized_start=91
  _globals['_LEGALPERSONFORM']._serialized_end=453
# @@protoc_insertion_point(module_scope)
