from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class LegalPersonConnectionType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LEGAL_PERSON_CONNECTION_TYPE_UNSPECIFIED: _ClassVar[LegalPersonConnectionType]
    LEGAL_PERSON_CONNECTION_TYPE_SHAREHOLDER: _ClassVar[LegalPersonConnectionType]
    LEGAL_PERSON_CONNECTION_TYPE_PARENT_COMPANY: _ClassVar[LegalPersonConnectionType]
    LEGAL_PERSON_CONNECTION_TYPE_CORPORATE_DIRECTOR: _ClassVar[LegalPersonConnectionType]
    LEGAL_PERSON_CONNECTION_TYPE_TRUST: _ClassVar[LegalPersonConnectionType]
    LEGAL_PERSON_CONNECTION_TYPE_GENERAL_PARTNER: _ClassVar[LegalPersonConnectionType]
    LEGAL_PERSON_CONNECTION_TYPE_GUARANTOR: _ClassVar[LegalPersonConnectionType]
LEGAL_PERSON_CONNECTION_TYPE_UNSPECIFIED: LegalPersonConnectionType
LEGAL_PERSON_CONNECTION_TYPE_SHAREHOLDER: LegalPersonConnectionType
LEGAL_PERSON_CONNECTION_TYPE_PARENT_COMPANY: LegalPersonConnectionType
LEGAL_PERSON_CONNECTION_TYPE_CORPORATE_DIRECTOR: LegalPersonConnectionType
LEGAL_PERSON_CONNECTION_TYPE_TRUST: LegalPersonConnectionType
LEGAL_PERSON_CONNECTION_TYPE_GENERAL_PARTNER: LegalPersonConnectionType
LEGAL_PERSON_CONNECTION_TYPE_GUARANTOR: LegalPersonConnectionType
