// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: instrument/feeprofile/lifecycleEventCategory.proto

package feeprofile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LifecycleEventCategory defines the different types of lifecycle events that can trigger a Fee.
type LifecycleEventCategory int32

const (
	LifecycleEventCategory_UNDEFINED_LIFECYCLE_EVENT_CATEGORY                 LifecycleEventCategory = 0 // 0 not used to prevent unexpected default value behaviour.
	LifecycleEventCategory_LISTING_LIFECYCLE_EVENT_CATEGORY                   LifecycleEventCategory = 1
	LifecycleEventCategory_PRIMARY_MARKET_SETTLEMENT_LIFECYCLE_EVENT_CATEGORY LifecycleEventCategory = 2
)

// Enum value maps for LifecycleEventCategory.
var (
	LifecycleEventCategory_name = map[int32]string{
		0: "UNDEFINED_LIFECYCLE_EVENT_CATEGORY",
		1: "LISTING_LIFECYCLE_EVENT_CATEGORY",
		2: "PRIMARY_MARKET_SETTLEMENT_LIFECYCLE_EVENT_CATEGORY",
	}
	LifecycleEventCategory_value = map[string]int32{
		"UNDEFINED_LIFECYCLE_EVENT_CATEGORY":                 0,
		"LISTING_LIFECYCLE_EVENT_CATEGORY":                   1,
		"PRIMARY_MARKET_SETTLEMENT_LIFECYCLE_EVENT_CATEGORY": 2,
	}
)

func (x LifecycleEventCategory) Enum() *LifecycleEventCategory {
	p := new(LifecycleEventCategory)
	*p = x
	return p
}

func (x LifecycleEventCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifecycleEventCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_instrument_feeprofile_lifecycleEventCategory_proto_enumTypes[0].Descriptor()
}

func (LifecycleEventCategory) Type() protoreflect.EnumType {
	return &file_instrument_feeprofile_lifecycleEventCategory_proto_enumTypes[0]
}

func (x LifecycleEventCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LifecycleEventCategory.Descriptor instead.
func (LifecycleEventCategory) EnumDescriptor() ([]byte, []int) {
	return file_instrument_feeprofile_lifecycleEventCategory_proto_rawDescGZIP(), []int{0}
}

var File_instrument_feeprofile_lifecycleEventCategory_proto protoreflect.FileDescriptor

var file_instrument_feeprofile_lifecycleEventCategory_proto_rawDesc = []byte{
	0x0a, 0x32, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x66, 0x65, 0x65,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x6c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x66, 0x65, 0x65, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2a,
	0x9e, 0x01, 0x0a, 0x16, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x26, 0x0a, 0x22, 0x55, 0x4e,
	0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x5f, 0x4c, 0x49, 0x46, 0x45, 0x43, 0x59, 0x43, 0x4c,
	0x45, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59,
	0x10, 0x00, 0x12, 0x24, 0x0a, 0x20, 0x4c, 0x49, 0x53, 0x54, 0x49, 0x4e, 0x47, 0x5f, 0x4c, 0x49,
	0x46, 0x45, 0x43, 0x59, 0x43, 0x4c, 0x45, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x43, 0x41,
	0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x10, 0x01, 0x12, 0x36, 0x0a, 0x32, 0x50, 0x52, 0x49, 0x4d,
	0x41, 0x52, 0x59, 0x5f, 0x4d, 0x41, 0x52, 0x4b, 0x45, 0x54, 0x5f, 0x53, 0x45, 0x54, 0x54, 0x4c,
	0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x4c, 0x49, 0x46, 0x45, 0x43, 0x59, 0x43, 0x4c, 0x45, 0x5f,
	0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x10, 0x02,
	0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x65, 0x73, 0x68, 0x74, 0x72, 0x61, 0x64, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x2f,
	0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x66, 0x65, 0x65, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_instrument_feeprofile_lifecycleEventCategory_proto_rawDescOnce sync.Once
	file_instrument_feeprofile_lifecycleEventCategory_proto_rawDescData = file_instrument_feeprofile_lifecycleEventCategory_proto_rawDesc
)

func file_instrument_feeprofile_lifecycleEventCategory_proto_rawDescGZIP() []byte {
	file_instrument_feeprofile_lifecycleEventCategory_proto_rawDescOnce.Do(func() {
		file_instrument_feeprofile_lifecycleEventCategory_proto_rawDescData = protoimpl.X.CompressGZIP(file_instrument_feeprofile_lifecycleEventCategory_proto_rawDescData)
	})
	return file_instrument_feeprofile_lifecycleEventCategory_proto_rawDescData
}

var file_instrument_feeprofile_lifecycleEventCategory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_instrument_feeprofile_lifecycleEventCategory_proto_goTypes = []interface{}{
	(LifecycleEventCategory)(0), // 0: api.instrument.feeprofile.LifecycleEventCategory
}
var file_instrument_feeprofile_lifecycleEventCategory_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_instrument_feeprofile_lifecycleEventCategory_proto_init() }
func file_instrument_feeprofile_lifecycleEventCategory_proto_init() {
	if File_instrument_feeprofile_lifecycleEventCategory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_instrument_feeprofile_lifecycleEventCategory_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_instrument_feeprofile_lifecycleEventCategory_proto_goTypes,
		DependencyIndexes: file_instrument_feeprofile_lifecycleEventCategory_proto_depIdxs,
		EnumInfos:         file_instrument_feeprofile_lifecycleEventCategory_proto_enumTypes,
	}.Build()
	File_instrument_feeprofile_lifecycleEventCategory_proto = out.File
	file_instrument_feeprofile_lifecycleEventCategory_proto_rawDesc = nil
	file_instrument_feeprofile_lifecycleEventCategory_proto_goTypes = nil
	file_instrument_feeprofile_lifecycleEventCategory_proto_depIdxs = nil
}
