[project]
name = "mesh-python-workspace"
version = "0.0.1"
description = "Development workspace for the Mesh Python API integration SDKs."

[project.optional-dependencies]
dev = [
    # Install local libraries in editable mode.
    # The paths are relative to THIS file.
    "mesh-account-v1 @ file:./lib/account/v1",
    "mesh-iam-v1 @ file:./lib/iam/v1",

    # Development tools
    "pip-tools ~= 7.4.1",
    "ruff ~= 0.11.13",
    "pytest ~= 8.4.0",
    "build ~= 1.2.2",
    "twine ~= 6.1.0",
    "tox ~= 4.26.0",
]

# --- Ruff Configuration (Linter and Formatter) ---
[tool.ruff]
target-version = "py38"
line-length = 88

[tool.ruff.lint]
# E/W: flake8 errors/warnings | F: Pyflakes
# I: isort | B: flake8-bugbear | C4: flake8-comprehensions
# SIM: flake8-simplify | UP: pyupgrade | TID: flake8-tidy-imports
select = ["E", "W", "F", "I", "B", "C4", "SIM", "UP", "TID"]

[tool.ruff.lint.per-file-ignores]
# ignore unused import error in generated files
"*_pb.py" = ["F401"]