// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: meshtrade/iam/role/v1/role.proto

package role_v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role defines a named collection of permissions.
// This allows for the creation of business-level roles (e.g., "AccountReader", "AccountAdmin")
// that group a set of granular, string-based permissions. Roles are
// defined at the file level in a service's `.proto` file.
type Role int32

const (
	// The default value, indicating the role is unknown or not specified.
	// This should be treated as an error and not be used explicitly.
	Role_ROLE_UNSPECIFIED                Role = 0
	Role_ROLE_WALLET_ADMIN               Role = 1000000
	Role_ROLE_WALLET_VIEWER              Role = 1000001
	Role_ROLE_WALLET_ACCOUNT_ADMIN       Role = 1000002
	Role_ROLE_WALLET_ACCOUNT_VIEWER      Role = 1000003
	Role_ROLE_COMPLIANCE_ADMIN           Role = 2000000
	Role_ROLE_COMPLIANCE_VIEWER          Role = 2000001
	Role_ROLE_COMPLIANCE_CLIENT_ADMIN    Role = 2000002
	Role_ROLE_COMPLIANCE_CLIENT_VIEWER   Role = 2000003
	Role_ROLE_IAM_ADMIN                  Role = 3000000
	Role_ROLE_IAM_VIEWER                 Role = 3000001
	Role_ROLE_IAM_API_USER_ADMIN         Role = 3000002
	Role_ROLE_IAM_API_USER_VIEWER        Role = 3000003
	Role_ROLE_IAM_GROUP_ADMIN            Role = 3000004
	Role_ROLE_IAM_GROUP_VIEWER           Role = 3000005
	Role_ROLE_IAM_USER_ADMIN             Role = 3000006
	Role_ROLE_IAM_USER_VIEWER            Role = 3000007
	Role_ROLE_STUDIO_ADMIN               Role = 4000000
	Role_ROLE_STUDIO_VIEWER              Role = 4000001
	Role_ROLE_STUDIO_INSTRUMENT_ADMIN    Role = 4000002
	Role_ROLE_STUDIO_INSTRUMENT_VIEWER   Role = 4000003
	Role_ROLE_TRADING_ADMIN              Role = 5000000
	Role_ROLE_TRADING_VIEWER             Role = 5000001
	Role_ROLE_TRADING_LIMIT_ORDER_ADMIN  Role = 5000002
	Role_ROLE_TRADING_LIMIT_ORDER_VIEWER Role = 5000003
	Role_ROLE_REPORTING_ADMIN            Role = 6000000
	Role_ROLE_REPORTING_VIEWER           Role = 6000001
	Role_ROLE_LEDGER_ADMIN               Role = 7000000
	Role_ROLE_LEDGER_VIEWER              Role = 7000001
	Role_ROLE_LEDGER_TRANSACTION_ADMIN   Role = 7000002
	Role_ROLE_LEDGER_TRANSACTION_VIEWER  Role = 7000003
	Role_ROLE_LEDGER_TOKEN_TAP_ADMIN     Role = 7000004
	Role_ROLE_LEDGER_TOKEN_TAP_VIEWER    Role = 7000005
	Role_ROLE_MARKET_DATA_ADMIN          Role = 8000000
	Role_ROLE_MARKET_DATA_VIEWER         Role = 8000001
	Role_ROLE_MARKET_DATA_PRICE_ADMIN    Role = 8000002
	Role_ROLE_MARKET_DATA_PRICE_VIEWER   Role = 8000003
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0:       "ROLE_UNSPECIFIED",
		1000000: "ROLE_WALLET_ADMIN",
		1000001: "ROLE_WALLET_VIEWER",
		1000002: "ROLE_WALLET_ACCOUNT_ADMIN",
		1000003: "ROLE_WALLET_ACCOUNT_VIEWER",
		2000000: "ROLE_COMPLIANCE_ADMIN",
		2000001: "ROLE_COMPLIANCE_VIEWER",
		2000002: "ROLE_COMPLIANCE_CLIENT_ADMIN",
		2000003: "ROLE_COMPLIANCE_CLIENT_VIEWER",
		3000000: "ROLE_IAM_ADMIN",
		3000001: "ROLE_IAM_VIEWER",
		3000002: "ROLE_IAM_API_USER_ADMIN",
		3000003: "ROLE_IAM_API_USER_VIEWER",
		3000004: "ROLE_IAM_GROUP_ADMIN",
		3000005: "ROLE_IAM_GROUP_VIEWER",
		3000006: "ROLE_IAM_USER_ADMIN",
		3000007: "ROLE_IAM_USER_VIEWER",
		4000000: "ROLE_STUDIO_ADMIN",
		4000001: "ROLE_STUDIO_VIEWER",
		4000002: "ROLE_STUDIO_INSTRUMENT_ADMIN",
		4000003: "ROLE_STUDIO_INSTRUMENT_VIEWER",
		5000000: "ROLE_TRADING_ADMIN",
		5000001: "ROLE_TRADING_VIEWER",
		5000002: "ROLE_TRADING_LIMIT_ORDER_ADMIN",
		5000003: "ROLE_TRADING_LIMIT_ORDER_VIEWER",
		6000000: "ROLE_REPORTING_ADMIN",
		6000001: "ROLE_REPORTING_VIEWER",
		7000000: "ROLE_LEDGER_ADMIN",
		7000001: "ROLE_LEDGER_VIEWER",
		7000002: "ROLE_LEDGER_TRANSACTION_ADMIN",
		7000003: "ROLE_LEDGER_TRANSACTION_VIEWER",
		7000004: "ROLE_LEDGER_TOKEN_TAP_ADMIN",
		7000005: "ROLE_LEDGER_TOKEN_TAP_VIEWER",
		8000000: "ROLE_MARKET_DATA_ADMIN",
		8000001: "ROLE_MARKET_DATA_VIEWER",
		8000002: "ROLE_MARKET_DATA_PRICE_ADMIN",
		8000003: "ROLE_MARKET_DATA_PRICE_VIEWER",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED":                0,
		"ROLE_WALLET_ADMIN":               1000000,
		"ROLE_WALLET_VIEWER":              1000001,
		"ROLE_WALLET_ACCOUNT_ADMIN":       1000002,
		"ROLE_WALLET_ACCOUNT_VIEWER":      1000003,
		"ROLE_COMPLIANCE_ADMIN":           2000000,
		"ROLE_COMPLIANCE_VIEWER":          2000001,
		"ROLE_COMPLIANCE_CLIENT_ADMIN":    2000002,
		"ROLE_COMPLIANCE_CLIENT_VIEWER":   2000003,
		"ROLE_IAM_ADMIN":                  3000000,
		"ROLE_IAM_VIEWER":                 3000001,
		"ROLE_IAM_API_USER_ADMIN":         3000002,
		"ROLE_IAM_API_USER_VIEWER":        3000003,
		"ROLE_IAM_GROUP_ADMIN":            3000004,
		"ROLE_IAM_GROUP_VIEWER":           3000005,
		"ROLE_IAM_USER_ADMIN":             3000006,
		"ROLE_IAM_USER_VIEWER":            3000007,
		"ROLE_STUDIO_ADMIN":               4000000,
		"ROLE_STUDIO_VIEWER":              4000001,
		"ROLE_STUDIO_INSTRUMENT_ADMIN":    4000002,
		"ROLE_STUDIO_INSTRUMENT_VIEWER":   4000003,
		"ROLE_TRADING_ADMIN":              5000000,
		"ROLE_TRADING_VIEWER":             5000001,
		"ROLE_TRADING_LIMIT_ORDER_ADMIN":  5000002,
		"ROLE_TRADING_LIMIT_ORDER_VIEWER": 5000003,
		"ROLE_REPORTING_ADMIN":            6000000,
		"ROLE_REPORTING_VIEWER":           6000001,
		"ROLE_LEDGER_ADMIN":               7000000,
		"ROLE_LEDGER_VIEWER":              7000001,
		"ROLE_LEDGER_TRANSACTION_ADMIN":   7000002,
		"ROLE_LEDGER_TRANSACTION_VIEWER":  7000003,
		"ROLE_LEDGER_TOKEN_TAP_ADMIN":     7000004,
		"ROLE_LEDGER_TOKEN_TAP_VIEWER":    7000005,
		"ROLE_MARKET_DATA_ADMIN":          8000000,
		"ROLE_MARKET_DATA_VIEWER":         8000001,
		"ROLE_MARKET_DATA_PRICE_ADMIN":    8000002,
		"ROLE_MARKET_DATA_PRICE_VIEWER":   8000003,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtrade_iam_role_v1_role_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_meshtrade_iam_role_v1_role_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_meshtrade_iam_role_v1_role_proto_rawDescGZIP(), []int{0}
}

var File_meshtrade_iam_role_v1_role_proto protoreflect.FileDescriptor

const file_meshtrade_iam_role_v1_role_proto_rawDesc = "" +
	"\n" +
	" meshtrade/iam/role/v1/role.proto\x12\x15meshtrade.iam.role.v1*\xc7\b\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x11ROLE_WALLET_ADMIN\x10\xc0\x84=\x12\x18\n" +
	"\x12ROLE_WALLET_VIEWER\x10\xc1\x84=\x12\x1f\n" +
	"\x19ROLE_WALLET_ACCOUNT_ADMIN\x10\u0084=\x12 \n" +
	"\x1aROLE_WALLET_ACCOUNT_VIEWER\x10Ä=\x12\x1b\n" +
	"\x15ROLE_COMPLIANCE_ADMIN\x10\x80\x89z\x12\x1c\n" +
	"\x16ROLE_COMPLIANCE_VIEWER\x10\x81\x89z\x12\"\n" +
	"\x1cROLE_COMPLIANCE_CLIENT_ADMIN\x10\x82\x89z\x12#\n" +
	"\x1dROLE_COMPLIANCE_CLIENT_VIEWER\x10\x83\x89z\x12\x15\n" +
	"\x0eROLE_IAM_ADMIN\x10\xc0\x8d\xb7\x01\x12\x16\n" +
	"\x0fROLE_IAM_VIEWER\x10\xc1\x8d\xb7\x01\x12\x1e\n" +
	"\x17ROLE_IAM_API_USER_ADMIN\x10\u008d\xb7\x01\x12\x1f\n" +
	"\x18ROLE_IAM_API_USER_VIEWER\x10Í\xb7\x01\x12\x1b\n" +
	"\x14ROLE_IAM_GROUP_ADMIN\x10č\xb7\x01\x12\x1c\n" +
	"\x15ROLE_IAM_GROUP_VIEWER\x10ō\xb7\x01\x12\x1a\n" +
	"\x13ROLE_IAM_USER_ADMIN\x10ƍ\xb7\x01\x12\x1b\n" +
	"\x14ROLE_IAM_USER_VIEWER\x10Ǎ\xb7\x01\x12\x18\n" +
	"\x11ROLE_STUDIO_ADMIN\x10\x80\x92\xf4\x01\x12\x19\n" +
	"\x12ROLE_STUDIO_VIEWER\x10\x81\x92\xf4\x01\x12#\n" +
	"\x1cROLE_STUDIO_INSTRUMENT_ADMIN\x10\x82\x92\xf4\x01\x12$\n" +
	"\x1dROLE_STUDIO_INSTRUMENT_VIEWER\x10\x83\x92\xf4\x01\x12\x19\n" +
	"\x12ROLE_TRADING_ADMIN\x10\xc0\x96\xb1\x02\x12\x1a\n" +
	"\x13ROLE_TRADING_VIEWER\x10\xc1\x96\xb1\x02\x12%\n" +
	"\x1eROLE_TRADING_LIMIT_ORDER_ADMIN\x10\u0096\xb1\x02\x12&\n" +
	"\x1fROLE_TRADING_LIMIT_ORDER_VIEWER\x10Ö\xb1\x02\x12\x1b\n" +
	"\x14ROLE_REPORTING_ADMIN\x10\x80\x9b\xee\x02\x12\x1c\n" +
	"\x15ROLE_REPORTING_VIEWER\x10\x81\x9b\xee\x02\x12\x18\n" +
	"\x11ROLE_LEDGER_ADMIN\x10\xc0\x9f\xab\x03\x12\x19\n" +
	"\x12ROLE_LEDGER_VIEWER\x10\xc1\x9f\xab\x03\x12$\n" +
	"\x1dROLE_LEDGER_TRANSACTION_ADMIN\x10\u009f\xab\x03\x12%\n" +
	"\x1eROLE_LEDGER_TRANSACTION_VIEWER\x10ß\xab\x03\x12\"\n" +
	"\x1bROLE_LEDGER_TOKEN_TAP_ADMIN\x10ğ\xab\x03\x12#\n" +
	"\x1cROLE_LEDGER_TOKEN_TAP_VIEWER\x10ş\xab\x03BO\n" +
	"\x1eROLE_LEDGER_TRANSACTION_VIEWER\x10ß\xab\x03\x12\x1d\n" +
	"\x16ROLE_MARKET_DATA_ADMIN\x10\x80\xa4\xe8\x03\x12\x1e\n" +
	"\x17ROLE_MARKET_DATA_VIEWER\x10\x81\xa4\xe8\x03\x12#\n" +
	"\x1cROLE_MARKET_DATA_PRICE_ADMIN\x10\x82\xa4\xe8\x03\x12$\n" +
	"\x1dROLE_MARKET_DATA_PRICE_VIEWER\x10\x83\xa4\xe8\x03BO\n" +
	"\x1cco.meshtrade.api.iam.role.v1Z/github.com/meshtrade/api/go/iam/role/v1;role_v1b\x06proto3"

var (
	file_meshtrade_iam_role_v1_role_proto_rawDescOnce sync.Once
	file_meshtrade_iam_role_v1_role_proto_rawDescData []byte
)

func file_meshtrade_iam_role_v1_role_proto_rawDescGZIP() []byte {
	file_meshtrade_iam_role_v1_role_proto_rawDescOnce.Do(func() {
		file_meshtrade_iam_role_v1_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshtrade_iam_role_v1_role_proto_rawDesc), len(file_meshtrade_iam_role_v1_role_proto_rawDesc)))
	})
	return file_meshtrade_iam_role_v1_role_proto_rawDescData
}

var file_meshtrade_iam_role_v1_role_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meshtrade_iam_role_v1_role_proto_goTypes = []any{
	(Role)(0), // 0: meshtrade.iam.role.v1.Role
}
var file_meshtrade_iam_role_v1_role_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meshtrade_iam_role_v1_role_proto_init() }
func file_meshtrade_iam_role_v1_role_proto_init() {
	if File_meshtrade_iam_role_v1_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshtrade_iam_role_v1_role_proto_rawDesc), len(file_meshtrade_iam_role_v1_role_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshtrade_iam_role_v1_role_proto_goTypes,
		DependencyIndexes: file_meshtrade_iam_role_v1_role_proto_depIdxs,
		EnumInfos:         file_meshtrade_iam_role_v1_role_proto_enumTypes,
	}.Build()
	File_meshtrade_iam_role_v1_role_proto = out.File
	file_meshtrade_iam_role_v1_role_proto_goTypes = nil
	file_meshtrade_iam_role_v1_role_proto_depIdxs = nil
}
