// Code generated by protoc-gen-meshgo. DO NOT EDIT.
// source: meshtrade/iam/role/v1/service.proto
package rolev1

import (
	context "context"
)

type RoleService interface {
	Get(ctx context.Context, request *GetRoleRequest) (*GetRoleResponse, error)
}

const RoleServiceServiceProviderName = "meshtrade-iam-role-v1-RoleService"
