// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: meshtrade/iam/group/v1/service.proto

package groupv1

import (
	_ "github.com/meshtrade/api/go/option/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the group to get.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_meshtrade_iam_group_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_group_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_group_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_meshtrade_iam_group_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_group_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_group_v1_service_proto_rawDescGZIP(), []int{1}
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_meshtrade_iam_group_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_group_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_group_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type SearchGroupsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is a substring search for groups.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGroupsRequest) Reset() {
	*x = SearchGroupsRequest{}
	mi := &file_meshtrade_iam_group_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGroupsRequest) ProtoMessage() {}

func (x *SearchGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_group_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGroupsRequest.ProtoReflect.Descriptor instead.
func (*SearchGroupsRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_group_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *SearchGroupsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SearchGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGroupsResponse) Reset() {
	*x = SearchGroupsResponse{}
	mi := &file_meshtrade_iam_group_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGroupsResponse) ProtoMessage() {}

func (x *SearchGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_group_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGroupsResponse.ProtoReflect.Descriptor instead.
func (*SearchGroupsResponse) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_group_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *SearchGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

var File_meshtrade_iam_group_v1_service_proto protoreflect.FileDescriptor

const file_meshtrade_iam_group_v1_service_proto_rawDesc = "" +
	"\n" +
	"$meshtrade/iam/group/v1/service.proto\x12\x16meshtrade.iam.group.v1\x1a\"meshtrade/iam/group/v1/group.proto\x1a\x1emeshtrade/option/v1/role.proto\x1a%meshtrade/option/v1/method_type.proto\"%\n" +
	"\x0fGetGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x13\n" +
	"\x11ListGroupsRequest\"K\n" +
	"\x12ListGroupsResponse\x125\n" +
	"\x06groups\x18\x01 \x03(\v2\x1d.meshtrade.iam.group.v1.GroupR\x06groups\")\n" +
	"\x13SearchGroupsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"M\n" +
	"\x14SearchGroupsResponse\x125\n" +
	"\x06groups\x18\x01 \x03(\v2\x1d.meshtrade.iam.group.v1.GroupR\x06groups2\xdc\x02\n" +
	"\fGroupService\x12`\n" +
	"\bGetGroup\x12'.meshtrade.iam.group.v1.GetGroupRequest\x1a\x1d.meshtrade.iam.group.v1.Group\"\f\xa0\xb5\x18\x01\xaa\xb5\x18\x04\n" +
	"\x02\x05\x06\x12q\n" +
	"\n" +
	"ListGroups\x12).meshtrade.iam.group.v1.ListGroupsRequest\x1a*.meshtrade.iam.group.v1.ListGroupsResponse\"\f\xa0\xb5\x18\x01\xaa\xb5\x18\x04\n" +
	"\x02\x05\x06\x12w\n" +
	"\fSearchGroups\x12+.meshtrade.iam.group.v1.SearchGroupsRequest\x1a,.meshtrade.iam.group.v1.SearchGroupsResponse\"\f\xa0\xb5\x18\x01\xaa\xb5\x18\x04\n" +
	"\x02\x05\x06B2Z0github.com/meshtrade/api/go/iam/group/v1;groupv1b\x06proto3"

var (
	file_meshtrade_iam_group_v1_service_proto_rawDescOnce sync.Once
	file_meshtrade_iam_group_v1_service_proto_rawDescData []byte
)

func file_meshtrade_iam_group_v1_service_proto_rawDescGZIP() []byte {
	file_meshtrade_iam_group_v1_service_proto_rawDescOnce.Do(func() {
		file_meshtrade_iam_group_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshtrade_iam_group_v1_service_proto_rawDesc), len(file_meshtrade_iam_group_v1_service_proto_rawDesc)))
	})
	return file_meshtrade_iam_group_v1_service_proto_rawDescData
}

var file_meshtrade_iam_group_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_meshtrade_iam_group_v1_service_proto_goTypes = []any{
	(*GetGroupRequest)(nil),      // 0: meshtrade.iam.group.v1.GetGroupRequest
	(*ListGroupsRequest)(nil),    // 1: meshtrade.iam.group.v1.ListGroupsRequest
	(*ListGroupsResponse)(nil),   // 2: meshtrade.iam.group.v1.ListGroupsResponse
	(*SearchGroupsRequest)(nil),  // 3: meshtrade.iam.group.v1.SearchGroupsRequest
	(*SearchGroupsResponse)(nil), // 4: meshtrade.iam.group.v1.SearchGroupsResponse
	(*Group)(nil),                // 5: meshtrade.iam.group.v1.Group
}
var file_meshtrade_iam_group_v1_service_proto_depIdxs = []int32{
	5, // 0: meshtrade.iam.group.v1.ListGroupsResponse.groups:type_name -> meshtrade.iam.group.v1.Group
	5, // 1: meshtrade.iam.group.v1.SearchGroupsResponse.groups:type_name -> meshtrade.iam.group.v1.Group
	0, // 2: meshtrade.iam.group.v1.GroupService.GetGroup:input_type -> meshtrade.iam.group.v1.GetGroupRequest
	1, // 3: meshtrade.iam.group.v1.GroupService.ListGroups:input_type -> meshtrade.iam.group.v1.ListGroupsRequest
	3, // 4: meshtrade.iam.group.v1.GroupService.SearchGroups:input_type -> meshtrade.iam.group.v1.SearchGroupsRequest
	5, // 5: meshtrade.iam.group.v1.GroupService.GetGroup:output_type -> meshtrade.iam.group.v1.Group
	2, // 6: meshtrade.iam.group.v1.GroupService.ListGroups:output_type -> meshtrade.iam.group.v1.ListGroupsResponse
	4, // 7: meshtrade.iam.group.v1.GroupService.SearchGroups:output_type -> meshtrade.iam.group.v1.SearchGroupsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_meshtrade_iam_group_v1_service_proto_init() }
func file_meshtrade_iam_group_v1_service_proto_init() {
	if File_meshtrade_iam_group_v1_service_proto != nil {
		return
	}
	file_meshtrade_iam_group_v1_group_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshtrade_iam_group_v1_service_proto_rawDesc), len(file_meshtrade_iam_group_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meshtrade_iam_group_v1_service_proto_goTypes,
		DependencyIndexes: file_meshtrade_iam_group_v1_service_proto_depIdxs,
		MessageInfos:      file_meshtrade_iam_group_v1_service_proto_msgTypes,
	}.Build()
	File_meshtrade_iam_group_v1_service_proto = out.File
	file_meshtrade_iam_group_v1_service_proto_goTypes = nil
	file_meshtrade_iam_group_v1_service_proto_depIdxs = nil
}
