// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: meshtrade/compliance/client/v1/identification_document_type.proto

package clientv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IdentificationDocumentType specifies the type of official document used to
// verify a client's identity.
type IdentificationDocumentType int32

const (
	// Unknown or not specified.
	// This is a default value to prevent accidental assignment and should not be used.
	IdentificationDocumentType_IDENTIFICATION_DOCUMENT_TYPE_UNSPECIFIED IdentificationDocumentType = 0
	// An international passport.
	IdentificationDocumentType_IDENTIFICATION_DOCUMENT_TYPE_PASSPORT IdentificationDocumentType = 1
	// A government-issued national identity card/book/paper.
	// This covers documents like the South African ID, a European ID card, etc.
	IdentificationDocumentType_IDENTIFICATION_DOCUMENT_TYPE_NATIONAL_ID IdentificationDocumentType = 2
	// A government-issued driver's license.
	IdentificationDocumentType_IDENTIFICATION_DOCUMENT_TYPE_DRIVERS_LICENSE IdentificationDocumentType = 3
	// A residence permit or visa issued to a foreign national.
	IdentificationDocumentType_IDENTIFICATION_DOCUMENT_TYPE_RESIDENCE_PERMIT IdentificationDocumentType = 4
)

// Enum value maps for IdentificationDocumentType.
var (
	IdentificationDocumentType_name = map[int32]string{
		0: "IDENTIFICATION_DOCUMENT_TYPE_UNSPECIFIED",
		1: "IDENTIFICATION_DOCUMENT_TYPE_PASSPORT",
		2: "IDENTIFICATION_DOCUMENT_TYPE_NATIONAL_ID",
		3: "IDENTIFICATION_DOCUMENT_TYPE_DRIVERS_LICENSE",
		4: "IDENTIFICATION_DOCUMENT_TYPE_RESIDENCE_PERMIT",
	}
	IdentificationDocumentType_value = map[string]int32{
		"IDENTIFICATION_DOCUMENT_TYPE_UNSPECIFIED":      0,
		"IDENTIFICATION_DOCUMENT_TYPE_PASSPORT":         1,
		"IDENTIFICATION_DOCUMENT_TYPE_NATIONAL_ID":      2,
		"IDENTIFICATION_DOCUMENT_TYPE_DRIVERS_LICENSE":  3,
		"IDENTIFICATION_DOCUMENT_TYPE_RESIDENCE_PERMIT": 4,
	}
)

func (x IdentificationDocumentType) Enum() *IdentificationDocumentType {
	p := new(IdentificationDocumentType)
	*p = x
	return p
}

func (x IdentificationDocumentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentificationDocumentType) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtrade_compliance_client_v1_identification_document_type_proto_enumTypes[0].Descriptor()
}

func (IdentificationDocumentType) Type() protoreflect.EnumType {
	return &file_meshtrade_compliance_client_v1_identification_document_type_proto_enumTypes[0]
}

func (x IdentificationDocumentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentificationDocumentType.Descriptor instead.
func (IdentificationDocumentType) EnumDescriptor() ([]byte, []int) {
	return file_meshtrade_compliance_client_v1_identification_document_type_proto_rawDescGZIP(), []int{0}
}

var File_meshtrade_compliance_client_v1_identification_document_type_proto protoreflect.FileDescriptor

const file_meshtrade_compliance_client_v1_identification_document_type_proto_rawDesc = "" +
	"\n" +
	"Ameshtrade/compliance/client/v1/identification_document_type.proto\x12\x1emeshtrade.compliance.client.v1*\x88\x02\n" +
	"\x1aIdentificationDocumentType\x12,\n" +
	"(IDENTIFICATION_DOCUMENT_TYPE_UNSPECIFIED\x10\x00\x12)\n" +
	"%IDENTIFICATION_DOCUMENT_TYPE_PASSPORT\x10\x01\x12,\n" +
	"(IDENTIFICATION_DOCUMENT_TYPE_NATIONAL_ID\x10\x02\x120\n" +
	",IDENTIFICATION_DOCUMENT_TYPE_DRIVERS_LICENSE\x10\x03\x121\n" +
	"-IDENTIFICATION_DOCUMENT_TYPE_RESIDENCE_PERMIT\x10\x04Bb\n" +
	"%co.meshtrade.api.compliance.client.v1Z9github.com/meshtrade/api/go/compliance/client/v1;clientv1b\x06proto3"

var (
	file_meshtrade_compliance_client_v1_identification_document_type_proto_rawDescOnce sync.Once
	file_meshtrade_compliance_client_v1_identification_document_type_proto_rawDescData []byte
)

func file_meshtrade_compliance_client_v1_identification_document_type_proto_rawDescGZIP() []byte {
	file_meshtrade_compliance_client_v1_identification_document_type_proto_rawDescOnce.Do(func() {
		file_meshtrade_compliance_client_v1_identification_document_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshtrade_compliance_client_v1_identification_document_type_proto_rawDesc), len(file_meshtrade_compliance_client_v1_identification_document_type_proto_rawDesc)))
	})
	return file_meshtrade_compliance_client_v1_identification_document_type_proto_rawDescData
}

var file_meshtrade_compliance_client_v1_identification_document_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meshtrade_compliance_client_v1_identification_document_type_proto_goTypes = []any{
	(IdentificationDocumentType)(0), // 0: meshtrade.compliance.client.v1.IdentificationDocumentType
}
var file_meshtrade_compliance_client_v1_identification_document_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meshtrade_compliance_client_v1_identification_document_type_proto_init() }
func file_meshtrade_compliance_client_v1_identification_document_type_proto_init() {
	if File_meshtrade_compliance_client_v1_identification_document_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshtrade_compliance_client_v1_identification_document_type_proto_rawDesc), len(file_meshtrade_compliance_client_v1_identification_document_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshtrade_compliance_client_v1_identification_document_type_proto_goTypes,
		DependencyIndexes: file_meshtrade_compliance_client_v1_identification_document_type_proto_depIdxs,
		EnumInfos:         file_meshtrade_compliance_client_v1_identification_document_type_proto_enumTypes,
	}.Build()
	File_meshtrade_compliance_client_v1_identification_document_type_proto = out.File
	file_meshtrade_compliance_client_v1_identification_document_type_proto_goTypes = nil
	file_meshtrade_compliance_client_v1_identification_document_type_proto_depIdxs = nil
}
