// Code generated by protoc-gen-meshgo. DO NOT EDIT.
// source: meshtrade/compliance/client/v1/service.proto
package client_v1

import (
	context "context"
	sync "sync"
	testing "testing"
)

// Ensure that MockClientService implements the ClientServiceClientInterface interface
var _ ClientServiceClientInterface = &MockClientService{}

// Ensure that MockClientService implements the ClientService interface
var _ ClientService = &MockClientService{}

// MockClientService is a mock implementation of the ClientServiceClientInterface interface.
type MockClientService struct {
	mutex                         sync.Mutex
	T                             *testing.T
	GroupValue                    string
	CreateClientFunc              func(t *testing.T, m *MockClientService, ctx context.Context, request *CreateClientRequest) (*Client, error)
	CreateClientFuncInvocations   int
	GetClientFunc                 func(t *testing.T, m *MockClientService, ctx context.Context, request *GetClientRequest) (*Client, error)
	GetClientFuncInvocations      int
	GetGroupClientFunc            func(t *testing.T, m *MockClientService, ctx context.Context, request *GetGroupClientRequest) (*Client, error)
	GetGroupClientFuncInvocations int
	ListClientsFunc               func(t *testing.T, m *MockClientService, ctx context.Context, request *ListClientsRequest) (*ListClientsResponse, error)
	ListClientsFuncInvocations    int
}

// Close is a no-op for the mock implementation.
func (m *MockClientService) Close() error {
	return nil
}

// Group returns the mock's configured group value.
func (m *MockClientService) Group() string {
	return m.GroupValue
}

// WithGroup returns a shallow copy of the mock with the given group value.
func (m *MockClientService) WithGroup(group string) ClientServiceClientInterface {
	return &MockClientService{
		T:                  m.T,
		GroupValue:         group,
		CreateClientFunc:   m.CreateClientFunc,
		GetClientFunc:      m.GetClientFunc,
		GetGroupClientFunc: m.GetGroupClientFunc,
		ListClientsFunc:    m.ListClientsFunc,
	}
}

func (m *MockClientService) CreateClient(ctx context.Context, request *CreateClientRequest) (*Client, error) {
	m.mutex.Lock()
	m.CreateClientFuncInvocations++
	m.mutex.Unlock()
	if m.CreateClientFunc == nil {
		return nil, nil
	}
	return m.CreateClientFunc(m.T, m, ctx, request)
}

func (m *MockClientService) GetClient(ctx context.Context, request *GetClientRequest) (*Client, error) {
	m.mutex.Lock()
	m.GetClientFuncInvocations++
	m.mutex.Unlock()
	if m.GetClientFunc == nil {
		return nil, nil
	}
	return m.GetClientFunc(m.T, m, ctx, request)
}

func (m *MockClientService) GetGroupClient(ctx context.Context, request *GetGroupClientRequest) (*Client, error) {
	m.mutex.Lock()
	m.GetGroupClientFuncInvocations++
	m.mutex.Unlock()
	if m.GetGroupClientFunc == nil {
		return nil, nil
	}
	return m.GetGroupClientFunc(m.T, m, ctx, request)
}

func (m *MockClientService) ListClients(ctx context.Context, request *ListClientsRequest) (*ListClientsResponse, error) {
	m.mutex.Lock()
	m.ListClientsFuncInvocations++
	m.mutex.Unlock()
	if m.ListClientsFunc == nil {
		return nil, nil
	}
	return m.ListClientsFunc(m.T, m, ctx, request)
}
