// Code generated by protoc-gen-meshgo. DO NOT EDIT.
// source: meshtrade/compliance/client/v1/service.proto
package clientv1

import (
	context "context"
	grpc "github.com/meshtrade/api/go/grpc"
	config "github.com/meshtrade/api/go/grpc/config"
)

// ClientServiceClientInterface is a gRPC service for the ClientService service.
// It combines the service interface with resource management capabilities using
// the common BaseGRPCClient for consistent authentication, timeouts, and tracing.
//
// Example usage:
//
//	service, err := NewClientService(
//		config.WithAPIKey("your-api-key"),
//		config.WithGroup("groups/your-group-id"),
//		config.WithTimeout(30 * time.Second),
//	)
//	if err != nil {
//		log.Fatal(err)
//	}
//	defer service.Close()
type ClientServiceClientInterface interface {
	ClientService
	grpc.GRPCClient
}

// clientService is the internal implementation of the ClientServiceClientInterface interface.
// It embeds BaseGRPCClient to provide all common gRPC functionality.
type clientService struct {
	*grpc.BaseGRPCClient[ClientServiceClient]
}

// ensure clientService implements the ClientServiceClientInterface interface
var _ ClientServiceClientInterface = &clientService{}

// NewClientService creates a new gRPC service for the ClientService service.
// The service uses the common BaseGRPCClient for all functionality including
// connection management, authentication, timeouts, and distributed tracing.
//
// Parameters:
//   - opts: Functional options to configure the client
//
// Returns:
//   - ClientServiceClientInterface: Configured service instance
//   - error: Configuration or connection error
func NewClientService(opts ...config.ServiceOption) (ClientServiceClientInterface, error) {
	base, err := grpc.NewBaseGRPCClient(
		ClientServiceServiceProviderName,
		NewClientServiceClient,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return &clientService{BaseGRPCClient: base}, nil
}

// CreateClient executes the CreateClient RPC method with automatic
// timeout handling, distributed tracing, and authentication.
func (s *clientService) CreateClient(ctx context.Context, request *CreateClientRequest) (*Client, error) {
	return grpc.Execute(s.Executor(), ctx, "CreateClient", func(ctx context.Context) (*Client, error) {
		return s.GrpcClient().CreateClient(ctx, request)
	})
}

// GetClient executes the GetClient RPC method with automatic
// timeout handling, distributed tracing, and authentication.
func (s *clientService) GetClient(ctx context.Context, request *GetClientRequest) (*Client, error) {
	return grpc.Execute(s.Executor(), ctx, "GetClient", func(ctx context.Context) (*Client, error) {
		return s.GrpcClient().GetClient(ctx, request)
	})
}

// ListClients executes the ListClients RPC method with automatic
// timeout handling, distributed tracing, and authentication.
func (s *clientService) ListClients(ctx context.Context, request *ListClientsRequest) (*ListClientsResponse, error) {
	return grpc.Execute(s.Executor(), ctx, "ListClients", func(ctx context.Context) (*ListClientsResponse, error) {
		return s.GrpcClient().ListClients(ctx, request)
	})
}
