// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: meshtrade/compliance/client/v1/service.proto

package clientv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRequest is the message used to request a single client resource.
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique resource name of the client to be retrieved.
	// The name serves as the primary identifier for the client resource.
	// Format: "clients/{client_id}"
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_meshtrade_compliance_client_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_compliance_client_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_compliance_client_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetResponse contains the client resource requested.
type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The client resource object containing the full compliance profile.
	Client        *Client `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_meshtrade_compliance_client_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_compliance_client_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_meshtrade_compliance_client_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

// ListRequest is the message used to request a list of client resources.
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_meshtrade_compliance_client_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_compliance_client_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_compliance_client_v1_service_proto_rawDescGZIP(), []int{2}
}

// ListResponse contains a list of client resources.
type ListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A repeated field containing the client resource objects.
	Client        []*Client `protobuf:"bytes,1,rep,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_meshtrade_compliance_client_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_compliance_client_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_meshtrade_compliance_client_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListResponse) GetClient() []*Client {
	if x != nil {
		return x.Client
	}
	return nil
}

var File_meshtrade_compliance_client_v1_service_proto protoreflect.FileDescriptor

const file_meshtrade_compliance_client_v1_service_proto_rawDesc = "" +
	"\n" +
	",meshtrade/compliance/client/v1/service.proto\x12\x1emeshtrade.compliance.client.v1\x1a+meshtrade/compliance/client/v1/client.proto\" \n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"M\n" +
	"\vGetResponse\x12>\n" +
	"\x06client\x18\x01 \x01(\v2&.meshtrade.compliance.client.v1.ClientR\x06client\"\r\n" +
	"\vListRequest\"N\n" +
	"\fListResponse\x12>\n" +
	"\x06client\x18\x01 \x03(\v2&.meshtrade.compliance.client.v1.ClientR\x06client2\xcc\x01\n" +
	"\aService\x12^\n" +
	"\x03Get\x12*.meshtrade.compliance.client.v1.GetRequest\x1a+.meshtrade.compliance.client.v1.GetResponse\x12a\n" +
	"\x04List\x12+.meshtrade.compliance.client.v1.ListRequest\x1a,.meshtrade.compliance.client.v1.ListResponseB;Z9github.com/meshtrade/api/go/compliance/client/v1;clientv1b\x06proto3"

var (
	file_meshtrade_compliance_client_v1_service_proto_rawDescOnce sync.Once
	file_meshtrade_compliance_client_v1_service_proto_rawDescData []byte
)

func file_meshtrade_compliance_client_v1_service_proto_rawDescGZIP() []byte {
	file_meshtrade_compliance_client_v1_service_proto_rawDescOnce.Do(func() {
		file_meshtrade_compliance_client_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshtrade_compliance_client_v1_service_proto_rawDesc), len(file_meshtrade_compliance_client_v1_service_proto_rawDesc)))
	})
	return file_meshtrade_compliance_client_v1_service_proto_rawDescData
}

var file_meshtrade_compliance_client_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_meshtrade_compliance_client_v1_service_proto_goTypes = []any{
	(*GetRequest)(nil),   // 0: meshtrade.compliance.client.v1.GetRequest
	(*GetResponse)(nil),  // 1: meshtrade.compliance.client.v1.GetResponse
	(*ListRequest)(nil),  // 2: meshtrade.compliance.client.v1.ListRequest
	(*ListResponse)(nil), // 3: meshtrade.compliance.client.v1.ListResponse
	(*Client)(nil),       // 4: meshtrade.compliance.client.v1.Client
}
var file_meshtrade_compliance_client_v1_service_proto_depIdxs = []int32{
	4, // 0: meshtrade.compliance.client.v1.GetResponse.client:type_name -> meshtrade.compliance.client.v1.Client
	4, // 1: meshtrade.compliance.client.v1.ListResponse.client:type_name -> meshtrade.compliance.client.v1.Client
	0, // 2: meshtrade.compliance.client.v1.Service.Get:input_type -> meshtrade.compliance.client.v1.GetRequest
	2, // 3: meshtrade.compliance.client.v1.Service.List:input_type -> meshtrade.compliance.client.v1.ListRequest
	1, // 4: meshtrade.compliance.client.v1.Service.Get:output_type -> meshtrade.compliance.client.v1.GetResponse
	3, // 5: meshtrade.compliance.client.v1.Service.List:output_type -> meshtrade.compliance.client.v1.ListResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_meshtrade_compliance_client_v1_service_proto_init() }
func file_meshtrade_compliance_client_v1_service_proto_init() {
	if File_meshtrade_compliance_client_v1_service_proto != nil {
		return
	}
	file_meshtrade_compliance_client_v1_client_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshtrade_compliance_client_v1_service_proto_rawDesc), len(file_meshtrade_compliance_client_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meshtrade_compliance_client_v1_service_proto_goTypes,
		DependencyIndexes: file_meshtrade_compliance_client_v1_service_proto_depIdxs,
		MessageInfos:      file_meshtrade_compliance_client_v1_service_proto_msgTypes,
	}.Build()
	File_meshtrade_compliance_client_v1_service_proto = out.File
	file_meshtrade_compliance_client_v1_service_proto_goTypes = nil
	file_meshtrade_compliance_client_v1_service_proto_depIdxs = nil
}
