// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: meshtrade/trading/limit_order/v1/limit_order.proto

package limit_order_v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/meshtrade/api/go/type/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LimitOrderSide represents the direction of a limit order.
type LimitOrderSide int32

const (
	// Unspecified side (invalid for creation).
	LimitOrderSide_LIMIT_ORDER_SIDE_UNSPECIFIED LimitOrderSide = 0
	// Buy order.
	LimitOrderSide_LIMIT_ORDER_SIDE_BUY LimitOrderSide = 1
	// Sell order.
	LimitOrderSide_LIMIT_ORDER_SIDE_SELL LimitOrderSide = 2
)

// Enum value maps for LimitOrderSide.
var (
	LimitOrderSide_name = map[int32]string{
		0: "LIMIT_ORDER_SIDE_UNSPECIFIED",
		1: "LIMIT_ORDER_SIDE_BUY",
		2: "LIMIT_ORDER_SIDE_SELL",
	}
	LimitOrderSide_value = map[string]int32{
		"LIMIT_ORDER_SIDE_UNSPECIFIED": 0,
		"LIMIT_ORDER_SIDE_BUY":         1,
		"LIMIT_ORDER_SIDE_SELL":        2,
	}
)

func (x LimitOrderSide) Enum() *LimitOrderSide {
	p := new(LimitOrderSide)
	*p = x
	return p
}

func (x LimitOrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LimitOrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtrade_trading_limit_order_v1_limit_order_proto_enumTypes[0].Descriptor()
}

func (LimitOrderSide) Type() protoreflect.EnumType {
	return &file_meshtrade_trading_limit_order_v1_limit_order_proto_enumTypes[0]
}

func (x LimitOrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LimitOrderSide.Descriptor instead.
func (LimitOrderSide) EnumDescriptor() ([]byte, []int) {
	return file_meshtrade_trading_limit_order_v1_limit_order_proto_rawDescGZIP(), []int{0}
}

// LimitOrderState represents the current life-cycle state of a limit order.
type LimitOrderState int32

const (
	// Unspecified status.
	LimitOrderState_LIMIT_ORDER_STATUS_UNSPECIFIED LimitOrderState = 0
	// Submission transaction in progress.
	LimitOrderState_LIMIT_ORDER_STATUS_SUBMISSION_IN_PROGRESS LimitOrderState = 1
	// Submission failed.
	LimitOrderState_LIMIT_ORDER_STATUS_SUBMISSION_FAILED LimitOrderState = 2
	// Order is open on the ledger.
	LimitOrderState_LIMIT_ORDER_STATUS_OPEN LimitOrderState = 3
	// Completion in progress.
	LimitOrderState_LIMIT_ORDER_STATUS_COMPLETE_IN_PROGRESS LimitOrderState = 4
	// Order completed (fully filled).
	LimitOrderState_LIMIT_ORDER_STATUS_COMPLETE LimitOrderState = 5
	// Cancellation in progress.
	LimitOrderState_LIMIT_ORDER_STATUS_CANCELLATION_IN_PROGRESS LimitOrderState = 6
	// Order cancelled.
	LimitOrderState_LIMIT_ORDER_STATUS_CANCELLED LimitOrderState = 7
)

// Enum value maps for LimitOrderState.
var (
	LimitOrderState_name = map[int32]string{
		0: "LIMIT_ORDER_STATUS_UNSPECIFIED",
		1: "LIMIT_ORDER_STATUS_SUBMISSION_IN_PROGRESS",
		2: "LIMIT_ORDER_STATUS_SUBMISSION_FAILED",
		3: "LIMIT_ORDER_STATUS_OPEN",
		4: "LIMIT_ORDER_STATUS_COMPLETE_IN_PROGRESS",
		5: "LIMIT_ORDER_STATUS_COMPLETE",
		6: "LIMIT_ORDER_STATUS_CANCELLATION_IN_PROGRESS",
		7: "LIMIT_ORDER_STATUS_CANCELLED",
	}
	LimitOrderState_value = map[string]int32{
		"LIMIT_ORDER_STATUS_UNSPECIFIED":              0,
		"LIMIT_ORDER_STATUS_SUBMISSION_IN_PROGRESS":   1,
		"LIMIT_ORDER_STATUS_SUBMISSION_FAILED":        2,
		"LIMIT_ORDER_STATUS_OPEN":                     3,
		"LIMIT_ORDER_STATUS_COMPLETE_IN_PROGRESS":     4,
		"LIMIT_ORDER_STATUS_COMPLETE":                 5,
		"LIMIT_ORDER_STATUS_CANCELLATION_IN_PROGRESS": 6,
		"LIMIT_ORDER_STATUS_CANCELLED":                7,
	}
)

func (x LimitOrderState) Enum() *LimitOrderState {
	p := new(LimitOrderState)
	*p = x
	return p
}

func (x LimitOrderState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LimitOrderState) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtrade_trading_limit_order_v1_limit_order_proto_enumTypes[1].Descriptor()
}

func (LimitOrderState) Type() protoreflect.EnumType {
	return &file_meshtrade_trading_limit_order_v1_limit_order_proto_enumTypes[1]
}

func (x LimitOrderState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LimitOrderState.Descriptor instead.
func (LimitOrderState) EnumDescriptor() ([]byte, []int) {
	return file_meshtrade_trading_limit_order_v1_limit_order_proto_rawDescGZIP(), []int{1}
}

// LimitOrder resource representing a limit order for trading on the Mesh platform.
//
// Limit orders enable traders to specify price and quantity for buying or selling
// instruments on supported ledgers. Each order is owned by a group and associated
// with a specific account.
type LimitOrder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique resource name for the limit order.
	// Format: limit_orders/{ULIDv2}.
	// This field is system-generated and immutable upon creation.
	// Any value provided on creation is ignored.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The resource name of the parent group that owns this limit order.
	// This field is required on creation and establishes the direct ownership link.
	// Format: groups/{ULIDv2}.
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// Ownership hiearchy of groups that have access to this resource in the format groups/{group_id}.
	// System set on creation.
	Owners []string `protobuf:"bytes,3,rep,name=owners,proto3" json:"owners,omitempty"`
	// The account associated with this limit order.
	// Format: accounts/{ULIDv2}.
	// This field is required on creation.
	Account string `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`
	// External reference for client-side tracking and correlation.
	// This field allows clients to associate orders with their own identifiers.
	//
	// If specified, must be unique within the scope of limit orders owned by
	// this owner. The Mesh system enforces this constraint to ensure reliable
	// lookups via GetLimitOrderByExternalReference.
	ExternalReference string `protobuf:"bytes,6,opt,name=external_reference,json=externalReference,proto3" json:"external_reference,omitempty"`
	// Order side indicating buy or sell.
	// This field is required on creation.
	Side LimitOrderSide `protobuf:"varint,7,opt,name=side,proto3,enum=meshtrade.trading.limit_order.v1.LimitOrderSide" json:"side,omitempty"`
	// Limit price for the order.
	// This field is required on creation.
	LimitPrice *v1.Amount `protobuf:"bytes,8,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`
	// Order quantity.
	// This field is required on creation.
	Quantity *v1.Amount `protobuf:"bytes,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Fill price from live ledger data.
	// Calculated as the volume weighted average price (VWAP) of all trades
	// that filled this order. This value is computed in real-time from ledger
	// data and becomes final when the order is marked complete.
	//
	// Only populated when live_ledger_data=true in request.
	FillPrice *v1.Amount `protobuf:"bytes,10,opt,name=fill_price,json=fillPrice,proto3" json:"fill_price,omitempty"`
	// Filled quantity from live ledger data.
	// Represents the total amount of the order that has been filled on the ledger.
	// This value is computed in real-time from ledger data and becomes final
	// when the order is marked complete.
	//
	// Only populated when live_ledger_data=true in request.
	FilledQuantity *v1.Amount `protobuf:"bytes,10,opt,name=filled_quantity,json=filledQuantity,proto3" json:"filled_quantity,omitempty"`
	// Limit Order life cycle state.
	State         LimitOrderState `protobuf:"varint,11,opt,name=state,proto3,enum=meshtrade.trading.limit_order.v1.LimitOrderState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LimitOrder) Reset() {
	*x = LimitOrder{}
	mi := &file_meshtrade_trading_limit_order_v1_limit_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LimitOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitOrder) ProtoMessage() {}

func (x *LimitOrder) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_trading_limit_order_v1_limit_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitOrder.ProtoReflect.Descriptor instead.
func (*LimitOrder) Descriptor() ([]byte, []int) {
	return file_meshtrade_trading_limit_order_v1_limit_order_proto_rawDescGZIP(), []int{0}
}

func (x *LimitOrder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LimitOrder) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *LimitOrder) GetOwners() []string {
	if x != nil {
		return x.Owners
	}
	return nil
}

func (x *LimitOrder) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LimitOrder) GetExternalReference() string {
	if x != nil {
		return x.ExternalReference
	}
	return ""
}

func (x *LimitOrder) GetSide() LimitOrderSide {
	if x != nil {
		return x.Side
	}
	return LimitOrderSide_LIMIT_ORDER_SIDE_UNSPECIFIED
}

func (x *LimitOrder) GetLimitPrice() *v1.Amount {
	if x != nil {
		return x.LimitPrice
	}
	return nil
}

func (x *LimitOrder) GetQuantity() *v1.Amount {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *LimitOrder) GetFillPrice() *v1.Amount {
	if x != nil {
		return x.FillPrice
	}
	return nil
}

func (x *LimitOrder) GetFilledQuantity() *v1.Amount {
	if x != nil {
		return x.FilledQuantity
	}
	return nil
}

func (x *LimitOrder) GetState() LimitOrderState {
	if x != nil {
		return x.State
	}
	return LimitOrderState_LIMIT_ORDER_STATUS_UNSPECIFIED
}

var File_meshtrade_trading_limit_order_v1_limit_order_proto protoreflect.FileDescriptor

const file_meshtrade_trading_limit_order_v1_limit_order_proto_rawDesc = "" +
	"\n" +
	"2meshtrade/trading/limit_order/v1/limit_order.proto\x12 meshtrade.trading.limit_order.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1emeshtrade/type/v1/amount.proto\"\xee\x06\n" +
	"\n" +
	"LimitOrder\x12\xc8\x01\n" +
	"\x04name\x18\x01 \x01(\tB\xb3\x01\xbaH\xaf\x01\xba\x01\xab\x01\n" +
	"\x14name.format.optional\x129name must be empty or in the format limit_orders/{ULIDv2}\x1aXsize(this) == 0 || this.matches('^limit_orders/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$')R\x04name\x12R\n" +
	"\x05owner\x18\x02 \x01(\tB<\xbaH9\xc8\x01\x01r42/^groups/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$\x98\x01!R\x05owner\x12V\n" +
	"\x06owners\x18\x03 \x03(\tB>\xbaH;\x92\x018\"6r42/^groups/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$\x98\x01!R\x06owners\x12X\n" +
	"\aaccount\x18\x05 \x01(\tB>\xbaH;\xc8\x01\x01r621^accounts/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$\x98\x01#R\aaccount\x127\n" +
	"\x12external_reference\x18\x06 \x01(\tB\b\xbaH\x05r\x03\x18\xc8\x01R\x11externalReference\x12P\n" +
	"\x04side\x18\a \x01(\x0e20.meshtrade.trading.limit_order.v1.LimitOrderSideB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x04side\x12B\n" +
	"\vlimit_price\x18\b \x01(\v2\x19.meshtrade.type.v1.AmountB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"limitPrice\x12=\n" +
	"\bquantity\x18\t \x01(\v2\x19.meshtrade.type.v1.AmountB\x06\xbaH\x03\xc8\x01\x01R\bquantity\x128\n" +
	"\n" +
	"fill_price\x18\t \x01(\v2\x19.meshtrade.type.v1.AmountR\tfillPrice\x12B\n" +
	"\x0ffilled_quantity\x18\n" +
	" \x01(\v2\x19.meshtrade.type.v1.AmountR\x0efilledQuantity\x12G\n" +
	"\x05state\x18\v \x01(\x0e21.meshtrade.trading.limit_order.v1.LimitOrderStateR\x05stateJ\x04\b\x04\x10\x05R\fdisplay_name*g\n" +
	"\x0eLimitOrderSide\x12 \n" +
	"\x1cLIMIT_ORDER_SIDE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14LIMIT_ORDER_SIDE_BUY\x10\x01\x12\x19\n" +
	"\x15LIMIT_ORDER_SIDE_SELL\x10\x02*\xcc\x02\n" +
	"\x0fLimitOrderState\x12\"\n" +
	"\x1eLIMIT_ORDER_STATUS_UNSPECIFIED\x10\x00\x12-\n" +
	")LIMIT_ORDER_STATUS_SUBMISSION_IN_PROGRESS\x10\x01\x12(\n" +
	"$LIMIT_ORDER_STATUS_SUBMISSION_FAILED\x10\x02\x12\x1b\n" +
	"\x17LIMIT_ORDER_STATUS_OPEN\x10\x03\x12+\n" +
	"'LIMIT_ORDER_STATUS_COMPLETE_IN_PROGRESS\x10\x04\x12\x1f\n" +
	"\x1bLIMIT_ORDER_STATUS_COMPLETE\x10\x05\x12/\n" +
	"+LIMIT_ORDER_STATUS_CANCELLATION_IN_PROGRESS\x10\x06\x12 \n" +
	"\x1cLIMIT_ORDER_STATUS_CANCELLED\x10\aBl\n" +
	"'co.meshtrade.api.trading.limit_order.v1ZAgithub.com/meshtrade/api/go/trading/limit_order/v1;limit_order_v1b\x06proto3"

var (
	file_meshtrade_trading_limit_order_v1_limit_order_proto_rawDescOnce sync.Once
	file_meshtrade_trading_limit_order_v1_limit_order_proto_rawDescData []byte
)

func file_meshtrade_trading_limit_order_v1_limit_order_proto_rawDescGZIP() []byte {
	file_meshtrade_trading_limit_order_v1_limit_order_proto_rawDescOnce.Do(func() {
		file_meshtrade_trading_limit_order_v1_limit_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshtrade_trading_limit_order_v1_limit_order_proto_rawDesc), len(file_meshtrade_trading_limit_order_v1_limit_order_proto_rawDesc)))
	})
	return file_meshtrade_trading_limit_order_v1_limit_order_proto_rawDescData
}

var file_meshtrade_trading_limit_order_v1_limit_order_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_meshtrade_trading_limit_order_v1_limit_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meshtrade_trading_limit_order_v1_limit_order_proto_goTypes = []any{
	(LimitOrderSide)(0),  // 0: meshtrade.trading.limit_order.v1.LimitOrderSide
	(LimitOrderState)(0), // 1: meshtrade.trading.limit_order.v1.LimitOrderState
	(*LimitOrder)(nil),   // 2: meshtrade.trading.limit_order.v1.LimitOrder
	(*v1.Amount)(nil),    // 3: meshtrade.type.v1.Amount
}
var file_meshtrade_trading_limit_order_v1_limit_order_proto_depIdxs = []int32{
	0, // 0: meshtrade.trading.limit_order.v1.LimitOrder.side:type_name -> meshtrade.trading.limit_order.v1.LimitOrderSide
	3, // 1: meshtrade.trading.limit_order.v1.LimitOrder.limit_price:type_name -> meshtrade.type.v1.Amount
	3, // 2: meshtrade.trading.limit_order.v1.LimitOrder.quantity:type_name -> meshtrade.type.v1.Amount
	3, // 3: meshtrade.trading.limit_order.v1.LimitOrder.fill_price:type_name -> meshtrade.type.v1.Amount
	3, // 4: meshtrade.trading.limit_order.v1.LimitOrder.filled_quantity:type_name -> meshtrade.type.v1.Amount
	1, // 5: meshtrade.trading.limit_order.v1.LimitOrder.state:type_name -> meshtrade.trading.limit_order.v1.LimitOrderState
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_meshtrade_trading_limit_order_v1_limit_order_proto_init() }
func file_meshtrade_trading_limit_order_v1_limit_order_proto_init() {
	if File_meshtrade_trading_limit_order_v1_limit_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshtrade_trading_limit_order_v1_limit_order_proto_rawDesc), len(file_meshtrade_trading_limit_order_v1_limit_order_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshtrade_trading_limit_order_v1_limit_order_proto_goTypes,
		DependencyIndexes: file_meshtrade_trading_limit_order_v1_limit_order_proto_depIdxs,
		EnumInfos:         file_meshtrade_trading_limit_order_v1_limit_order_proto_enumTypes,
		MessageInfos:      file_meshtrade_trading_limit_order_v1_limit_order_proto_msgTypes,
	}.Build()
	File_meshtrade_trading_limit_order_v1_limit_order_proto = out.File
	file_meshtrade_trading_limit_order_v1_limit_order_proto_goTypes = nil
	file_meshtrade_trading_limit_order_v1_limit_order_proto_depIdxs = nil
}
