# Site settings
title: My API Documentation
description: "API documentation for my awesome project."
remote_theme: just-the-docs/just-the-docs

# Optional: Enable search
search_enabled: true

# Optional: Add a link to your repository
aux_links:
  "View on GitHub": "https://github.com/your-username/your-repo" # Change this