// Code generated by protoc-gen-meshgo. DO NOT EDIT.
// source: api/proto/auth/service.proto
package auth

import (
	role "github.com/meshtrade/api/go/iam/role"
)

var (
	// LoginWithFirebaseTokenPermission provides permission to call the LoginWithFirebaseToken method on the Service service provider
	LoginWithFirebaseTokenPermission = &role.Permission{
		ServiceProvider: ServiceServiceProviderName,
		Service:         "LoginWithFirebaseToken",
		Description:     "Provides permission to call the Service.LoginWithFirebaseToken method",
	}

	// ServiceReaderRole contains read only service permissions for the Service
	ServiceReaderRole = role.Role{
		Name:        "ServiceReader",
		Permissions: []*role.Permission{},
	}

	// ServiceAdminRole provides access to all methods on the Service service provider.
	ServiceAdminRole = role.Role{
		Name: "ServiceAdmin",
		Permissions: []*role.Permission{
			LoginWithFirebaseTokenPermission,
		},
	}
)
