// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: meshtrade/iam/user_profile/v1/service.proto

package user_profile_v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/meshtrade/api/go/option/method_options/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for GetUserProfileByUser.
//
// Retrieves a user profile by specifying the associated user resource name.
type GetUserProfileByUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the user whose profile should be retrieved.
	// Format: users/{ULIDv2}.
	// This field is required.
	User          string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileByUserRequest) Reset() {
	*x = GetUserProfileByUserRequest{}
	mi := &file_meshtrade_iam_user_profile_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileByUserRequest) ProtoMessage() {}

func (x *GetUserProfileByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_user_profile_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileByUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileByUserRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_user_profile_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserProfileByUserRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

// Request message for UpdateUserProfile.
//
// Updates an existing user profile. Only the fields provided
// in the user_profile will be updated; omitted fields remain unchanged.
type UpdateUserProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user profile with updated values.
	// The name field must be set to identify which profile to update.
	// Only provided fields will be modified.
	UserProfile   *UserProfile `protobuf:"bytes,1,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileRequest) Reset() {
	*x = UpdateUserProfileRequest{}
	mi := &file_meshtrade_iam_user_profile_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileRequest) ProtoMessage() {}

func (x *UpdateUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_user_profile_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_user_profile_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateUserProfileRequest) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

// Request message for GetUserProfile.
//
// Retrieves a specific user profile by its resource name.
type GetUserProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the user profile to retrieve.
	// Format: iam/user_profiles/{ULIDv2}.
	// This field is required.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_meshtrade_iam_user_profile_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_user_profile_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_user_profile_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request message for ListUserProfiles.
//
// Lists all user profiles accessible to the caller based on
// their role permissions and group ownership.
type ListUserProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserProfilesRequest) Reset() {
	*x = ListUserProfilesRequest{}
	mi := &file_meshtrade_iam_user_profile_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserProfilesRequest) ProtoMessage() {}

func (x *ListUserProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_user_profile_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListUserProfilesRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_user_profile_v1_service_proto_rawDescGZIP(), []int{3}
}

// Response message for ListUserProfiles.
//
// Contains the collection of user profiles accessible to the caller.
type ListUserProfilesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of user profiles.
	// Ordered by creation time, with most recent first.
	UserProfiles  []*UserProfile `protobuf:"bytes,1,rep,name=user_profiles,json=userProfiles,proto3" json:"user_profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserProfilesResponse) Reset() {
	*x = ListUserProfilesResponse{}
	mi := &file_meshtrade_iam_user_profile_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserProfilesResponse) ProtoMessage() {}

func (x *ListUserProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_user_profile_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListUserProfilesResponse) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_user_profile_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListUserProfilesResponse) GetUserProfiles() []*UserProfile {
	if x != nil {
		return x.UserProfiles
	}
	return nil
}

// Request message for GetUserProfilePictureUploadUrl.
//
// Requests a presigned URL for uploading a profile picture for
// the specified user profile.
type GetUserProfilePictureUploadUrlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the user profile to upload a picture for.
	// Format: iam/user_profiles/{ULIDv2}.
	// This field is required.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfilePictureUploadUrlRequest) Reset() {
	*x = GetUserProfilePictureUploadUrlRequest{}
	mi := &file_meshtrade_iam_user_profile_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfilePictureUploadUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfilePictureUploadUrlRequest) ProtoMessage() {}

func (x *GetUserProfilePictureUploadUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_user_profile_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfilePictureUploadUrlRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfilePictureUploadUrlRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_user_profile_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserProfilePictureUploadUrlRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Response message for GetUserProfilePictureUploadUrl.
//
// Contains the presigned upload URL and its expiration time.
type GetUserProfilePictureUploadUrlResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The presigned URL for uploading the profile picture.
	// This URL should be used immediately with a PUT request to upload the image.
	UploadUrl string `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	// The timestamp when the upload URL expires.
	// After this time, the URL will no longer be valid for uploading.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfilePictureUploadUrlResponse) Reset() {
	*x = GetUserProfilePictureUploadUrlResponse{}
	mi := &file_meshtrade_iam_user_profile_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfilePictureUploadUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfilePictureUploadUrlResponse) ProtoMessage() {}

func (x *GetUserProfilePictureUploadUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_user_profile_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfilePictureUploadUrlResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfilePictureUploadUrlResponse) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_user_profile_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserProfilePictureUploadUrlResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GetUserProfilePictureUploadUrlResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// Request message for SearchUserProfiles.
//
// Searches user profiles by first name or last name substring matching.
type SearchUserProfilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional substring to match against user profile first names.
	// The search is case-insensitive.
	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// Optional substring to match against user profile last names.
	// The search is case-insensitive.
	LastName string `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Optional list of user resource names to filter by.
	// Format: users/{ULIDv2}.
	// When provided, only profiles associated with the specified users are returned.
	Users         []string `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserProfilesRequest) Reset() {
	*x = SearchUserProfilesRequest{}
	mi := &file_meshtrade_iam_user_profile_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserProfilesRequest) ProtoMessage() {}

func (x *SearchUserProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_user_profile_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserProfilesRequest.ProtoReflect.Descriptor instead.
func (*SearchUserProfilesRequest) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_user_profile_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *SearchUserProfilesRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *SearchUserProfilesRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *SearchUserProfilesRequest) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

// Response message for SearchUserProfiles.
//
// Contains the collection of user profiles matching the search criteria.
type SearchUserProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserProfiles  []*UserProfile         `protobuf:"bytes,1,rep,name=user_profiles,json=userProfiles,proto3" json:"user_profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserProfilesResponse) Reset() {
	*x = SearchUserProfilesResponse{}
	mi := &file_meshtrade_iam_user_profile_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserProfilesResponse) ProtoMessage() {}

func (x *SearchUserProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_user_profile_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserProfilesResponse.ProtoReflect.Descriptor instead.
func (*SearchUserProfilesResponse) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_user_profile_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *SearchUserProfilesResponse) GetUserProfiles() []*UserProfile {
	if x != nil {
		return x.UserProfiles
	}
	return nil
}

var File_meshtrade_iam_user_profile_v1_service_proto protoreflect.FileDescriptor

const file_meshtrade_iam_user_profile_v1_service_proto_rawDesc = "" +
	"\n" +
	"+meshtrade/iam/user_profile/v1/service.proto\x12\x1dmeshtrade.iam.user_profile.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a0meshtrade/iam/user_profile/v1/user_profile.proto\x1a7meshtrade/option/method_options/v1/method_options.proto\x1a<meshtrade/iam/user_profile/v1/notification_preferences.proto\"\xfe\x02\n" +
	"\x1bGetUserProfileByUserRequest\x12\xde\x02\n" +
	"\x04user\x18\x01 \x01(\tB\xc9\x02\xbaH\xc5\x02\xba\x01V\n" +
	"\ruser.required\x125user is required and must be in format users/{ULIDv2}\x1a\x0esize(this) > 0\xba\x01\xb1\x01\n" +
	"\vuser.format\x12bname must be in format users/{ULIDv2} where ulidv2 is exactly 26 uppercase alphanumeric characters\x1a>this.matches('^users/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$')\xc8\x01\x01r2\x10\x012.^users/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$R\x04user\"q\n" +
	"\x18UpdateUserProfileRequest\x12U\n" +
	"\fuser_profile\x18\x01 \x01(\v2*.meshtrade.iam.user_profile.v1.UserProfileB\x06\xbaH\x03\xc8\x01\x01R\vuserProfile\"\xa8\x03\n" +
	"\x15GetUserProfileRequest\x12\x8e\x03\n" +
	"\x04name\x18\x01 \x01(\tB\xf9\x02\xbaH\xf5\x02\xba\x01b\n" +
	"\rname.required\x12Aname is required and must be in format iam/user_profiles/{ULIDv2}\x1a\x0esize(this) > 0\xba\x01\xc9\x01\n" +
	"\vname.format\x12nname must be in format iam/user_profiles/{ULIDv2} where ulidv2 is exactly 26 uppercase alphanumeric characters\x1aJthis.matches('^iam/user_profiles/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$')\xc8\x01\x01r>\x10\x012:^iam/user_profiles/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$R\x04name\"\x19\n" +
	"\x17ListUserProfilesRequest\"k\n" +
	"\x18ListUserProfilesResponse\x12O\n" +
	"\ruser_profiles\x18\x01 \x03(\v2*.meshtrade.iam.user_profile.v1.UserProfileR\fuserProfiles\"\xb8\x03\n" +
	"%GetUserProfilePictureUploadUrlRequest\x12\x8e\x03\n" +
	"\x04name\x18\x01 \x01(\tB\xf9\x02\xbaH\xf5\x02\xba\x01b\n" +
	"\rname.required\x12Aname is required and must be in format iam/user_profiles/{ULIDv2}\x1a\x0esize(this) > 0\xba\x01\xc9\x01\n" +
	"\vname.format\x12nname must be in format iam/user_profiles/{ULIDv2} where ulidv2 is exactly 26 uppercase alphanumeric characters\x1aJthis.matches('^iam/user_profiles/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$')\xc8\x01\x01r>\x10\x012:^iam/user_profiles/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$R\x04name\"\x82\x01\n" +
	"&GetUserProfilePictureUploadUrlResponse\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xbf\x01\n" +
	"\x19SearchUserProfilesRequest\x12'\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\tfirstName\x12%\n" +
	"\tlast_name\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\blastName\x12R\n" +
	"\x05users\x18\x03 \x03(\tB<\xbaH9\x92\x016\x10d\"2r02.^users/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$R\x05users\"m\n" +
	"\x1aSearchUserProfilesResponse\x12O\n" +
	"\ruser_profiles\x18\x01 \x03(\v2*.meshtrade.iam.user_profile.v1.UserProfileR\fuserProfiles2\xdf\a\n" +
	"\x12UserProfileService\x12\x8c\x01\n" +
	"\x11UpdateUserProfile\x127.meshtrade.iam.user_profile.v1.UpdateUserProfileRequest\x1a*.meshtrade.iam.user_profile.v1.UserProfile\"\x12\xb2\xb5\x18\x0e\b\x02\x10\x02\x1a\b\xc0\x8d\xb7\x01ȍ\xb7\x01\x12\x8e\x01\n" +
	"\x0eGetUserProfile\x124.meshtrade.iam.user_profile.v1.GetUserProfileRequest\x1a*.meshtrade.iam.user_profile.v1.UserProfile\"\x1a\xb2\xb5\x18\x16\b\x01\x10\x02\x1a\x10\xc0\x8d\xb7\x01\xc1\x8d\xb7\x01ȍ\xb7\x01ɍ\xb7\x01\x12\x9a\x01\n" +
	"\x14GetUserProfileByUser\x12:.meshtrade.iam.user_profile.v1.GetUserProfileByUserRequest\x1a*.meshtrade.iam.user_profile.v1.UserProfile\"\x1a\xb2\xb5\x18\x16\b\x01\x10\x02\x1a\x10\xc0\x8d\xb7\x01\xc1\x8d\xb7\x01ȍ\xb7\x01ɍ\xb7\x01\x12\x9f\x01\n" +
	"\x10ListUserProfiles\x126.meshtrade.iam.user_profile.v1.ListUserProfilesRequest\x1a7.meshtrade.iam.user_profile.v1.ListUserProfilesResponse\"\x1a\xb2\xb5\x18\x16\b\x01\x10\x02\x1a\x10\xc0\x8d\xb7\x01\xc1\x8d\xb7\x01ȍ\xb7\x01ɍ\xb7\x01\x12\xa5\x01\n" +
	"\x12SearchUserProfiles\x128.meshtrade.iam.user_profile.v1.SearchUserProfilesRequest\x1a9.meshtrade.iam.user_profile.v1.SearchUserProfilesResponse\"\x1a\xb2\xb5\x18\x16\b\x01\x10\x02\x1a\x10\xc0\x8d\xb7\x01\xc1\x8d\xb7\x01ȍ\xb7\x01ɍ\xb7\x01\x12\xc1\x01\n" +
	"\x1eGetUserProfilePictureUploadUrl\x12D.meshtrade.iam.user_profile.v1.GetUserProfilePictureUploadUrlRequest\x1aE.meshtrade.iam.user_profile.v1.GetUserProfilePictureUploadUrlResponse\"\x12\xb2\xb5\x18\x0e\b\x01\x10\x02\x1a\b\xc0\x8d\xb7\x01ȍ\xb7\x01Bg\n" +
	"$co.meshtrade.api.iam.user_profile.v1Z?github.com/meshtrade/api/go/iam/user_profile/v1;user_profile_v1b\x06proto3"

var (
	file_meshtrade_iam_user_profile_v1_service_proto_rawDescOnce sync.Once
	file_meshtrade_iam_user_profile_v1_service_proto_rawDescData []byte
)

func file_meshtrade_iam_user_profile_v1_service_proto_rawDescGZIP() []byte {
	file_meshtrade_iam_user_profile_v1_service_proto_rawDescOnce.Do(func() {
		file_meshtrade_iam_user_profile_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshtrade_iam_user_profile_v1_service_proto_rawDesc), len(file_meshtrade_iam_user_profile_v1_service_proto_rawDesc)))
	})
	return file_meshtrade_iam_user_profile_v1_service_proto_rawDescData
}

var file_meshtrade_iam_user_profile_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_meshtrade_iam_user_profile_v1_service_proto_goTypes = []any{
	(*GetUserProfileByUserRequest)(nil),            // 0: meshtrade.iam.user_profile.v1.GetUserProfileByUserRequest
	(*UpdateUserProfileRequest)(nil),               // 1: meshtrade.iam.user_profile.v1.UpdateUserProfileRequest
	(*GetUserProfileRequest)(nil),                  // 2: meshtrade.iam.user_profile.v1.GetUserProfileRequest
	(*ListUserProfilesRequest)(nil),                // 3: meshtrade.iam.user_profile.v1.ListUserProfilesRequest
	(*ListUserProfilesResponse)(nil),               // 4: meshtrade.iam.user_profile.v1.ListUserProfilesResponse
	(*GetUserProfilePictureUploadUrlRequest)(nil),  // 5: meshtrade.iam.user_profile.v1.GetUserProfilePictureUploadUrlRequest
	(*GetUserProfilePictureUploadUrlResponse)(nil), // 6: meshtrade.iam.user_profile.v1.GetUserProfilePictureUploadUrlResponse
	(*SearchUserProfilesRequest)(nil),              // 7: meshtrade.iam.user_profile.v1.SearchUserProfilesRequest
	(*SearchUserProfilesResponse)(nil),             // 8: meshtrade.iam.user_profile.v1.SearchUserProfilesResponse
	(*UserProfile)(nil),                            // 9: meshtrade.iam.user_profile.v1.UserProfile
	(*timestamppb.Timestamp)(nil),                  // 10: google.protobuf.Timestamp
}
var file_meshtrade_iam_user_profile_v1_service_proto_depIdxs = []int32{
	9,  // 0: meshtrade.iam.user_profile.v1.UpdateUserProfileRequest.user_profile:type_name -> meshtrade.iam.user_profile.v1.UserProfile
	9,  // 1: meshtrade.iam.user_profile.v1.ListUserProfilesResponse.user_profiles:type_name -> meshtrade.iam.user_profile.v1.UserProfile
	10, // 2: meshtrade.iam.user_profile.v1.GetUserProfilePictureUploadUrlResponse.expires_at:type_name -> google.protobuf.Timestamp
	9,  // 3: meshtrade.iam.user_profile.v1.SearchUserProfilesResponse.user_profiles:type_name -> meshtrade.iam.user_profile.v1.UserProfile
	1,  // 4: meshtrade.iam.user_profile.v1.UserProfileService.UpdateUserProfile:input_type -> meshtrade.iam.user_profile.v1.UpdateUserProfileRequest
	2,  // 5: meshtrade.iam.user_profile.v1.UserProfileService.GetUserProfile:input_type -> meshtrade.iam.user_profile.v1.GetUserProfileRequest
	0,  // 6: meshtrade.iam.user_profile.v1.UserProfileService.GetUserProfileByUser:input_type -> meshtrade.iam.user_profile.v1.GetUserProfileByUserRequest
	3,  // 7: meshtrade.iam.user_profile.v1.UserProfileService.ListUserProfiles:input_type -> meshtrade.iam.user_profile.v1.ListUserProfilesRequest
	7,  // 8: meshtrade.iam.user_profile.v1.UserProfileService.SearchUserProfiles:input_type -> meshtrade.iam.user_profile.v1.SearchUserProfilesRequest
	5,  // 9: meshtrade.iam.user_profile.v1.UserProfileService.GetUserProfilePictureUploadUrl:input_type -> meshtrade.iam.user_profile.v1.GetUserProfilePictureUploadUrlRequest
	9,  // 10: meshtrade.iam.user_profile.v1.UserProfileService.UpdateUserProfile:output_type -> meshtrade.iam.user_profile.v1.UserProfile
	9,  // 11: meshtrade.iam.user_profile.v1.UserProfileService.GetUserProfile:output_type -> meshtrade.iam.user_profile.v1.UserProfile
	9,  // 12: meshtrade.iam.user_profile.v1.UserProfileService.GetUserProfileByUser:output_type -> meshtrade.iam.user_profile.v1.UserProfile
	4,  // 13: meshtrade.iam.user_profile.v1.UserProfileService.ListUserProfiles:output_type -> meshtrade.iam.user_profile.v1.ListUserProfilesResponse
	8,  // 14: meshtrade.iam.user_profile.v1.UserProfileService.SearchUserProfiles:output_type -> meshtrade.iam.user_profile.v1.SearchUserProfilesResponse
	6,  // 15: meshtrade.iam.user_profile.v1.UserProfileService.GetUserProfilePictureUploadUrl:output_type -> meshtrade.iam.user_profile.v1.GetUserProfilePictureUploadUrlResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_meshtrade_iam_user_profile_v1_service_proto_init() }
func file_meshtrade_iam_user_profile_v1_service_proto_init() {
	if File_meshtrade_iam_user_profile_v1_service_proto != nil {
		return
	}
	file_meshtrade_iam_user_profile_v1_user_profile_proto_init()
	file_meshtrade_iam_user_profile_v1_notification_preferences_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshtrade_iam_user_profile_v1_service_proto_rawDesc), len(file_meshtrade_iam_user_profile_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meshtrade_iam_user_profile_v1_service_proto_goTypes,
		DependencyIndexes: file_meshtrade_iam_user_profile_v1_service_proto_depIdxs,
		MessageInfos:      file_meshtrade_iam_user_profile_v1_service_proto_msgTypes,
	}.Build()
	File_meshtrade_iam_user_profile_v1_service_proto = out.File
	file_meshtrade_iam_user_profile_v1_service_proto_goTypes = nil
	file_meshtrade_iam_user_profile_v1_service_proto_depIdxs = nil
}
