// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: meshtrade/iam/user_profile/v1/user_profile.proto

package user_profile_v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/meshtrade/api/go/type/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A user_profile in the IAM user_profile service.
//
// Each User Profile belongs to a specific user
type UserProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique resource name for the user_profiles.
	// Format: iam/user_profiles/{ULIDv2}.
	// This field is system-generated and immutable upon creation.
	// Any value provided on creation is ignored.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The resource name of the parent group that owns this user_profile.
	// This field is required on creation and establishes the direct ownership link.
	// Format: groups/{ULIDv2}.
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// Ownership hiearchy of groups that have access to this resource in the format groups/{group_id}.
	// System set on creation.
	Owners []string `protobuf:"bytes,3,rep,name=owners,proto3" json:"owners,omitempty"`
	// The resource name of the user associated with this profile.
	// Format: users/{ULIDv2}.
	// This field links the user profile to a specific user resource.
	// This field is required.
	User string `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	// The locale/language preference for this user profile.
	// Format: IETF BCP 47 language tag (e.g., "en", "en-US", "fr-FR", "zh-Hans-CN").
	// Used for internationalization and localization of the user interface.
	// This field is optional but must be a valid BCP 47 tag when provided.
	Locale string `protobuf:"bytes,5,opt,name=locale,proto3" json:"locale,omitempty"`
	// URL to the user's profile picture or avatar image.
	// Should be a valid HTTPS URL pointing to an accessible image resource.
	// Used for displaying user identity in the application interface.
	// This field is optional but must be a valid URI when provided.
	ProfilePictureUrl string `protobuf:"bytes,6,opt,name=profile_picture_url,json=profilePictureUrl,proto3" json:"profile_picture_url,omitempty"`
	// The display name shown for this user in the application.
	// This field is required and represents how the user is identified to others.
	// May be the user's full name, nickname, or preferred identifier.
	DisplayName string `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The preferred currency token for displaying monetary values to this user.
	// Used as the default currency for presenting prices, balances, and trading values.
	// References a token from the meshtrade.type.v1.Token definition.
	DisplayCurrency *v1.Token `protobuf:"bytes,8,opt,name=display_currency,json=displayCurrency,proto3" json:"display_currency,omitempty"`
	// The currency token used for financial reporting and accounting purposes.
	// This may differ from display_currency and is used for official records and statements.
	// References a token from the meshtrade.type.v1.Token definition.
	ReportingCurrency *v1.Token `protobuf:"bytes,9,opt,name=reporting_currency,json=reportingCurrency,proto3" json:"reporting_currency,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_meshtrade_iam_user_profile_v1_user_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_meshtrade_iam_user_profile_v1_user_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_meshtrade_iam_user_profile_v1_user_profile_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserProfile) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *UserProfile) GetOwners() []string {
	if x != nil {
		return x.Owners
	}
	return nil
}

func (x *UserProfile) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *UserProfile) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *UserProfile) GetProfilePictureUrl() string {
	if x != nil {
		return x.ProfilePictureUrl
	}
	return ""
}

func (x *UserProfile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserProfile) GetDisplayCurrency() *v1.Token {
	if x != nil {
		return x.DisplayCurrency
	}
	return nil
}

func (x *UserProfile) GetReportingCurrency() *v1.Token {
	if x != nil {
		return x.ReportingCurrency
	}
	return nil
}

var File_meshtrade_iam_user_profile_v1_user_profile_proto protoreflect.FileDescriptor

const file_meshtrade_iam_user_profile_v1_user_profile_proto_rawDesc = "" +
	"\n" +
	"0meshtrade/iam/user_profile/v1/user_profile.proto\x12\x1dmeshtrade.iam.user_profile.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1dmeshtrade/type/v1/token.proto\"\xaf\n" +
	"\n" +
	"\vUserProfile\x12\xd2\x01\n" +
	"\x04name\x18\x01 \x01(\tB\xbd\x01\xbaH\xb9\x01\xba\x01\xb5\x01\n" +
	"\x14name.format.optional\x12>name must be empty or in the format iam/user_profiles/{ULIDv2}\x1a]size(this) == 0 || this.matches('^iam/user_profiles/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$')R\x04name\x12R\n" +
	"\x05owner\x18\x02 \x01(\tB<\xbaH9\xc8\x01\x01r42/^groups/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$\x98\x01!R\x05owner\x12V\n" +
	"\x06owners\x18\x03 \x03(\tB>\xbaH;\x92\x018\"6r42/^groups/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$\x98\x01!R\x06owners\x12\xdf\x02\n" +
	"\x04user\x18\x04 \x01(\tB\xca\x02\xbaH\xc6\x02\xba\x01V\n" +
	"\ruser.required\x125user is required and must be in format users/{ULIDv2}\x1a\x0esize(this) > 0\xba\x01\xb1\x01\n" +
	"\vuser.format\x12buser must be in format users/{ULIDv2} where ULIDv2 is exactly 26 uppercase alphanumeric characters\x1a>this.matches('^users/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$')\xc8\x01\x01r32.^users/[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$\x98\x01 R\x04user\x12\xdb\x01\n" +
	"\x06locale\x18\x05 \x01(\tB\xc2\x01\xbaH\xbe\x01\xba\x01\xba\x01\n" +
	"\rlocale.format\x12Rlocale must be empty or a valid BCP 47 language tag (e.g., 'en', 'en-US', 'fr-FR')\x1aUsize(this) == 0 || this.matches('^[a-z]{2,3}(-[A-Za-z]{4})?(-([A-Z]{2}|[0-9]{3}))?$')R\x06locale\x12\xa5\x01\n" +
	"\x13profile_picture_url\x18\x06 \x01(\tBu\xbaHr\xba\x01o\n" +
	"\x1aprofile_picture_url.format\x120profile_picture_url must be empty or a valid URI\x1a\x1fsize(this) == 0 || this.isUri()R\x11profilePictureUrl\x12)\n" +
	"\fdisplay_name\x18\a \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\vdisplayName\x12C\n" +
	"\x10display_currency\x18\b \x01(\v2\x18.meshtrade.type.v1.TokenR\x0fdisplayCurrency\x12G\n" +
	"\x12reporting_currency\x18\t \x01(\v2\x18.meshtrade.type.v1.TokenR\x11reportingCurrencyBg\n" +
	"$co.meshtrade.api.iam.user_profile.v1Z?github.com/meshtrade/api/go/iam/user_profile/v1;user_profile_v1b\x06proto3"

var (
	file_meshtrade_iam_user_profile_v1_user_profile_proto_rawDescOnce sync.Once
	file_meshtrade_iam_user_profile_v1_user_profile_proto_rawDescData []byte
)

func file_meshtrade_iam_user_profile_v1_user_profile_proto_rawDescGZIP() []byte {
	file_meshtrade_iam_user_profile_v1_user_profile_proto_rawDescOnce.Do(func() {
		file_meshtrade_iam_user_profile_v1_user_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshtrade_iam_user_profile_v1_user_profile_proto_rawDesc), len(file_meshtrade_iam_user_profile_v1_user_profile_proto_rawDesc)))
	})
	return file_meshtrade_iam_user_profile_v1_user_profile_proto_rawDescData
}

var file_meshtrade_iam_user_profile_v1_user_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meshtrade_iam_user_profile_v1_user_profile_proto_goTypes = []any{
	(*UserProfile)(nil), // 0: meshtrade.iam.user_profile.v1.UserProfile
	(*v1.Token)(nil),    // 1: meshtrade.type.v1.Token
}
var file_meshtrade_iam_user_profile_v1_user_profile_proto_depIdxs = []int32{
	1, // 0: meshtrade.iam.user_profile.v1.UserProfile.display_currency:type_name -> meshtrade.type.v1.Token
	1, // 1: meshtrade.iam.user_profile.v1.UserProfile.reporting_currency:type_name -> meshtrade.type.v1.Token
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_meshtrade_iam_user_profile_v1_user_profile_proto_init() }
func file_meshtrade_iam_user_profile_v1_user_profile_proto_init() {
	if File_meshtrade_iam_user_profile_v1_user_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshtrade_iam_user_profile_v1_user_profile_proto_rawDesc), len(file_meshtrade_iam_user_profile_v1_user_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshtrade_iam_user_profile_v1_user_profile_proto_goTypes,
		DependencyIndexes: file_meshtrade_iam_user_profile_v1_user_profile_proto_depIdxs,
		MessageInfos:      file_meshtrade_iam_user_profile_v1_user_profile_proto_msgTypes,
	}.Build()
	File_meshtrade_iam_user_profile_v1_user_profile_proto = out.File
	file_meshtrade_iam_user_profile_v1_user_profile_proto_goTypes = nil
	file_meshtrade_iam_user_profile_v1_user_profile_proto_depIdxs = nil
}
