name: Push to Registry
on:
  release:
    types: [published]

permissions:
  contents: read
jobs:
  buf-push-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
      - run: buf push --label "${{ github.event.release.tag_name }}"
