name: Deploy TypeScript SDK to npm

# Triggers on tags like ts/v1.0.0, ts/v2.1.3, etc.
on:
  push:
    tags:
      - 'ts/v*.*.*'

  # Allows manual workflow dispatch
  workflow_dispatch:

permissions:
  contents: write  # Need write permission to commit version changes back

jobs:
  npm-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Enable Corepack
        run: corepack enable

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .yarn/cache
            ts/node_modules
          key: ${{ runner.os }}-ts-deps-${{ hashFiles('yarn.lock', 'ts/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-ts-deps-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Extract version from tag
        id: version
        run: |
          # Extract version from ts/v*.*.* tag (e.g., ts/v1.2.3 -> 1.2.3)
          if [[ "${{ github.event_name }}" == "push" ]]; then
            VERSION=$(echo "${{ github.ref_name }}" | sed 's/^ts\/v//')
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "Extracted version: $VERSION"
          else
            echo "Manual workflow dispatch - version must be set manually"
            exit 1
          fi

      - name: Update package.json version
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          echo "Setting TypeScript package version to: $VERSION"
          cd ts
          # Update package.json with the extracted version
          if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" package.json
          else
            sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" package.json
          fi
          echo "Updated package.json version:"
          grep '"version":' package.json

      - name: Commit version changes
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          # Configure git for automated commits
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add and commit the version change
          git add ts/package.json
          git commit -m "chore: bump TypeScript SDK version to v$VERSION [skip ci]"
          git push origin HEAD:master
          
          echo "✅ Committed version change back to repository"

      - name: Build TypeScript SDK
        run: |
          echo "🚀 Building TypeScript SDK..."
          cd ts
          yarn build

      - name: Run TypeScript tests
        run: |
          echo "🧪 Running TypeScript tests..."
          cd ts
          yarn test

      - name: Run TypeScript linting
        run: |
          echo "🚀 Linting TypeScript code..."
          cd ts
          yarn lint

      - name: Verify build artifacts
        run: |
          echo "✅ Verifying build artifacts..."
          cd ts
          ls -la dist/ | head -10

      - name: Publish to npm
        run: |
          echo "🚀 Publishing to npm..."
          cd ts
          yarn publish --access public --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Success notification
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          echo ""
          echo "############################################################"
          echo "#                                                          #"
          echo "#  🎉 TypeScript SDK v$VERSION published to npm! 📦      #"
          echo "#                                                          #"
          echo "#  Package: @meshtrade/api@$VERSION                       #"
          echo "#  Registry: https://www.npmjs.com/package/@meshtrade/api #"
          echo "#                                                          #"
          echo "############################################################"