name: Deploy TypeScript SDK to npm via Trusted Publisher

# Triggers on tags like ts/v1.0.0, ts/v2.1.3, etc.
# Uses npm Trusted Publishing (OIDC) - no tokens required!
on:
  push:
    tags:
      - 'ts/v*.*.*'

  # Allows manual workflow dispatch
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.2.3)'
        required: true
        type: string

permissions:
  contents: write  # Need write permission to commit version changes back
  id-token: write  # Required for npm trusted publishing with OIDC

jobs:
  npm-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Enable Corepack
        run: corepack enable

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .yarn/cache
            ts/node_modules
          key: ${{ runner.os }}-ts-deps-${{ hashFiles('yarn.lock', 'ts/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-ts-deps-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup buf CLI (required for protobuf generation)
        uses: bufbuild/buf-setup-action@v1

      - name: Generate TypeScript code from protobuf
        run: ./dev/tool.sh generate --targets=typescript

      - name: Run TypeScript tests (early validation)
        working-directory: ./ts
        run: |
          echo "🧪 Running TypeScript tests..."
          yarn test

      - name: Run TypeScript linting (early validation)
        working-directory: ./ts
        run: |
          echo "🚀 Linting TypeScript code..."
          yarn lint

      - name: Extract version from tag or input
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            # Extract version from ts/v*.*.* tag (e.g., ts/v1.2.3 -> 1.2.3)
            VERSION=$(echo "${{ github.ref_name }}" | sed 's/^ts\/v//')
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "Extracted version from tag: $VERSION"
          else
            # Use version from manual workflow dispatch input
            VERSION="${{ inputs.version }}"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "Using manual version input: $VERSION"
          fi

      - name: Update package.json version
        working-directory: ./ts
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          echo "Setting TypeScript package version to: $VERSION"
          # Use yarn version to update package.json (safer and cross-platform)
          yarn version --new-version "$VERSION" --no-git-tag-version
          echo "Updated package.json version:"
          grep '"version":' package.json

      # TEMPORARILY SKIP commit-back to test npm publishing
      # - name: Commit version changes
      #   run: |
      #     # Will re-enable after confirming npm publishing works

      - name: Build TypeScript SDK
        working-directory: ./ts
        run: |
          echo "🚀 Building TypeScript SDK..."
          yarn build

      - name: Verify build artifacts
        working-directory: ./ts
        run: |
          echo "✅ Verifying build artifacts..."
          ls -la dist/ | head -10

      - name: Publish to npm via Trusted Publisher (OIDC)
        working-directory: ./ts
        run: |
          echo "🚀 Publishing to npm via Trusted Publisher..."
          # With trusted publishing configured, no token needed - uses OIDC automatically
          yarn publish --access public --non-interactive

      - name: Success notification
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          echo ""
          echo "############################################################"
          echo "#                                                          #"
          echo "#  🎉 TypeScript SDK v$VERSION published via Trusted Publisher! 📦 #"
          echo "#                                                          #"
          echo "#  Package: @meshtrade/api@$VERSION                       #"
          echo "#  Registry: https://www.npmjs.com/package/@meshtrade/api #"
          echo "#                                                          #"
          echo "############################################################"